### PR TITLE
`RelwithDebInfo` build mode support

### PR DESCRIPTION
**Pull request by zasdfgbnm**
The `RelwithDebInfo` build mode can be thought of as a mixture of release and debug build: it enable optimizations like in release build, it also keep debugging info such as line info. This is my favorite build mode, and my default build mode for PyTorch. With this build mode, tests are running as fast as in release build, while keeping the debugability close to debug build. Strongly recommend to use :)

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by naoyam** [comment]
AFAIK, it still does `-DNDEBUG`, which means, for example, `as` is done with no type check. Personally, I'd prefer to use `dynamic_cast` always no matter if `NDEBUG` is defined.

**Comment by zasdfgbnm** [comment]
> Personally, I'd prefer to use `dynamic_cast` always no matter if `NDEBUG` is defined.
I agree.

**Pull request merged**
