### PR TITLE
[codediff] Refactor codediff tool to allow merging shards

### PR DESCRIPTION
**Pull request by jacobhinkle**
This refactors `tools/codediff/diff_report.py` into `tools/codediff/codediff.py` and adds new subcommands:
- parse
- join
- diff
- diff_report

This lets us parse the output of `run_command.sh` to generate a JSON containing all the data needed for diffing. We can apply that to individual sharded tests then use the `join` subcommand to join them as if the shards were computed in a single command. After that we can `diff` the joined JSON files and create an HTML `diff_report` from the resulting `diff.json`.

This should help us fix the problem where we cannot reliably get codediffs in sharded tests because adding or removing a test can cause a different sharding, so diffing within each shard is unreliable.

Note that `diff_report.py` should still function but once we have updated pur CI to use the new way we can remove it.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!test --diff

**Comment by jacobhinkle** [comment]
Failures are due to missing `dataclasses_json` module. We need to install `tools/codediff/requirements.txt` before running `compare_codegen.sh`.

**Review by xwang233 — APPROVED** [review]
LGTM. Will work on the backend CI infra to implement the shard merging mechanism.

**Comment by jacobhinkle** [comment]
!test --diff

**Comment by jacobhinkle** [comment]
Running `!test --diff` again to check that this won't break CI, then will merge.

**Pull request merged**
