### PR TITLE
Enable fp8 on sm89

### PR DESCRIPTION
**Pull request by jjsjann123**
fp8's supported has been lifted to sm89 since PTX ISA 8.1 and later per https://docs.nvidia.com/cuda/parallel-thread-execution/

### CODE REVIEW

**Review by wujingyue — APPROVED** [review]

**Comment by jjsjann123** [comment]
!test

**Review by crcrpar — APPROVED** [review]
thank you! now I can see the same traces as in https://github.com/Lightning-AI/lightning-thunder/pull/1551 on my environment with RTX6000 Ada, with [a diff in thunder](https://github.com/Lightning-AI/lightning-thunder/pull/1576)

**Comment by jacobhinkle** [comment]
> fp8's supported has been lifted to sm89 since PTX ISA 8.1 and later per https://docs.nvidia.com/cuda/parallel-thread-execution/

Does that technically mean we only support CUDA 12+ for this feature?

**Comment by jjsjann123** [comment]
> > fp8's supported has been lifted to sm89 since PTX ISA 8.1 and later per https://docs.nvidia.com/cuda/parallel-thread-execution/
> 
> Does that technically mean we only support CUDA 12+ for this feature?

good call. I think I should conditionally relax this one, depending on the build time CUDA version.

**Comment by jjsjann123** [comment]
!test

**Comment by jjsjann123** [comment]
!test

**Comment by naoyam** [comment]
@jjsjann123 I'm seeing an error on RTX 6000 (sm_89):

```
[ RUN      ] NVFuserTest.FusionFp8CastOps_CUDA
unknown file: Failure
C++ exception with description " INTERNAL ASSERT FAILED at "/home/nmaruyama/nvfuser/debug3/csrc/runtime/executor_utils.cpp":859, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues.
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<__bfloat, 2, 2> T0, Tensor<__bfloat, 2, 2> T2) {
  __e4m3 T1[1LL];
  T1[0LL]
     = __bfloat2e4m3(T0[((T0.alloc_stride[1LL] * ((nvfuser_index_t)threadIdx.x)) + (T0.alloc_stride[0LL] * ((nvfuser_index_t)blockIdx.x)))]);
  T2[(((nvfuser_index_t)threadIdx.x) + (T0.logical_size[1LL] * ((nvfuser_index_t)blockIdx.x)))]
     = __e4m32bfloat(T1[0LL]);
}
}

CUDA NVRTC compile error: ptxas application ptx input, line 47; error   : Feature 'cvt with .f16.bf16' requires .target sm_90 or higher
ptxas application ptx input, line 58; error   : Feature 'cvt with .bf16.f16' requires .target sm_90 or higher
ptxas fatal   : Ptx assembly aborted due to errors

Exception raised from invoke at /home/nmaruyama/nvfuser/debug3/csrc/runtime/executor_utils.cpp:859 (most recent call first):
```

**Comment by jjsjann123** [comment]
Did I get the cuda TK check wrong?! I thought CUDA TK version would determine PTX ISA version...

Are you running this in a container? I'm curious how the setup is like.
sm_89 should have fp8 support since cuda 12.1.

**Comment by naoyam** [comment]
This is on my own container with 12.6.

**Comment by jjsjann123** [comment]
wait, it's not complaining about fp8 though..

`cvt with .bf16.f16`

**Comment by jjsjann123** [comment]
looks like cvt to/from bf16 does require sm_90. https://docs.nvidia.com/cuda/parallel-thread-execution/#data-movement-and-conversion-instructions-cvt

I wonder why our check is only requiring sm_80. https://github.com/NVIDIA/Fuser/blob/6466834d563bcd48eb9baf8e72177fb108f689f4/csrc/device_lower/analysis/device_version.cpp#L17-L21

Looks like this is just a [test thing](https://github.com/NVIDIA/Fuser/blob/6466834d563bcd48eb9baf8e72177fb108f689f4/tests/cpp/test_gpu1.cpp#L2679-L2682). I'll update that along with the checks. Thanks for raising the issue @naoyam

**Comment by jjsjann123** [comment]
> .relu modifier and {.f16x2, .bf16, .bf16x2, .tf32} destination formats require sm_80 or higher.
> cvt.bf16.{u8/s8/u16/s16/u32/s32/u64/s64/f16/f64/bf16}, cvt.{u8/s8/u16/s16/u32/s32/u64/s64/f16/f64}.bf16, and cvt.tf32.f32.{relu}.{rn/rz} require sm_90 or higher.

**Comment by wujingyue** [comment]
FusionFp8CastOps_CUDA is apparently broken for me. My workstation has sm 8.9 and cuda 12.8. 

```
>>> torch.version.cuda
'12.8'
```

```
$ nvidia-smi -L
GPU 0: NVIDIA RTX 6000 Ada Generation (UUID: <redacted>)
GPU 1: NVIDIA RTX 6000 Ada Generation (UUID: <redacted>)
```

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from NVFuserTest
[ RUN      ] NVFuserTest.FusionFp8CastOps_CUDA
unknown file: Failure
C++ exception with description " INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/runtime/executor_utils.cpp":855, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues.
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<__bfloat, 2, 2> T0, Tensor<__bfloat, 2, 2> T2) {
  __e4m3 T1[1LL];
  T1[0LL]
     = __bfloat2e4m3(T0[((T0.alloc_stride[1LL] * ((nvfuser_index_t)threadIdx.x)) + (T0.alloc_stride[0LL] * ((nvfuser_index_t)blockIdx.x)))]);
  T2[(((nvfuser_index_t)threadIdx.x) + (T0.logical_size[1LL] * ((nvfuser_index_t)blockIdx.x)))]
     = __e4m32bfloat(T1[0LL]);
}
}

CUDA NVRTC compile error: ptxas application ptx input, line 47; error   : Feature 'cvt with .f16.bf16' requires .target sm_90 or higher
ptxas application ptx input, line 58; error   : Feature 'cvt with .bf16.f16' requires .target sm_90 or higher
ptxas fatal   : Ptx assembly aborted due to errors

Exception raised from invoke at /opt/pytorch/nvfuser/csrc/runtime/executor_utils.cpp:855 (most recent call first):
frame #0: <unknown function> + 0x1d4d37 (0x642775ac3d37 in bin/nvfuser_tests)
frame #1: <unknown function> + 0x5e42d2 (0x642775ed32d2 in bin/nvfuser_tests)
frame #2: <unknown function> + 0x94d677 (0x64277623c677 in bin/nvfuser_tests)
frame #3: <unknown function> + 0x92bc26 (0x64277621ac26 in bin/nvfuser_tests)
frame #4: <unknown function> + 0xc16ba6 (0x642776505ba6 in bin/nvfuser_tests)
frame #5: <unknown function> + 0xd4ec73 (0x64277663dc73 in bin/nvfuser_tests)
frame #6: <unknown function> + 0x12a7541 (0x642776b96541 in bin/nvfuser_tests)
frame #7: <unknown function> + 0x128f05a (0x642776b7e05a in bin/nvfuser_tests)
frame #8: <unknown function> + 0x128f612 (0x642776b7e612 in bin/nvfuser_tests)
frame #9: <unknown function> + 0x128fc51 (0x642776b7ec51 in bin/nvfuser_tests)
frame #10: <unknown function> + 0x129d7fa (0x642776b8c7fa in bin/nvfuser_tests)
frame #11: <unknown function> + 0x128fe4a (0x642776b7ee4a in bin/nvfuser_tests)
frame #12: <unknown function> + 0x39c6d4 (0x642775c8b6d4 in bin/nvfuser_tests)
frame #13: <unknown function> + 0x2a1ca (0x7ae252dc11ca in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #14: __libc_start_main + 0x8b (0x7ae252dc128b in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #15: <unknown function> + 0x39cc55 (0x642775c8bc55 in bin/nvfuser_tests)
" thrown in the test body.

To reproduce: NVFUSER_TEST_RANDOM_SEED=1737141197 NVFUSER_TEST_ATEN_RANDOM_SEED=0 nvfuser_tests --gtest_filter='NVFuserTest.FusionFp8CastOps_CUDA'
[  FAILED  ] NVFuserTest.FusionFp8CastOps_CUDA (208 ms)
[----------] 1 test from NVFuserTest (208 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (208 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] NVFuserTest.FusionFp8CastOps_CUDA

 1 FAILED TEST
```

**Comment by wujingyue** [comment]
Oh, I think it's the same as https://github.com/NVIDIA/Fuser/pull/3624#issuecomment-2566143737

**Comment by jjsjann123** [comment]
> Oh, I think it's the same as [#3624 (comment)](https://github.com/NVIDIA/Fuser/pull/3624#issuecomment-2566143737)

oops, sorry for dropping the ball. I can get a PR up to fix the test.

**Comment by jjsjann123** [comment]
verified the issue. Turns out it's indeed the fp8 runtime I added. Verified the fix in #3727

**Pull request merged**
