### PR TITLE
clean 2dInnerReductionHeuristic

### PR DESCRIPTION
**Pull request by liqiangxl**
Following https://github.com/NVIDIA/Fuser/pull/3330
Removed paras and computations related to 3D inner reduction.

### CODE REVIEW

**Comment by liqiangxl** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
stamp for mechanical changes.
nitpick: let's do a code diff to verify that this one isn't introducing any behavior change.

**Comment by liqiangxl** [comment]
!build !test --diff --diff-bench

**Comment by liqiangxl** [comment]
!test --diff --diff-bench

**Comment by liqiangxl** [comment]
@jjsjann123 code diffs are known issues where order of output is changed.

**Pull request merged**
