### PR TITLE
Remove bit_cast to convert MmaMacroEncode to uint64_t

### PR DESCRIPTION
**Pull request by jacobhinkle**
This standardizes how we convert `MmaMacroEncode` to `uint64_t`. Doing this with a bitcast actually gives us UB because we are not guaranteed to have the given order for struct fields defined as bitfields. I first noticed this was happening when using a `libnvfuser.so` compiled as C++20 with another project linking against that was compiled using C++17. In that case, the compilation and linking worked properly, but we wound up with garbage for the `MmaMacro`. I think this PR will address this kind of issue.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Review by zasdfgbnm — COMMENTED** [review]
Do we also want to remove `MmaMacroEncode::operator MmaMacro` and the constructor?

**Comment by jacobhinkle** [comment]
> Do we also want to remove `MmaMacroEncode::operator MmaMacro` and the constructor?

Removing them would require some unergonomic changes to other parts of the code, so I just modified them by removing the `#if`.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
At this point the only use of `IS_CPP20` is here: https://github.com/NVIDIA/Fuser/blob/55971f8811243822983edf8510b3fa26524d1f15/tests/cpp/test_matmul.cpp#L484-L488

**Comment by jacobhinkle** [comment]
!build

**Pull request merged**
