### PR TITLE
Python API supports dynamic reshape. 

### PR DESCRIPTION
**Pull request by wujingyue**
1. Add the python binding for dynamic reshape. 
2. Remove the `original_shape` parameter from static reshape. I don't see why it's necessary. Because this changes the API, this PR also bumps up the version number. A separate PR adds a version check at the framework level so they'll be compatible. 
3. Add op tests and a Python frontend test for dynamic reshapes.

### CODE REVIEW

**Comment by kevinstephano** [comment]
Adding dynamic reshape has been in the works for a while with a sequence of PRs where the last one to merge was the following: https://github.com/NVIDIA/Fuser/pull/721 for `broadcast_in_dim`.  These PRs are doing more than just utilizing the API from the C++ side, they are allowing the user to specify inputs as vectors python numbers, vector of Scalars, and a mix of both. The next PR which was this one, https://github.com/NVIDIA/Fuser/pull/417,  was on hold due to trying address the verbose printing that currently is happen due to these changes that does not look like a good user experience.  Swapping out the APIs is also a little more difficult than just changing the API at the Python level as it has to be orchestrated at the Framework level as well.

**Comment by wujingyue** [comment]
I wish I had known #417 and what you have tried earlier! 

> trying address the verbose printing that currently is happen due to these changes that does not look like a good user experience

Can you say more about this? Is it something I can fix? Not having to specify the original shape and being able to specify a dynamic target shape are user experience improvements to me. But I'd love to know about the downside. 

> has to be orchestrated at the Framework level as well.

Can I change the usage so it works with both versions (w/ original_shape and w/o) before submitting #417 or this PR?

**Comment by jjsjann123** [comment]
so wondering if we have a concrete plan moving forward with the API changes?

**Comment by wujingyue** [comment]
> so wondering if we have a concrete plan moving forward with the API changes?

I should have updated the thread after my offline chat with @kevinstephano . The order of actions is:

1. Add a version check at the framework level so changing the number of parameters of `fd.ops.reshape` won't break anything. 
2. Get this PR reviewed and merged. 
3. Improve the usability by allowing users to pass in a list of Python scalars as the target shape (instead of a list of `define_scalar`s).

**Comment by wujingyue** [comment]
This is now ready for review!

**Review by jjsjann123 — APPROVED** [review]
LGTM

**Comment by jjsjann123** [comment]
!build

**Review by rdspring1 — APPROVED** [review]
LGTM

**Pull request merged**
