### PR TITLE
Check for SliceOp before inserting casts

### LINKED ISSUE #1953: Intermediate downcasting interferes with segmentation of slice
The following script fails in a similar manner to #1541.
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id17(fd : FusionDefinition) -> None :
    S0 = fd.define_scalar(None, dtype=DataType.Int)
    S1 = fd.define_scalar(None, dtype=DataType.Int)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(None, dtype=DataType.Int)
    S4 = fd.define_scalar(None, dtype=DataType.Int)
    S5 = fd.define_scalar(None, dtype=DataType.Int)
    S6 = fd.define_scalar(None, dtype=DataType.Int)
    S7 = fd.define_scalar(None, dtype=DataType.Int)
    S8 = fd.define_scalar(None, dtype=DataType.Int)
    S9 = fd.define_scalar(None, dtype=DataType.Int)
    T10 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[None, True, None, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T11 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[None, True, None, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T12 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 1, 2, 0])
    T13 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 1, 2, 0])
    T14 = fd.ops.cast(T13, dtype=DataType.Float)
    T15 = fd.ops.permute(T14, dims=[0, 2, 1, 3])
    S16 = fd.define_scalar(128, dtype=DataType.Int)
    S17 = fd.define_scalar(256, dtype=DataType.Int)
    S18 = fd.define_scalar(6, dtype=DataType.Int)
    S19 = fd.define_scalar(24, dtype=DataType.Int)
    S20 = fd.define_scalar(2, dtype=DataType.Int)
    V21 = fd.define_vector([S16, S17, S18, S19, S20], dtype=DataType.Int)
    T22 = fd.ops.reshape(T15, new_shape=V21)
    T23 = fd.ops.slice(T22, start_indices=[0, 0, 0, 0, 0], end_indices=[128, 256, 6, 24, 1], strides=[1, 1, 1, 1, 1])
    T24 = fd.ops.slice(T22, start_indices=[0, 0, 0, 0, 1], end_indices=[128, 256, 6, 24, 2], strides=[1, 1, 1, 1, 1])
    T25 = fd.ops.sum(T24, dims=[4], keepdim=False, dtype=DataType.Null)
    T26 = fd.ops.sum(T23, dims=[4], keepdim=False, dtype=DataType.Null)
    T27 = fd.ops.mul(T25, T10)
    T28 = fd.ops.mul(T25, T11)
    T29 = fd.ops.neg(T26)
    T30 = fd.ops.mul(T29, T11)
    T31 = fd.ops.add(T27, T30)
    T32 = fd.ops.cast(T31, dtype=DataType.BFloat16)
    T33 = fd.ops.mul(T26, T10)
    T34 = fd.ops.add(T28, T33)
    T35 = fd.ops.cast(T34, dtype=DataType.BFloat16)
    S36 = fd.define_scalar(128, dtype=DataType.Int)
    S37 = fd.define_scalar(256, dtype=DataType.Int)
    S38 = fd.define_scalar(6, dtype=DataType.Int)
    S39 = fd.define_scalar(24, dtype=DataType.Int)
    S40 = fd.define_scalar(1, dtype=DataType.Int)
    V41 = fd.define_vector([S36, S37, S38, S39, S40], dtype=DataType.Int)
    T42 = fd.ops.broadcast_in_dim(T32, shape=V41, broadcast_dims=[0, 1, 2, 3])
    S43 = fd.define_scalar(128, dtype=DataType.Int)
    S44 = fd.define_scalar(256, dtype=DataType.Int)
    S45 = fd.define_scalar(6, dtype=DataType.Int)
    S46 = fd.define_scalar(24, dtype=DataType.Int)
    S47 = fd.define_scalar(1, dtype=DataType.Int)
    V48 = fd.define_vector([S43, S44, S45, S46, S47], dtype=DataType.Int)
    T49 = fd.ops.broadcast_in_dim(T35, shape=V48, broadcast_dims=[0, 1, 2, 3])
    S50 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T51 = fd.ops.pad(T42, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0], S50)
    S52 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T53 = fd.ops.pad(T49, [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], S52)
    T54 = fd.ops.cast(T51, dtype=DataType.Float)
    T55 = fd.ops.cast(T53, dtype=DataType.Float)
    T56 = fd.ops.add(T54, T55)
    T57 = fd.ops.cast(T56, dtype=DataType.BFloat16)
    T58 = fd.ops.cast(T12, dtype=DataType.Float)
    T59 = fd.ops.permute(T58, dims=[0, 2, 1, 3])
    S60 = fd.define_scalar(128, dtype=DataType.Int)
    S61 = fd.define_scalar(256, dtype=DataType.Int)
    S62 = fd.define_scalar(6, dtype=DataType.Int)
    S63 = fd.define_scalar(24, dtype=DataType.Int)
    S64 = fd.define_scalar(2, dtype=DataType.Int)
    V65 = fd.define_vector([S60, S61, S62, S63, S64], dtype=DataType.Int)
    T66 = fd.ops.reshape(T59, new_shape=V65)
    T67 = fd.ops.slice(T66, start_indices=[0, 0, 0, 0, 0], end_indices=[128, 256, 6, 24, 1], strides=[1, 1, 1, 1, 1])
    T68 = fd.ops.slice(T66, start_indices=[0, 0, 0, 0, 1], end_indices=[128, 256, 6, 24, 2], strides=[1, 1, 1, 1, 1])
    T69 = fd.ops.sum(T68, dims=[4], keepdim=False, dtype=DataType.Null)
    T70 = fd.ops.sum(T67, dims=[4], keepdim=False, dtype=DataType.Null)
    T71 = fd.ops.mul(T69, T10)
    T72 = fd.ops.mul(T69, T11)
    T73 = fd.ops.neg(T70)
    T74 = fd.ops.mul(T73, T11)
    T75 = fd.ops.add(T71, T74)
    T76 = fd.ops.cast(T75, dtype=DataType.BFloat16)
    T77 = fd.ops.mul(T70, T10)
    T78 = fd.ops.add(T72, T77)
    T79 = fd.ops.cast(T78, dtype=DataType.BFloat16)
    S80 = fd.define_scalar(128, dtype=DataType.Int)
    S81 = fd.define_scalar(256, dtype=DataType.Int)
    S82 = fd.define_scalar(6, dtype=DataType.Int)
    S83 = fd.define_scalar(24, dtype=DataType.Int)
    S84 = fd.define_scalar(1, dtype=DataType.Int)
    V85 = fd.define_vector([S80, S81, S82, S83, S84], dtype=DataType.Int)
    T86 = fd.ops.broadcast_in_dim(T76, shape=V85, broadcast_dims=[0, 1, 2, 3])
    S87 = fd.define_scalar(128, dtype=DataType.Int)
    S88 = fd.define_scalar(256, dtype=DataType.Int)
    S89 = fd.define_scalar(6, dtype=DataType.Int)
    S90 = fd.define_scalar(24, dtype=DataType.Int)
    S91 = fd.define_scalar(1, dtype=DataType.Int)
    V92 = fd.define_vector([S87, S88, S89, S90, S91], dtype=DataType.Int)
    T93 = fd.ops.broadcast_in_dim(T79, shape=V92, broadcast_dims=[0, 1, 2, 3])
    S94 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T95 = fd.ops.pad(T86, [1, 0, 0, 0, 0, 0, 0, 0, 0, 0], S94)
    S96 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T97 = fd.ops.pad(T93, [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], S96)
    T98 = fd.ops.cast(T95, dtype=DataType.Float)
    T99 = fd.ops.cast(T97, dtype=DataType.Float)
    T100 = fd.ops.add(T98, T99)
    T101 = fd.ops.cast(T100, dtype=DataType.BFloat16)
    fd.add_output(T57)
    fd.add_output(T101)

with FusionDefinition() as fd:
    nvfuser_fusion_id17(fd)

inputs = [
    128,
    256,
    6,
    24,
    2,
    128,
    256,
    6,
    24,
    2,
    torch.randn((6144,), dtype=torch.float32, device='cuda:0').as_strided((128, 256, 6, 24), (0, 24, 0, 1)),
    torch.randn((6144,), dtype=torch.float32, device='cuda:0').as_strided((128, 256, 6, 24), (0, 24, 0, 1)),
    torch.randn((9437184,), dtype=torch.bfloat16, device='cuda:0').as_strided((128, 6, 256, 48), (73728, 48, 288, 1)),
    torch.randn((9437184,), dtype=torch.bfloat16, device='cuda:0').as_strided((128, 6, 256, 48), (73728, 48, 288, 1)),
]
fd.execute(inputs)
```
The issue is that the segmenter creates a segment consisting only of a slice, but `castInputOutputToLowerPrecision` inserts casts. That violates the requirement that slice have no upstream expressions within a segment, so we fail to segment the fusion.

### PR DESCRIPTION
**Pull request by jacobhinkle**
We already check for select-based ops because they must be the first op in the segment. This PR just adds SliceOp to the list of types to check.

This current approach is flawed, since it will cause some segments to not cast at all, leading to increased IO. Instead, we should probably forward the casts through incompatible ops instead of skipping inserting casts altogether.

Fixes #1953.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
As I understand it, this is what `castInputOutputToLowerPrecision()` currently does:
- Looks at all segmentation edges
- If that edge is set to be cast to fp16/bf16, find all uses that aren't select ops and insert h->s casts in front of those uses
- If any casts were inserted in the previous step, insert an s->h cast downstream of this edge and update the edge position to the new half-precision tensor

I think the issue is in step two where we just skip inserting casts for select-like ops. Instead, we should forward through incompatible ops at that point. Essentially we should flow forward from the segmentation edge until we find an arithmetic op or another segmentation edge, and place the casts at that frontier. That will automatically skip ops that don't need the upcast and those that are incompatible with it like select or slice. I think we need to update the dtypes as we propagate though, otherwise I'm not sure how we will know whether downstream edges need producer-side s->h casts or not.

**Review by wujingyue — APPROVED** [review]
Can you add a unit test?

**Comment by jacobhinkle** [comment]
> Can you add a unit test?

I added a repro for #1953  and also an isolated C++ test that we should update when we change the cast insertion so that we handle slice segments.

**Pull request merged**
