### PR TITLE
Add support for `torch.minimum` and `torch.maximum` operations

### PR DESCRIPTION
**Pull request by rdspring1**
This PR adds the `minimum` and `maximum` operators to nvfuser.

- https://pytorch.org/docs/stable/generated/torch.minimum.html
- https://pytorch.org/docs/stable/generated/torch.maximum.html

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Review by jacobhinkle — APPROVED** [review]
Sounds good to me

**Review by jjsjann123 — APPROVED** [review]
:ship:

**Comment by rdspring1** [comment]
!build

**Pull request merged**
