### PR TITLE
one full wave

### PR DESCRIPTION
**Pull request by liqiangxl**
Only do multi reductions per block if we need at least 2 waves.

### CODE REVIEW

**Comment by naoyam** [comment]
The change seems to make sense. What do the benchmark performances look like?

**Comment by liqiangxl** [comment]
> The change seems to make sense. What do the benchmark performances look like?

On top of main, there is no noticable change, becase the multi-reductions-per-block is rarelly used.
But on top of #386 , there are noticable improvement, becase multi-reductions-per-block are used more frequently. (the point dropped to 0 is not repeatable)
image

**Comment by naoyam** [comment]
Is the graph comparing `main` and this PR? Or is the comparison done on top of #386?

> the point dropped to 0 is a baseline case, ideally it should not change, may due to memory allocation)

Sorry I don't understand what you mean.

**Comment by naoyam** [comment]
Looks like you edited my post. I reverted your edit as it's confusing. Can you repost your response?

**Comment by naoyam** [comment]
> > Is the graph comparing `main` and this PR? Or is the comparison done on top of #386?
> 
> the graph is done on top of #386.
> 
> > > the point dropped to 0 is a baseline case, ideally it should not change, may due to memory allocation)
> > 
> > 
> > Sorry I don't understand what you mean.
> 
> I mean this case. It is a baseline case, ideally its bandwidth should not change. However, it changed, the reason may due to memory allocation.
> 
> image

Is the result reproducible? It seems it's pretty small case, so some fluctuations are expected, but this large spike seems concerning.

**Comment by liqiangxl** [comment]
> > > Is the graph comparing `main` and this PR? Or is the comparison done on top of #386?
> > 
> > 
> > the graph is done on top of #386.
> > > > the point dropped to 0 is a baseline case, ideally it should not change, may due to memory allocation)
> > > 
> > > 
> > > Sorry I don't understand what you mean.
> > 
> > 
> > I mean this case. It is a baseline case, ideally its bandwidth should not change. However, it changed, the reason may due to memory allocation.
> > image
> 
> Is the result reproducible? It seems it's pretty small case, so some fluctuations are expected, but this large spike seems concerning.



> > > Is the graph comparing `main` and this PR? Or is the comparison done on top of #386?
> > 
> > 
> > the graph is done on top of #386.
> > > > the point dropped to 0 is a baseline case, ideally it should not change, may due to memory allocation)
> > > 
> > > 
> > > Sorry I don't understand what you mean.
> > 
> > 
> > I mean this case. It is a baseline case, ideally its bandwidth should not change. However, it changed, the reason may due to memory allocation.
> > image
> 
> Is the result reproducible? It seems it's pretty small case, so some fluctuations are expected, but this large spike seems concerning.

Not reproducible.

**Comment by naoyam** [comment]
OK, then never mind. I'll approve the PR as the change makes sense, even though the impact on top of TOT may be negligible.

**Pull request merged**
