### PR TITLE
calculate SOL using 1G = 1e9 instead of 1024^3

### PR DESCRIPTION
**Pull request by liqiangxl**

### CODE REVIEW

**Review by xwang233 — APPROVED** [review]
LGTM

**Review by naoyam — CHANGES_REQUESTED** [review]
As I mentioned offline, I don't think this is the right fix.

**Review by xwang233 — CHANGES_REQUESTED** [review]
we shouldn't modify metrics in place while still using the same name

[placeholder for request changes]

**Comment by Priya2698** [comment]
@liqiangxl is out of office, but if we have come to a conclusion we can merge this PR. From the offline discussion, it seemed we will have the existing field, and add the `Bandwidth_v2` as a new field that uses 1e9. @naoyam, @xwang233 do you agree with this?

**Comment by naoyam** [comment]
I'm good as long as we eventually remove `Bandwidth_v2` and just keep `Bandwidth` using `1e9`.

**Comment by Priya2698** [comment]
> I'm good as long as we eventually remove `Bandwidth_v2` and just keep `Bandwidth` using `1e9`.

@xwang233, if we choose to have these two variables now, then we will eventually still modify the metric computation while keeping the same name. `Bandwidth_v2` is a transition period (a month?) and finally `Bandwidth_v2 -> Bandwidth`. Do you agree with this plan?

**Comment by xwang233** [comment]
I can't agree to post data with different meanings into database with same name.

**Review by naoyam — APPROVED** [review]
LGTM

**Review by xwang233 — APPROVED** [review]

**Comment by liqiangxl** [comment]
!build

**Pull request merged**
