### PR TITLE
Remove MultiDeviceEnvironment for simplicity.

### PR DESCRIPTION
**Pull request by wujingyue**

### CODE REVIEW

**Comment by wujingyue** [comment]
!build --dist

**Comment by wujingyue** [comment]
Fails on nvdl-smc-01 at this moment:

```
NVFUSER_MULTIDEVICE_DEBUG_PRINT=1 NVFUSER_MULTIDEVICE_DEBUG_BARRIER=1 mpirun -np 4 bin/test_multidevice --gtest_filter=Gather*40
```

**Comment by wujingyue** [comment]
!build --dist

**Review by cowanmeg — APPROVED** [review]
LGTM! This cleans up a lot of duplicated code between MultiDeviceEnv and MultiDeviceTest!

**Pull request merged**
