### PR TITLE
Fix type consistency in SingleTileWithTMALoadStoreStMatrix for fusion.manage.

### PR DESCRIPTION
**Pull request by csarofeen**
This was causing errors in one of my development branches. We need to be consistent with types that we manage with fusion when storing and getting.

### CODE REVIEW

**Comment by naoyam** [comment]
@protonu Can you please change the type of `tile_sizes` to `int64_t`.

https://github.com/NVIDIA/Fuser/blob/main/tests/cpp/test_mma.cpp#L418

We just use `int64_t` for any integer data unless required to be other integer types. The cast shouldn't be necessary with this change.

**Review by protonu — APPROVED** [review]

**Comment by protonu** [comment]
I'll accept this change and send a new PR to fix the type.

**Comment by protonu** [comment]
!test

**Comment by zasdfgbnm** [comment]
Just realized that my PR hasn’t been merged yet: https://github.com/NVIDIA/Fuser/pull/3521
I believe this PR will ensure consistency of type during cloning, and push the error to the point when we get the managed data in lowering.

**Comment by protonu** [comment]
> Just realized that my PR hasn’t been merged yet: #3521 I believe this PR will ensure consistency of type during cloning, and push the error to the point when we get the managed data in lowering.

@zasdfgbnm  I missed your PR. I landed this a minute ago (https://github.com/NVIDIA/Fuser/pull/3614). You may need to rebase.

**Pull request merged**
