### PR TITLE
RMS Norm benchmark

### PR DESCRIPTION
**Pull request by Priya2698**
`rms_norm` fwd and bwd benchmarks: Ports the benchmarks at: https://github.com/NVIDIA/Fuser/blob/main/benchmark/rms_norm.cpp and https://github.com/NVIDIA/Fuser/blob/main/benchmark/rms_norm_backward.cpp

### CODE REVIEW

**Comment by naoyam** [comment]
@liqiangxl Please review

**Comment by liqiangxl** [comment]
Did you run these tests? with `root@nvdl-a112-d002:/opt/pytorch/nvfuser# pytest python_benchmarks/test_rmsnorm.py`  I got some validation errors:
```
==================================================================================================================================================================== short test summary info =====================================================================================================================================================================
FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(32, 1048576)] - AssertionError: Max error: 7.62939453125e-06,                     Absolute tolerance: 6.75395e-06, Relative tolerance: 6.753950000000001e-08
FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(64, 524288)] - AssertionError: Max error: 1.1444091796875e-05,                     Absolute tolerance: 8.57934e-06, Relative tolerance: 8.57934e-08
FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(64, 1048576)] - AssertionError: Max error: 1.1444091796875e-05,                     Absolute tolerance: 8.57934e-06, Relative tolerance: 8.57934e-08
FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(128, 262144)] - AssertionError: Max error: 1.52587890625e-05,                     Absolute tolerance: 1.30594e-05, Relative tolerance: 1.30594e-07
FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(128, 524288)] - AssertionError: Max error: 1.33514404296875e-05,                     Absolute tolerance: 1.30594e-05, Relative tolerance: 1.30594e-07
FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(256, 1048576)] - AssertionError: Max error: 3.814697265625e-05,                     Absolute tolerance: 2.19122e-05, Relative tolerance: 2.19122e-07
=========================================================================================================================================================== 6 failed, 354 passed, 6 warnings in 43.80s =======================================
```
Looks like the tolerence is too small.

**Comment by Priya2698** [comment]
> Did you run these tests? with `root@nvdl-a112-d002:/opt/pytorch/nvfuser# pytest python_benchmarks/test_rmsnorm.py` I got some validation errors:
> 
> ```
> ==================================================================================================================================================================== short test summary info =====================================================================================================================================================================
> FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(32, 1048576)] - AssertionError: Max error: 7.62939453125e-06,                     Absolute tolerance: 6.75395e-06, Relative tolerance: 6.753950000000001e-08
> FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(64, 524288)] - AssertionError: Max error: 1.1444091796875e-05,                     Absolute tolerance: 8.57934e-06, Relative tolerance: 8.57934e-08
> FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(64, 1048576)] - AssertionError: Max error: 1.1444091796875e-05,                     Absolute tolerance: 8.57934e-06, Relative tolerance: 8.57934e-08
> FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(128, 262144)] - AssertionError: Max error: 1.52587890625e-05,                     Absolute tolerance: 1.30594e-05, Relative tolerance: 1.30594e-07
> FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(128, 524288)] - AssertionError: Max error: 1.33514404296875e-05,                     Absolute tolerance: 1.30594e-05, Relative tolerance: 1.30594e-07
> FAILED python_benchmarks/test_rmsnorm.py::test_rmsnorm_bwd_benchmark[torch.float32-(256, 1048576)] - AssertionError: Max error: 3.814697265625e-05,                     Absolute tolerance: 2.19122e-05, Relative tolerance: 2.19122e-07
> =========================================================================================================================================================== 6 failed, 354 passed, 6 warnings in 43.80s =======================================
> ```
> 
> Looks like the tolerence is too small.

I ran the tests again. The validation passes on my workstation. This means that the errors can be flaky. Which machine are you using?

**Comment by xwang233** [comment]
@liqiangxl are you running the benchmark on A100? If so, do we need to disable TF32 for benchmark?

**Comment by liqiangxl** [comment]
> @liqiangxl are you running the benchmark on A100? If so, do we need to disable TF32 for benchmark?

Yes. I was testing the benchmark on A100. I don't think we need to disable these tests. Right now we are not running them through CI yet.  After CI is enabled and these tolerence errors are being captured, we need to bump the tolerence to avoid these false positive errors.

**Review by liqiangxl — APPROVED** [review]
LGTM.

**Comment by naoyam** [comment]
> > @liqiangxl are you running the benchmark on A100? If so, do we need to disable TF32 for benchmark?
> 
> Yes. I was testing the benchmark on A100. I don't think we need to disable these tests. Right now we are not running them through CI yet. After CI is enabled and these tolerence errors are being captured, we need to bump the tolerence to avoid these false positive errors.

Do we need to manually adjust tolerances? The whole point of the automatic threshold adjustment is to avoid manual adjustment. @Priya2698 , if you're not seeing errors on your system, please try it on one of the A100 machines. Fixing the validation is not directly tied to this PR, so it's fine to work on it separately, but please make sure to keep track of it as a github issue or something.

**Comment by Priya2698** [comment]
> > > @liqiangxl are you running the benchmark on A100? If so, do we need to disable TF32 for benchmark?
> > 
> > 
> > Yes. I was testing the benchmark on A100. I don't think we need to disable these tests. Right now we are not running them through CI yet. After CI is enabled and these tolerence errors are being captured, we need to bump the tolerence to avoid these false positive errors.
> 
> Do we need to manually adjust tolerances? The whole point of the automatic threshold adjustment is to avoid manual adjustment. @Priya2698 , if you're not seeing errors on your system, please try it on one of the A100 machines. Fixing the validation is not directly tied to this PR, so it's fine to work on it separately, but please make sure to keep track of it as a github issue or something.

Manually adjusting tolerances will not be a feasible solution since we have a wide range of inputs. When I generate the validation tolerances for larger reduction sizes, I'll re-evaluate the current validation tolerances as well. For now, I am waiting to see if we get any issues on our nightly CI. 
I had run the tests on A100 on `dlcluster` and did not run into this issue. Given that the max error that @liqiangxl are close to the maximum permissible tolerance, it seems that the errors are not persistent and variable between runs.

**Comment by naoyam** [comment]
> > > > @liqiangxl are you running the benchmark on A100? If so, do we need to disable TF32 for benchmark?
> > > 
> > > 
> > > Yes. I was testing the benchmark on A100. I don't think we need to disable these tests. Right now we are not running them through CI yet. After CI is enabled and these tolerence errors are being captured, we need to bump the tolerence to avoid these false positive errors.
> > 
> > 
> > Do we need to manually adjust tolerances? The whole point of the automatic threshold adjustment is to avoid manual adjustment. @Priya2698 , if you're not seeing errors on your system, please try it on one of the A100 machines. Fixing the validation is not directly tied to this PR, so it's fine to work on it separately, but please make sure to keep track of it as a github issue or something.
> 
> Manually adjusting tolerances will not be a feasible solution since we have a wide range of inputs. When I generate the validation tolerances for larger reduction sizes, I'll re-evaluate the current validation tolerances as well. For now, I am waiting to see if we get any issues on our nightly CI. I had run the tests on A100 on `dlcluster` and did not run into this issue. Given that the max error that @liqiangxl are close to the maximum permissible tolerance, it seems that the errors are not persistent and variable between runs.

OK, then I assume that depends on the random number seed. Let's pick one that passes and stick to it.

**Comment by csarofeen** [comment]
@Priya2698 could you check the heuristics used in the failing tolerance cases?

**Pull request merged**
