### PR TITLE
Enable object-based API option when compiling FlatBuffers schema

### PR DESCRIPTION
**Pull request by rdspring1**
The PR enables the FlatBuffers object-based API. It allows for using FlatBuffers objects directly in the NvFuser codebase and then serializing those objects without any extra translation steps.

> --gen-object-api : Generate an additional object-based API. This API is more convenient for object construction and mutation than the base API, at the cost of efficiency (object allocation). Recommended only to be used if other options are insufficient.

https://flatbuffers.dev/flatbuffers_guide_use_cpp.html

This option complements the existing API, so you can use it as-needed. Normally, after deserialization, the FlatBuffer is deleted from memory, so you lose access to the data. This option defines a cpp struct for each table. You can then unpack data into a struct for persistent storage.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
This reads concerning. `Recommended only to be used if other options are insufficient`.

I guess serialization isn't a efficiency-critical module. But are we sure this is a price that we want to pay? It's hard to make a call on what the benefit is here. i.e. I imagine this would allow us to simply the plumbing between flatbuffer to our codegen pieces. Do we have any rough idea to show how much that's going to help?

But in the meantime, if this allows us faster iteration on development. Let's merge as-is and we can revisit this and pay our plumbing debt then.

**Comment by rdspring1** [comment]
> FlatBuffers is all about memory efficiency, which is why its base API is written around using as little as possible of it. This does make the API clumsier (requiring pre-order construction of all data, and making mutation harder).
>
> For times when efficiency is less important a more convenient object based API can be used (through --gen-object-api) that is able to unpack & pack a FlatBuffer into objects and standard STL containers, allowing for convenient construction, access and mutation.

This option complements the existing API, so you can use it as-needed. Normally, after deserialization, the FlatBuffer is deleted from memory, so you lose access to the data. This option defines a cpp struct for each table. You can then unpack data into a struct for persistent storage.

**Pull request merged**
