### PR TITLE
Mostly mechanical cleanup

### PR DESCRIPTION
**Pull request by naoyam**
Also added a disable option to disable contiguous indexing for testing

### CODE REVIEW

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Review by zasdfgbnm — APPROVED** [review]

**Comment by naoyam** [comment]
The codegen diff results are unexpected. I suspect they are false alarms but will wait for @jacobhinkle's update.

**Comment by jacobhinkle** [comment]
> The codegen diff results are unexpected. I suspect they are false alarms but will wait for @jacobhinkle's update.

I'm looking into this now with @xwang233 . Until we have a fix, you can run codediff locally by checkout out the branch (it must be clean) and running `tools/codediff/compare_codegen.sh`. With no arguments it will run all the tests.

**Pull request merged**
