### PR TITLE
optimize inner persistent for softmax

### PR DESCRIPTION
**Pull request by liqiangxl**
(1) use small persistent batch if has expensive ops e.g. exp in softmax
(2) use large persistent batch if vectorization factor <= 2

Results: 
(1) can be vectorized by 8: perf increased about 10% for cases with hidden size from 6K to 16K.
image
(2) can be vectorized by 2: perf increased about 20% for cases with hidden size from 10K to 16K.
image
(3) no change for cases vectorized by 4.

### CODE REVIEW

**Comment by naoyam** [comment]
As I mentioned offline, we should have a reasoning to explain why this is more efficient.

**Comment by liqiangxl** [comment]
> As I mentioned offline, we should have a reasoning to explain why this is more efficient.

Agree. Let me summarize the offline discussions here so we know why this change improves the performance.
(1) `At a hidden size of 16K, before this PR (left part), the kernel uses 256 threads, each works on 64 elements. After this PR, the kernel uses 512 threads, each works on 32 elements. In both cases, one SM can hold 2 blocks and needs 8 waves. The serial work of 32 elements is large enough to help reduce the memory access latency since they include expensive exp op. ` The revised approach also doubles active warps (both theoritical and achieved) per SM. If there is no expensive exp op, we shouldn't use this optimization since the computation cost of each thread is not large enough to hide memory access latency and the increased overhead of inter-threads communications overtakes the benefit of higher occupancy.
image

(2) Another discussion not directly releated to this PR is: the `ncu` reported kernel execution time is higher than the actual kernel execution time reported by `nsys` due to the profiling overhead.

We haven't covered the reasoning behind using a large persistent batch when the `vectorization factor` is less than or equal to 2. This idea stems from the observation that each thread's serial workload is equivalent to the `product of the vectorization factor and the persistent batch`. To maintain a similar persistent buffer/workload for each thread, the persistent batch should be increased when the vectorization factor is small. However, it shouldn't be simply defined as  `N/vectorization factor`, as this would result in a large persistent batch, leading to a substantial number of global memory read and write operations.

**Comment by liqiangxl** [comment]
> For example, try removing exp in softmax and see if the change of this PR would negatively affect the performance.

I replaced exp(x) with x*x. The performance difference is very small whether we use small batch size or large batch size.
image

I also tested layer norm which doesn't have exp. If using small batch size by changing the code to`if (true || has_expensive_op)`, the performance change is also small.
image

**Comment by naoyam** [comment]
Aren't we supposed to see lower performances?

**Comment by liqiangxl** [comment]
> Aren't we supposed to see lower performances?

Oh, let me check a differnt batch size. The current batch size I used is 32K, which is very large. SM has enough blocks to switch on and off. When I setup this PR I was using a batch size of 16x108, which should be more sensitive to occupancy ratio.

**Comment by liqiangxl** [comment]
> > Aren't we supposed to see lower performances?
> 
> Oh, let me check a differnt batch size. The current batch size I used is 32K, which is very large. SM has enough blocks to switch on and off. When I setup this PR I was using a batch size of 16x108, which should be more sensitive to occupancy ratio.

Influence is still small for layer norm.
image

For softmax without exp(x), the performance is actually still increased when using a smaller batch size.
image

So the influence of exp op is very small. The major reason is still occupancy. For layer norm the occupancy is only slightly changed (max change is from 32 to 40) but for softmax the occupancies are largely increased or even doubled in cases around 10K and 15K.

image

image

**Comment by liqiangxl** [comment]
perf was solved by project to inputs in #1408

**Pull request closed without merging**
