### PR TITLE
Support indexing for circular buffering

### PR DESCRIPTION
**Pull request by naoyam**
Circular buffering is one area that the IdModel-based indexing still doesn't work well with because the three loops generated by circular buffering are not represented in any of ID graphs. That's why this PR adds the loop-nest parameter to `getLinearIndex` since properties on circular buffering are only available through actual for-loops. While this is not ideal, I think it's more important to get a working implementation first, so here it is.

There are mainly three changes:

- In a circular buffer loop, no matter prologue, main or epilogue, [the loop index is not the one registered for the iter domain of the loop only but it's also associated with the loop stage.](https://github.com/NVIDIA/Fuser/blob/main/csrc/compute_at_map.cpp#L894-L905). In this PR, I just added a WAR to get it from `ForLoop` if necessary (`getLoopIndexOfCircularBufferLoop`)
- In the circular buffer main loop, reading the input tensor must be advanced by `num_stages - 1` (`getLoopIndexOffsetForProducerOfCircularBuffer`)
- The circular buffer tensor needs to switch buffers by adding an offset to its linear offset, which should look like `i % num_stages`, where `i` is the index of the circular buffer loop. (`getOffsetForCircularBufferTensor`)

### CODE REVIEW

**Comment by naoyam** [comment]
CC: @zasdfgbnm @rdspring1

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
With this and #2591, here's the failing tests of `nvfuser_tests`. Note that the other test files are not included.

```
[  FAILED  ] 76 tests, listed below:
[  FAILED  ] NVFuserTest.FusionVectorizeMisalignedPointwise_CUDA
[  FAILED  ] NVFuserTest.FusionVectorizeMisalignedPointwiseMergeContig_CUDA
[  FAILED  ] NVFuserTest.FusionVectorizeMisalignedPointwiseMergeSymbolicPass_CUDA
[  FAILED  ] NVFuserTest.FusionVectorizeMisalignedRFactor_CUDA
[  FAILED  ] NVFuserTest.FusionVectorizeMisalignedStride_CUDA
[  FAILED  ] NVFuserTest.FusionVectorizeMisalignedStrideFail_CUDA
[  FAILED  ] NVFuserTest.FusionSimpleCpAsync_CUDA
[  FAILED  ] NVFuserTest.FusionCpAsyncPredicate_CUDA
[  FAILED  ] NVFuserTest.FusionSimpleAmperePipeline_CUDA
[  FAILED  ] NVFuserTest.FusionCpAsyncCommitWait_CUDA
[  FAILED  ] NVFuserTest.FusionCrossEntropyGatherPattern_CUDA
[  FAILED  ] NVFuserTest.FusionSelectOpPointwise_CUDA
[  FAILED  ] NVFuserTest.FusionSelectOpReduction_CUDA
[  FAILED  ] NVFuserTest.FusionSelectOpPersistent_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelectSimple_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelect_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelect1DSch_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelect3DTv_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelect_Sum_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelectIdxTvFuseable_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelectDim1InRank2_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelectDim2InRank3_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelectDim1InRank3_CUDA
[  FAILED  ] NVFuserTest.FusionIndexSelectDim2InRank4_CUDA
[  FAILED  ] NVFuserTest.IndexSelectBroadcastIndex_CUDA
[  FAILED  ] NVFuserTest.MultipleIndexSelectIssue_CUDA
[  FAILED  ] CircularBufferingTest.CircularBufferCpAsync1
[  FAILED  ] CircularBufferingTest.CircularBufferCpAsync2
[  FAILED  ] IndexingOpTest.TorchGatherAllRankAllSelectedDim_CUDA
[  FAILED  ] IndexingOpTest.TorchGatherAddMul_CUDA
[  FAILED  ] IndexingOpTest.AddGatherSumAdd_CUDA
[  FAILED  ] IndexingOpTest.TorchGatherSumAdd_CUDA
[  FAILED  ] IndexingOpTest.TorchGatherAddMulHugeSize_CUDA
[  FAILED  ] IndexingOpTest.TorchGatherInput_CUDA
[  FAILED  ] IndexingOpTest.TorchGatherIndexTvExtentIsOne_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongBroadcastIndex_CUDA
[  FAILED  ] IndexingOpTest.GatherBroadcastInput_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorPointwise1_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorPointwise2_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorReduction1_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorReduction2_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorReduction3_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorNormalization1_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorNormalization2_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorNormalization3_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorNormalizationAndReduction1_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorNormalizationAndReduction2_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorTranspose1_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorTranspose2_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisIntermediateTensorTranspose3_CUDA
[  FAILED  ] IndexingOpTest.TakeAlongAxisCrossEntropyLoss_CUDA
[  FAILED  ] IndexingOpTest.GatherIterGoupedReduction_CUDA
[  FAILED  ] LoopRotationTest.RotateInner
[  FAILED  ] LoopRotationTest.RotateOuter
[  FAILED  ] LoopRotationTest.NonDivisibleSplit
[  FAILED  ] LoopRotationTest.CircularBuffered
[  FAILED  ] LoopRotationTest.SelectCircularBufferLoad
[  FAILED  ] LoopRotationTest.MultipleCircularBuffer
[  FAILED  ] SwizzleTest.SimpleSwizzle0
[  FAILED  ] SwizzleTest.SimpleSwizzle1
[  FAILED  ] SwizzleTest.SimpleSwizzle2
[  FAILED  ] SwizzleTest.LoopSwizzle1
[  FAILED  ] SwizzleTest.TransposeBankConflictSwizzle1
[  FAILED  ] SwizzleTest.TransposeBankConflictSwizzle2
```

Misaligned vectorization and index_select are two major limitations that I haven't worked on. I didn't expect the cp.async failures.

**Review by jacobhinkle — APPROVED** [review]
LGTM. I didn't notice any logic errors, only a couple typos.

**Pull request merged**
