### PR TITLE
Pointwise shouldn't check transpose scheduler

### PR DESCRIPTION
**Pull request by naoyam**
Removed unnecessary check. 

Codegen diff kept failing with some python tests, which was due to #3283. Otherwise, no change is detected.

### CODE REVIEW

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff

**Comment by naoyam** [comment]
!build --diff-bench

**Comment by naoyam** [comment]
!build --diff-bench

**Review by jacobhinkle — APPROVED** [review]
LGTM. We don't need this since Pointwise is ahead of Transpose in the priority queue.

**Pull request merged**
