### PR TITLE
Check if `compiled_kernel_` exists before serialization.

### PR DESCRIPTION
**Pull request by rdspring1**
If compilation fails, `compiled_kernel_` is a nullptr. During serialization, we can get a segmentation fault when dereferencing the pointer. This PR checks if `compiled_kernel_` exists before serialization.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Review by wujingyue — APPROVED** [review]

**Pull request merged**
