### PR TITLE
Use `kir::Asm` for TMA store sync

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This PR is stacked on https://github.com/NVIDIA/Fuser/pull/1207

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by naoyam — APPROVED** [review]
Just to make sure I understand the context correctly, `kir::Asm` is already used and this PR is to just clean up unused code?

**Comment by zasdfgbnm** [comment]
> and this PR is to just clean up unused code?

Looks like I've made a mistake in resolving conflicts. This PR should change `inline_ptx.cpp` as well...

**Comment by naoyam** [comment]
> > and this PR is to just clean up unused code?
> 
> Looks like I've made a mistake in resolving conflicts. This PR should change `inline_ptx.cpp` as well...

Hahaha, I thought this was an easy-to-review PR.

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
