### PR TITLE
Rename files in `tests/python`

### PR DESCRIPTION
**Pull request by Priya2698**
PR #2701  to allow creating modular test files and moves to pytest from unittest. Given these changes, we are doing the following renaming/reorganization:
 
- Merge `pytest_utils.py` and `utils.py` since we are only using `pytest` now.
- `pytest_core.py` -> `opinfo_core.py`
- `pytest_framework.py` -> `opinfo_framework.py `
- `pytest_fusion_definitions.py` -> `opinfo_fusion_definitions.py`
- `pytest_input_generators.py` -> `opinfo_input_generators.py`
- `pytest_opinfos.py` -> `opinfos.py`
- `pytest_ops.py` -> `test_ops.py`. (Allows automatic test file discovery with `pytest`)
- `pytest.md` -> `README.md` so it will displayed on github page.

Next PRs:
- ~Remove other instances of `unittest`.~ (PR #2809 merged)
- Update README with instructions on creating new tests, using serde check decorators, and the `NVFuserTest` class.
- ~Extract matmul/linear and SDPA tests from `test_python_frontend.py` into a separate test file each.~ (PR #2806 merged)

### CODE REVIEW

**Comment by Priya2698** [comment]
!build --serde

**Comment by Priya2698** [comment]
!build --serde

**Review by rdspring1 — APPROVED** [review]
LGTM

**Comment by Priya2698** [comment]
@xwang233, in the CI we will need to modify `pytest_ops.py -> test_ops.py`

**Comment by Priya2698** [comment]
!build --serde

**Comment by Priya2698** [comment]
!build --serde

**Comment by Priya2698** [comment]
!build --serde

**Comment by Priya2698** [comment]
!build --serde

**Pull request merged**
