### PR TITLE
Hoist pad predicate

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Found this issue while reading https://github.com/NVIDIA/Fuser/issues/2795

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
:+1:

**Comment by zasdfgbnm** [comment]
@jjsjann123 Could you check if this help with your perf? My naive benchmark shows a small improvement:

Before:
```C++
 Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)                                                  Name                                                
 --------  ---------------  ---------  --------  --------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
     70.3            18784          1   18784.0   18784.0     18784     18784          0.0  <unnamed>::nvfuser_pointwise_f0_c1_r0_g6(<unnamed>::Tensor<<unnamed>::__bfloat, (int)4, (int)4>, <u…
     29.7             7935          3    2645.0    1600.0      1343      4992       2036.6  void at::native::<unnamed>::distribution_elementwise_grid_stride_kernel<float, (int)4, void at::nat…
```

After:
```C++
 Time (%)  Total Time (ns)  Instances  Avg (ns)  Med (ns)  Min (ns)  Max (ns)  StdDev (ns)                                                  Name                                                
 --------  ---------------  ---------  --------  --------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
     67.3            16608          1   16608.0   16608.0     16608     16608          0.0  <unnamed>::nvfuser_pointwise_f0_c1_r0_g6(<unnamed>::Tensor<<unnamed>::__bfloat, (int)4, (int)4>, <u…
```

**Comment by zasdfgbnm** [comment]
Output kernel with this PR:

```CUDA
__global__ void nvfuser_pointwise_f0_c1_r0_g6(Tensor<__bfloat, 4, 4> T10, Tensor<__bfloat, 4, 4> T8, Tensor<__bfloat, 2, 2> T22, Tensor<__bfloat, 2, 2> T14, Tensor<__bfloat, 2, 2> T18, Tensor<__bfloat, 4, 4> T12, Tensor<__bfloat, 2, 2> T26, Tensor<__bfloat, 4, 4> T4, Tensor<__bfloat, 4, 4> T6, nvfuser_index_t i0, nvfuser_index_t i1, nvfuser_index_t i2, Tensor<__bfloat, 4, 4> T48) {
  NVFUSER_DEFINE_MAGIC_ZERO;
  nvfuser_index_t i3;
  i3 = 8 * ((nvfuser_index_t)threadIdx.x);
  nvfuser_index_t i4;
  i4 = (8 * ((nvfuser_index_t)blockDim.x)) * ((nvfuser_index_t)blockIdx.x);
  nvfuser_index_t i5;
  i5 = i3 + i4;
  nvfuser_index_t i6;
  i6 = 28 + T26.logical_size[1LL];
  nvfuser_index_t i7;
  i7 = ((nvfuser_index_t)blockIdx.y) / T10.logical_size[1LL];
  nvfuser_index_t i8;
  i8 = ((nvfuser_index_t)blockIdx.y) % T10.logical_size[1LL];
  nvfuser_index_t i9;
  i9 = (-4 + (T6.alloc_stride[0LL] * i7)) + (T6.alloc_stride[1LL] * i8);
  nvfuser_index_t i10;
  i10 = 28 + T6.logical_size[3LL];
  nvfuser_index_t i11;
  i11 = 28 + T14.logical_size[1LL];
  nvfuser_index_t i12;
  i12 = (T10.alloc_stride[0LL] * i7) + (T10.alloc_stride[1LL] * i8);
  nvfuser_index_t i13;
  i13 = 28 + T10.logical_size[3LL];
  nvfuser_index_t i14;
  i14 = (T8.alloc_stride[0LL] * i7) + (T8.alloc_stride[1LL] * i8);
  nvfuser_index_t i15;
  i15 = 28 + T8.logical_size[3LL];
  nvfuser_index_t i16;
  i16 = 28 + T22.logical_size[1LL];
  nvfuser_index_t i17;
  i17 = (-8 + (T4.alloc_stride[0LL] * i7)) + (T4.alloc_stride[1LL] * i8);
  nvfuser_index_t i18;
  i18 = 8 + T4.logical_size[3LL];
  nvfuser_index_t i19;
  i19 = 28 + T18.logical_size[1LL];
  nvfuser_index_t i20;
  i20 = (-4 + (T12.alloc_stride[0LL] * i7)) + (T12.alloc_stride[1LL] * i8);
  nvfuser_index_t i21;
  i21 = 28 + T12.logical_size[3LL];
  nvfuser_index_t i22;
  i22 = (i3 + (32768 * ((nvfuser_index_t)blockIdx.y))) + i4;
  nvfuser_index_t i23;
  i23 = 24 * T10.logical_size[2LL];
  nvfuser_index_t i24;
  i24 = ((max(4, (min(i0, 8)))) * T10.logical_size[2LL]) + i23;
  bool b25;
  b25 = i5 < i24;
  nvfuser_index_t i26;
  i26 = 28 * T10.logical_size[2LL];
  bool b27;
  b27 = i5 < (i26 + (T10.logical_size[2LL] * T6.logical_size[3LL]));
  bool b28;
  b28 = i5 < (i26 + (T10.logical_size[2LL] * T14.logical_size[1LL]));
  bool b29;
  b29 = i5 < ((T10.logical_size[2LL] * T10.logical_size[3LL]) + i26);
  bool b30;
  b30 = i5 < (((max(4, (min((max(0LL, (min(i1, 8)))), 8)))) * T10.logical_size[2LL]) + i23);
  bool b31;
  b31 = i5 < (i26 + (T10.logical_size[2LL] * T22.logical_size[1LL]));
  bool b32;
  b32 = i5 < ((max(8, (min(i1, 32)))) * T10.logical_size[2LL]);
  bool b33;
  b33 = i5 < (((max(4, (min(i2, 8)))) * T10.logical_size[2LL]) + i23);
  if ((((i3 + 7) + i4) < i24)) {
    Array<__bfloat, 8, 8> T54;
    #pragma unroll
    for(nvfuser_index_t i34 = 0; i34 < 8; ++i34) {
      nvfuser_index_t i35;
      i35 = i5 + (i34 + nvfuser_zero);
      __bfloat T27[1];
      T27[0] = 0;
      T27[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T26.logical_size[1LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T26.logical_size[1LL] + 4) + 24)) - 4) < T26.logical_size[1LL])) ? T26[((-4 + (T26.alloc_stride[0LL] * (i35 / i6))) + (i35 % i6))] : 0.0000e+00;
      __bfloat T28[1];
      T28[0]
         = T27[0];
      __bfloat T52[1];
      T52[0]
         = T28[0];
      __bfloat T7[1];
      T7[0] = 0;
      T7[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T6.logical_size[3LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T6.logical_size[3LL] + 4) + 24)) - 4) < T6.logical_size[3LL])) ? T6[((i9 + (T6.alloc_stride[2LL] * (i35 / i10))) + (i35 % i10))] : 0.0000e+00;
      float T38[1];
      T38[0]
         = __bfloat2float(T7[0]);
      float T39[1];
      T39[0]
         = __bfloat2float(T52[0]);
      float T40[1];
      T40[0]
        = T38[0]
        * T39[0];
      __bfloat T15[1];
      T15[0] = 0;
      T15[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T14.logical_size[1LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T14.logical_size[1LL] + 28)) - 0) < T14.logical_size[1LL])) ? T14[((T14.alloc_stride[0LL] * (i35 / i11)) + (i35 % i11))] : 0.0000e+00;
      __bfloat T16[1];
      T16[0]
         = T15[0];
      __bfloat T51[1];
      T51[0]
         = T16[0];
      __bfloat T11[1];
      T11[0] = 0;
      T11[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T10.logical_size[3LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T10.logical_size[3LL] + 28)) - 0) < T10.logical_size[3LL])) ? T10[((i12 + (T10.alloc_stride[2LL] * (i35 / i13))) + (i35 % i13))] : 0.0000e+00;
      float T35[1];
      T35[0]
         = __bfloat2float(T11[0]);
      float T34[1];
      T34[0]
         = __bfloat2float(T51[0]);
      float T36[1];
      T36[0]
        = T34[0]
        * T35[0];
      __bfloat T9[1];
      T9[0] = 0;
      T9[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T8.logical_size[3LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T8.logical_size[3LL] + 28)) - 0) < T8.logical_size[3LL])) ? T8[((i14 + (T8.alloc_stride[2LL] * (i35 / i15))) + (i35 % i15))] : 0.0000e+00;
      float T30[1];
      T30[0]
         = __bfloat2float(T9[0]);
      float T31[1];
      T31[0]
         = -T30[0];
      __bfloat T23[1];
      T23[0] = 0;
      T23[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T22.logical_size[1LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T22.logical_size[1LL] + 28)) - 0) < T22.logical_size[1LL])) ? T22[((T22.alloc_stride[0LL] * (i35 / i16)) + (i35 % i16))] : 0.0000e+00;
      __bfloat T24[1];
      T24[0]
         = T23[0];
      __bfloat T50[1];
      T50[0]
         = T24[0];
      float T32[1];
      T32[0]
         = __bfloat2float(T50[0]);
      float T33[1];
      T33[0]
        = T31[0]
        * T32[0];
      __bfloat T5[1];
      T5[0] = 0;
      T5[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T4.logical_size[3LL] + 8)) - 8) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T4.logical_size[3LL] + 8)) - 8) < T4.logical_size[3LL])) ? T4[((i17 + (T4.alloc_stride[2LL] * (i35 / i18))) + (i35 % i18))] : 0.0000e+00;
      float T46[1];
      T46[0]
         = __bfloat2float(T5[0]);
      __bfloat T19[1];
      T19[0] = 0;
      T19[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T18.logical_size[1LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T18.logical_size[1LL] + 4) + 24)) - 4) < T18.logical_size[1LL])) ? T18[((-4 + (T18.alloc_stride[0LL] * (i35 / i19))) + (i35 % i19))] : 0.0000e+00;
      __bfloat T20[1];
      T20[0]
         = T19[0];
      __bfloat T53[1];
      T53[0]
         = T20[0];
      __bfloat T13[1];
      T13[0] = 0;
      T13[0]
         = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T12.logical_size[3LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T12.logical_size[3LL] + 4) + 24)) - 4) < T12.logical_size[3LL])) ? T12[((i20 + (T12.alloc_stride[2LL] * (i35 / i21))) + (i35 % i21))] : 0.0000e+00;
      float T42[1];
      T42[0]
         = __bfloat2float(T13[0]);
      float T41[1];
      T41[0]
         = __bfloat2float(T53[0]);
      float T43[1];
      T43[0]
        = T41[0]
        * T42[0];
      float T44[1];
      T44[0]
        = T40[0]
        + T43[0];
      float T37[1];
      T37[0]
        = T33[0]
        + T36[0];
      float T45[1];
      T45[0]
        = T37[0]
        + T44[0];
      float T47[1];
      T47[0]
        = T45[0]
        + T46[0];
      T54[i34]
         = __float2bfloat(T47[0]);
    }
    NVFUSER_UPDATE_MAGIC_ZERO;
    loadLocalToGlobal<__bfloat, /*vec_size=*/8, /*is_volatile=*/false>( &T48[i22], &T54[0]);
  } else {
    Array<__bfloat, 8, 8> T54;
    #pragma unroll
    for(nvfuser_index_t i34 = 0; i34 < 8; ++i34) {
      nvfuser_index_t i36;
      i36 = i5 + (i34 + nvfuser_zero);
      __bfloat T27[1];
      T27[0] = 0;
      if (b25) {
        T27[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T26.logical_size[1LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T26.logical_size[1LL] + 4) + 24)) - 4) < T26.logical_size[1LL])) ? T26[((-4 + (T26.alloc_stride[0LL] * (i36 / i6))) + (i36 % i6))] : 0.0000e+00;
      }
      __bfloat T28[1];
      T28[0]
         = T27[0];
      __bfloat T52[1];
      T52[0]
         = T28[0];
      __bfloat T7[1];
      T7[0] = 0;
      if (b27) {
        T7[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T6.logical_size[3LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T6.logical_size[3LL] + 4) + 24)) - 4) < T6.logical_size[3LL])) ? T6[((i9 + (T6.alloc_stride[2LL] * (i36 / i10))) + (i36 % i10))] : 0.0000e+00;
      }
      float T38[1];
      T38[0]
         = __bfloat2float(T7[0]);
      float T39[1];
      T39[0]
         = __bfloat2float(T52[0]);
      float T40[1];
      T40[0]
        = T38[0]
        * T39[0];
      __bfloat T15[1];
      T15[0] = 0;
      if (b28) {
        T15[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T14.logical_size[1LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T14.logical_size[1LL] + 28)) - 0) < T14.logical_size[1LL])) ? T14[((T14.alloc_stride[0LL] * (i36 / i11)) + (i36 % i11))] : 0.0000e+00;
      }
      __bfloat T16[1];
      T16[0]
         = T15[0];
      __bfloat T51[1];
      T51[0]
         = T16[0];
      __bfloat T11[1];
      T11[0] = 0;
      if (b29) {
        T11[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T10.logical_size[3LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T10.logical_size[3LL] + 28)) - 0) < T10.logical_size[3LL])) ? T10[((i12 + (T10.alloc_stride[2LL] * (i36 / i13))) + (i36 % i13))] : 0.0000e+00;
      }
      float T35[1];
      T35[0]
         = __bfloat2float(T11[0]);
      float T34[1];
      T34[0]
         = __bfloat2float(T51[0]);
      float T36[1];
      T36[0]
        = T34[0]
        * T35[0];
      __bfloat T9[1];
      T9[0] = 0;
      if (b30) {
        T9[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T8.logical_size[3LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T8.logical_size[3LL] + 28)) - 0) < T8.logical_size[3LL])) ? T8[((i14 + (T8.alloc_stride[2LL] * (i36 / i15))) + (i36 % i15))] : 0.0000e+00;
      }
      float T30[1];
      T30[0]
         = __bfloat2float(T9[0]);
      float T31[1];
      T31[0]
         = -T30[0];
      __bfloat T23[1];
      T23[0] = 0;
      if (b31) {
        T23[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T22.logical_size[1LL] + 28)) - 0) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T22.logical_size[1LL] + 28)) - 0) < T22.logical_size[1LL])) ? T22[((T22.alloc_stride[0LL] * (i36 / i16)) + (i36 % i16))] : 0.0000e+00;
      }
      __bfloat T24[1];
      T24[0]
         = T23[0];
      __bfloat T50[1];
      T50[0]
         = T24[0];
      float T32[1];
      T32[0]
         = __bfloat2float(T50[0]);
      float T33[1];
      T33[0]
        = T31[0]
        * T32[0];
      __bfloat T5[1];
      T5[0] = 0;
      if (b32) {
        T5[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T4.logical_size[3LL] + 8)) - 8) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % (T4.logical_size[3LL] + 8)) - 8) < T4.logical_size[3LL])) ? T4[((i17 + (T4.alloc_stride[2LL] * (i36 / i18))) + (i36 % i18))] : 0.0000e+00;
      }
      float T46[1];
      T46[0]
         = __bfloat2float(T5[0]);
      __bfloat T19[1];
      T19[0] = 0;
      if (b33) {
        T19[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T18.logical_size[1LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T18.logical_size[1LL] + 4) + 24)) - 4) < T18.logical_size[1LL])) ? T18[((-4 + (T18.alloc_stride[0LL] * (i36 / i19))) + (i36 % i19))] : 0.0000e+00;
      }
      __bfloat T20[1];
      T20[0]
         = T19[0];
      __bfloat T53[1];
      T53[0]
         = T20[0];
      __bfloat T13[1];
      T13[0] = 0;
      if (b30) {
        T13[0]
           = ((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T12.logical_size[3LL] + 4) + 24)) - 4) >= 0) && (((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 8) + (i34 + nvfuser_zero)) % ((T12.logical_size[3LL] + 4) + 24)) - 4) < T12.logical_size[3LL])) ? T12[((i20 + (T12.alloc_stride[2LL] * (i36 / i21))) + (i36 % i21))] : 0.0000e+00;
      }
      float T42[1];
      T42[0]
         = __bfloat2float(T13[0]);
      float T41[1];
      T41[0]
         = __bfloat2float(T53[0]);
      float T43[1];
      T43[0]
        = T41[0]
        * T42[0];
      float T44[1];
      T44[0]
        = T40[0]
        + T43[0];
      float T37[1];
      T37[0]
        = T33[0]
        + T36[0];
      float T45[1];
      T45[0]
        = T37[0]
        + T44[0];
      float T47[1];
      T47[0]
        = T45[0]
        + T46[0];
      T54[i34]
         = __float2bfloat(T47[0]);
    }
    NVFUSER_UPDATE_MAGIC_ZERO;
    if ((i5 < 32768)) {
      loadLocalToGlobal<__bfloat, /*vec_size=*/8, /*is_volatile=*/false>( &T48[i22], &T54[0]);
    }
  }
}
```

**Review by jacobhinkle — APPROVED** [review]

**Pull request merged**
