### PR TITLE
Fallback to stop in ForLoop::simplifiedStop

### PR DESCRIPTION
**Pull request by rdspring1**
Simple for-loops are used to initialize and invalidate mbarriers. The indexing pass is not used for these operations, so the `simplified_stop_` value is not initialized during lowering. This PR uses the original stop value if `simplified_stop_` is not initialized during lowering.

```cpp
  # mbarrier initialization
  if (hopper::elect_sync()) {
    #pragma unroll
    for(nvfuser_index_t i10 = 0; i10 < number_of_stages; ++i10) {
      mbarrier::init(toSmem((&T3[i10])), 1U);
    }
  }

  // remaining kernel

  // mbarrier invalidation
  if (hopper::elect_sync()) {
    #pragma unroll
    for(nvfuser_index_t i19 = 0; i19 < number_of_stages; ++i19) {
      mbarrier::inval(toSmem((&T3[i19])));
    }
  }
```

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]
Should we do something like below?
```C++
GpuLower::current()->commonScalarMap().initialized() ? GpuLower::current()->commonScalarMap().hoistScalar(stop(), {}) : stop();
```

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
Since I am calling `simplifiedStop()` after lowering, I changed your suggestion to:
`GpuLower::hasCurrent() ? GpuLower::current()->commonScalarMap().hoistScalar(stop(), {}) : stop();`

**Pull request merged**
