### PR TITLE
patch setuptools

### PR DESCRIPTION
**Pull request by jjsjann123**
1. adding --no-ninja option to use make instead;
2. adding BSD-3-Clause as license for the wheel package;
3. skip `nvfuser-patch` for bdist_wheel build, since we are not installation the package entry_points are not available yet.

### CODE REVIEW

**Review by zasdfgbnm — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
Instead of providing a non-ninja version, should we instead add `ninja` into https://github.com/NVIDIA/Fuser/blob/main/requirements.txt?

I just want to hear your opinion. I don't have any preference on this.

**Comment by jjsjann123** [comment]
> Instead of providing a non-ninja version, should we instead add `ninja` into https://github.com/NVIDIA/Fuser/blob/main/requirements.txt?
> 
> I just want to hear your opinion. I don't have any preference on this.

I'm perfectly ok with adding ninja as requirements.txt. That doesn't contradict to have an option to switch to make?!
let me update that.

**Comment by zasdfgbnm** [comment]
> > Instead of providing a non-ninja version, should we instead add `ninja` into https://github.com/NVIDIA/Fuser/blob/main/requirements.txt?
> > I just want to hear your opinion. I don't have any preference on this.
> 
> I'm perfectly ok with adding ninja as requirements.txt. That doesn't contradict to have an option to switch to make?! let me update that.

Yeah, there is no contradiction, and I am happy to have more options on which builder to use.

I was using the word "instead of XXX" mostly because I was comparing the following two approaches:

1. Change the installation guide to: "if you don't have ninja on your system, use `--no-ninja`"

vs

2. Add ninja to `requirements.txt` and keep the installation guide as-is.

And I thought 2 is less painful to follow. I meant to say "instead of 1, why not 2?" but I didn't express myself clearly.

**Comment by jjsjann123** [comment]
> And I thought 2 is less painful to follow. I meant to say "instead of 1, why not 2?" but I didn't express myself clearly.

Got ya. That sounds good to me. I'll move along with that then

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
CI looks good. I'm rebasing and merging this one after linter finishes.

**Pull request merged**
