### PR TITLE
Cleanup of circular buffering pass: add `onlyOneSerialForLoopOnStack`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Pulled out from https://github.com/NVIDIA/Fuser/pull/3202

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by rdspring1 — APPROVED** [review]
LGTM

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
