### PR TITLE
Enforce 128B alignment for TMA shared memory allocation.

### PR DESCRIPTION
**Pull request by rdspring1**
From https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#table-alignment-multi-dim-tma, the shared memory address must be 128B aligned.

This PR enforces this alignment for all TMA shared memory allocations to avoid `CUDA_ERROR_MISALIGNED_ADDRESS` errors.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]
This change looks good to me. But before you merge, could you move your changes in `csrc/device_lower/pass/allocation.cpp`, as well as `initializeMbarrier` and `invalidateMbarrier`, from #2833 to this PR? Because these are the things that makes TMA buffer no longer aligned well. I checked them in #2833 and they look good to me as well. Also, a nit pick: Should we move `initializeMbarrier` and `invalidateMbarrier` to `allocation.cpp` or as an `ir_utils`?

**Comment by rdspring1** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]

**Comment by rdspring1** [comment]
I moved `initializeMbarrier` and `invalidateMbarrier` to `allocation.cpp`

**Pull request merged**
