### PR TITLE
Add `--no-allow-shlib-undefined`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Another recommendation from @tfogal

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
looks like BUILD passed. Let's merge it to test with wheel build

unless @xwang233 wants to clear pip wheel before merging

**Review by xwang233 — APPROVED** [review]
The manylinux wheel build also passed in CI, so I think it should be fine.

**Comment by naoyam** [comment]
I'm having a problem with this option, maybe because I'm using lld:

```
ld.lld: error: /opt/conda/pytorch/lib/python3.11/site-packages/torch/lib/libc10.so: undefined reference to pthread_create [--no-allow-shlib-undefined]
ld.lld: error: /opt/conda/pytorch/lib/python3.11/site-packages/torch/lib/libc10.so: undefined reference to pthread_setname_np [--no-allow-shlib-undefined]
```

Looks like `libc10` isn't linked with `-lpthread`. Is this a problem with how I built PyTorch?

**Pull request merged**
