### PR TITLE
Move axioms to IR container

### PR DESCRIPTION
**Pull request by zasdfgbnm**
@jacobhinkle discovered that currently, a significant portion of our lowering time is spent at `getAxioms`, this PR removes this time by moving axioms to IR containers just like one value/zero value, etc.

cc: @naoyam

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM.

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
