### PR TITLE
removing obsolete code

### LINKED ISSUE #2910: Bad error message from illegal alias
When user specifies alias on intermediate / output tensors as aliasing source, our error message is confusing.

```py
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T1 = fd.ops.relu(T0)
    T2 = fd.ops.sin(T0)
    fd.add_output(T2, alias_input=T1)
    fd.add_output(T1)

with FusionDefinition() as fd:
    nvfuser_fusion_id1(fd)

t0 = torch.randn((20,), dtype=torch.float, device='cuda:0').as_strided((10, 2), (2, 1))

inputs = [t0.clone()]

print(fd.execute(inputs)[0])
```

gives:
```py
Traceback (most recent call last):
  File "/volume/nvfuser_repro.py", line 11, in <module>
    with FusionDefinition() as fd:
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 62, in __exit__
    self._finalize_definition()
RuntimeError: input_uop->getUnaryOpType() == UnaryOpType::Cast INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/fusion.cpp":819, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. expected aliased input to be output of cast op
Exception raised from aliasOutputToInput at /opt/pytorch/nvfuser/csrc/fusion.cpp:819 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f768392ec47 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7f7683c917b3 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: nvfuser::Fusion::aliasOutputToInput(nvfuser::Val*, nvfuser::Val*, nvfuser::AllocationType) + 0x5ed (0x7f7683d1fe6d in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x8cd86c (0x7f76840cc86c in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: nvfuser::python_frontend::FusionDefinition::finalizeDefinition() + 0x113 (0x7f76840c6703 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x215fe7 (0x7f7683a14fe7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x2b9840 (0x7f7683ab8840 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #22: <unknown function> + 0x29d90 (0x7f78c9a52d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #23: __libc_start_main + 0x80 (0x7f78c9a52e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

I think the error message comes from deprecated code handling type promotion for TorchScript. I'll clean it up.

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #2910

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build --pybench

**Review by csarofeen — APPROVED** [review]
LGTM

**Comment by jjsjann123** [comment]
Leaving this one as draft since there seems to be real failure. I'll start looking at failing cases.

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
errr. looks like this test is actually defining a wrong fusion: https://github.com/NVIDIA/Fuser/blob/7086d52e16aef80509ee710c40bfddb14adab90c/nvfuser/contrib/nn/normalization.py#L405-L409

**Comment by jjsjann123** [comment]
!test

**Pull request merged**
