### PR TITLE
Avoid validation error

### PR DESCRIPTION
**Pull request by naoyam**
~~Fix the validation issue of #374~~

The validation error still persists.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Unfortunately I pulled locally and this doesn't help. But on the other hand, I do think it make sense to manual seed. Should we do this inside https://github.com/NVIDIA/Fuser/blob/dd25df0c2127fc5adfd86352b29ccaa4043efb9b/test/utils.h#L387 instead?

**Comment by naoyam** [comment]
That's a good idea. Will update the tests.

Can you try comparing the results with a reference result in double precision?

**Comment by naoyam** [comment]
> Unfortunately I pulled locally and this doesn't help. But on the other hand, I do think it make sense to manual seed. Should we do this inside
> 
> https://github.com/NVIDIA/Fuser/blob/dd25df0c2127fc5adfd86352b29ccaa4043efb9b/test/utils.h#L387
> 
> instead?

Done

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
!build

**Comment by zasdfgbnm** [comment]
> That's a good idea. Will update the tests.
> 
> Can you try comparing the results with a reference result in double precision?

Unfortunately using double increases the validation error...

**Review by zasdfgbnm — APPROVED** [review]
Thanks for the cleanup!

**Comment by naoyam** [comment]
> Unfortunately using double increases the validation error...

Hmm, did we change anything recently that could affect the failing test? I don't remember anything particular.

**Comment by zasdfgbnm** [comment]
> > Unfortunately using double increases the validation error...
> 
> Hmm, did we change anything recently that could affect the failing test? I don't remember anything particular.

I am not aware of anything either. I am not even sure if it is due to a change in our codebase or in eager mode...

**Comment by naoyam** [comment]
Not ideal, but can you also try if reducing the problem size could avoid the error?

**Comment by zasdfgbnm** [comment]
> NVFuserTest

Does it make sense to do so? I think the test should honestly reproduce the exact same shape as reported from user code, because different shape might result different heuristics, therefore potentially hiding the problem.

**Comment by naoyam** [comment]
Do you remember what the original issue was about? Can we reduce the size without impacting the conditions to trigger the original issue?

I'm going to merge this PR anyway although it does not fix the issue.

**Comment by zasdfgbnm** [comment]
> Do you remember what the original issue was about? Can we reduce the size without impacting the conditions to trigger the original issue?
> 
> I'm going to merge this PR anyway although it does not fix the issue.

I think it is the issue where `TransformPropagator` fails to find a path that has all the information of all IDs. Yes, it is possible to do some debugging on changing the sizes while checking if the generated schedule changes, but I don't think it worth the effort to do such debugging, because it is not failing on our CI. If in the future it do fail on CI, I think just bumping up the `tol` is the solution because it takes least amount of effort.

**Pull request merged**
