### PR TITLE
Add DeviceMesh::createForNumDevices, a convenient helper.

### PR DESCRIPTION
**Pull request by wujingyue**

### CODE REVIEW

**Comment by wujingyue** [comment]
!build --dist

**Comment by wujingyue** [comment]
!build

**Review by cowanmeg — APPROVED** [review]
Thanks @samnordmann for pointing out the duplication with https://github.com/NVIDIA/Fuser/pull/1987#discussion_r1565865902 
I can update my PR with this changes once this one gets merged.

**Comment by wujingyue** [comment]
Thanks both! @cowanmeg, I'm happy to rebase #1987 on your behalf as long as you give me access there.

**Comment by cowanmeg** [comment]
> Thanks both! @cowanmeg, I'm happy to rebase #1987 on your behalf as long as you give me access there.

It should be real quick for me!

**Pull request merged**
