### PR TITLE
Remove `fusion_cache_generated.h`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Do we still care about submodule build?

### CODE REVIEW

**Comment by jjsjann123** [comment]
good point. Wondering if there's still need for this in our CI? There's also pytorch container, which I'm not sure if still uses submodule build? (we should change that if it's the case)
cc'ing @xwang233

**Review by jjsjann123 — APPROVED** [review]
stamping~~~

**Comment by zasdfgbnm** [comment]
!build

**Comment by xwang233** [comment]
I think we don't have submodule build anywhere internally now.

**Comment by jacobhinkle** [comment]
> Looks like clangtidy is not happy about the removing of this file. `NOLINTNEXTLINE` doesn't seem to fix.
> 
> ```
> >>> Lint for csrc/executor_params.h:
> 
>   Error (CLANGTIDY) [clang-diagnostic-error]
>     'serde/fusion_cache_generated.h' file not found
> 
>           7  |// clang-format on
>           8  |#pragma once
>           9  |#include <exceptions.h>
>     >>>  10  |#include <serde/fusion_cache_generated.h>
>          11  |#include <type.h>
>          12  |
>          13  |#include <optional>
> ```

I think we need to do this in the lintrunner CI job to generate this file: `python setup.py build --cmake-only && ninja -C build build_flatbuffer_config`

**Pull request merged**
