### PR TITLE
Cleanup: query compile_to_sass the knob less often.

### PR DESCRIPTION
**Pull request by wujingyue**

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
@xwang233 I don't quite understand the `jit_codegen_diff` errors: https://github.com/NVIDIA/Fuser/actions/runs/6155114257/job/16701525649. 
1. The diff seems to be artifact of 4e264e not this PR. 
2. Even if it were due to this PR, why is diff considered bad? There must be plenty of PRs change how codegen behaves.

**Comment by naoyam** [comment]
> @xwang233 I don't quite understand the `jit_codegen_diff` errors: https://github.com/NVIDIA/Fuser/actions/runs/6155114257/job/16701525649.
> 
> 1. The diff seems to be artifact of [4e264ee](https://github.com/NVIDIA/Fuser/commit/4e264ee48461d375d6aa3476d1054374e69539bf) not this PR.
> 2. Even if it were due to this PR, why is diff considered bad? There must be plenty of PRs change how codegen behaves.

The diff check is just meant to be informational as it's difficult to flag diffs as true or false errors automatically.

**Review by naoyam — APPROVED** [review]
LGTM

**Comment by naoyam** [comment]
> The diff seems to be artifact of [4e264ee](https://github.com/NVIDIA/Fuser/commit/4e264ee48461d375d6aa3476d1054374e69539bf) not this PR.

Not sure why diffs by past changes can show up here. @xwang233, any idea?

**Comment by xwang233** [comment]
>The diff seems to be artifact of [4e264ee](https://github.com/NVIDIA/Fuser/commit/4e264ee48461d375d6aa3476d1054374e69539bf) not this PR.

Where did you find this? I think the log suggested the diff were from

```
## __tmp_kernel1.cu
{
  "225a397": "python_tests/test_schedule_ops.py::TestScheduleOps::test_merge_op",
  "90e1004": "python_tests/test_schedule_ops.py::TestScheduleOps::test_merge_op"
}
```
225a397  90e1004

**Comment by wujingyue** [comment]
> > The diff seems to be artifact of [4e264ee](https://github.com/NVIDIA/Fuser/commit/4e264ee48461d375d6aa3476d1054374e69539bf) not this PR.
> 
> Where did you find this? 

image => Details of nvfuser-ci/jit_codegen_diff_2/10 => upload log => log.

**Pull request merged**
