### PR TITLE
Pip wheel build patch

### PR DESCRIPTION
**Pull request by jjsjann123**
1. Added `-wheel-name` option on setuptools to allow custom package name
2. changed version separator `+` to `.` to be pypi compatible

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
> is this for us to have wheels named correctly for each released pytorch including nightly?

somewhat yes. We don't really care much about which upstream code base it is, since we are releasing pip wheel mostly for our python APIs. So as long as nvprim is using the right API, it should work...
We do need to distinguish which cuda TK that we build against. so there's going to be `nvfuser-cu117` `nvfuser-cu118` e.t.c.

> Since PyTorch 2.0.1 is available nowm, we're building nvfuser wheels for stable pytorch with cuda11.7 and cuda11.8, and nightly pytorch with cuda11.8 and cuda12.1?

I don't think 2.0.1 would work. There's API change on our side that will error out on 2.0 release. But once 2.1 is out, we should be compatible with that and nightly as well. :crossed_fingers:

**Review by crcrpar — APPROVED** [review]

**Comment by xwang233** [comment]
!build

**Comment by jjsjann123** [comment]
CI looks green. I'll update the branch and merge it after linter.

**Pull request merged**
