### PR TITLE
Link `libnvfuser_codegen.so` with `-ldl`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
as suggested by @tfogal

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
well since Tom wanted it this way.

**Comment by tfogal** [comment]
We should then be able to remove it from the _test and _bench binaries, FWIW. Not a big deal.

**Comment by zasdfgbnm** [comment]
> We should then be able to remove it from the _test and _bench binaries, FWIW. Not a big deal.

We are not manually adding `-ldl` to test and bench. cmake added it magically and I have no control of.

**Comment by tfogal** [comment]
Ahhh, yeah sorry for the noise; I can see that now that I actually look at the CMake. Mea culpa!

**Pull request merged**
