### PR TITLE
Guarding file with macro

### PR DESCRIPTION
**Pull request by mmigdal-nv**
Allows to build with `USE_DISTRIBUTED=OFF`.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Comment by mmigdal-nv** [comment]
!build

**Comment by samnordmann** [comment]
Thanks for the patch. Do have a log of the build error ?

**Comment by samnordmann** [comment]
Ok I understand the error, it is because the header multidevice/executor.h is guarded by USE_DISTRIBUTED... which is a mistake

I think that a better solution would be to revert this patch but also remove the `USE_DISTRIBUTED` guards in multidevice/executor.h
The only actual depency with c10d is inside multidevice/communicator.(h|cpp).

Let me know what you think.

**Pull request merged**
