### PR TITLE
Always use scheduleMultipleMatmuls

### PR DESCRIPTION
**Pull request by jacobhinkle**
This removes the old matmul scheduler and switches to only using `scheduleMultipleMatmuls` instead. The tests for compatibility with the old scheduler are removed.

I have left the `NVFUSER_ENABLE=fuse_multiple_matmuls` option alive so that we can opt into accepting multiple matmuls in a fusion segment for now.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
Based on the failure in `test_multidevice`, I need t address the differences with DIDx scheduling before merging this PR. I will do that and add a test to `test_multi_matmul_scheduler.cpp` in a separate PR.

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Review by zasdfgbnm — APPROVED** [review]

**Comment by jacobhinkle** [comment]
!build

**Pull request merged**
