### PR TITLE
Replace TORCH_CHECK and TORCH_INTERNAL_ASSERT Macros

### LINKED ISSUE #668: Replace `TORCH_CHECK` and `TORCH_INTERNAL_ASSERT` Macros
`TORCH_INTERNAL_ASSERT` asks the user to report errors to Pytorch which no longer makes sense.  Additionally, it would be nice if the macros automatically gave a function signature and line number in a file so the user can find the error faster.

One example where that would be nice is in `arith.cpp` for the `size()` function where the user manually adds the `__FUNCTION__` macro.

```
Val* size(TensorView* inp, int64_t dim) {
  auto iter_domains = TensorDomain::noReductions(inp->getMaybeRFactorDomain());
  auto idx = dim;
  if (idx < 0) {
    idx = static_cast<int64_t>(iter_domains.size()) + idx;
  }
  TORCH_CHECK(
      (idx >= 0) && (static_cast<size_t>(idx) < iter_domains.size()),
      __FUNCTION__,
      ": The dimension requested is beyond the bounds of the shape of the indexed tensor!",
      " Tensor Dims: ",
      iter_domains.size(),
      " Dim: ",
      dim);
  return iter_domains.at(idx)->getMaybeExpandedExtent();
}
```

### PR DESCRIPTION
**Pull request by Priya2698**
The macros `TORCH_CHECK` and `TORCH_INTERNAL_ASSERT` are replaced by NVFuser specific assert macros `NVF_CHECK` and `NVF_ERROR` respectively. 

This PR resolves #668.

### CODE REVIEW

**Comment by Priya2698** [comment]
!build

**Comment by jjsjann123** [comment]
linking #811. This PR should go after that and this one should be a strict mechanical string replacement + a simple include.

**Comment by jjsjann123** [comment]
Let me know when this PR is rebased~~ I'm hoping this is a simple stamp and go since it's only string replacement

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
clang-tidy is very slow.... although we are touching lots of files...

**Review by jjsjann123 — APPROVED** [review]
Did a quick diff to verify it's just mechanical changes. (string replacement + formatting)

stamping it so I can merge it when CI passed.

**Pull request merged**
