### PR TITLE
Replacing one flavor of `IrBuilder::create` to `createInContainer`.

### PR DESCRIPTION
**Pull request by wujingyue**
As a follow-up to https://github.com/NVIDIA/Fuser/pull/2312#discussion_r1625015218.

Currently, the two flavors of `IrBuilder::create` both accept variadic template arguments and therefore require the caller to type perfectly.

### CODE REVIEW

**Review by samnordmann — APPROVED** [review]
Thanks!

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM

**Comment by wujingyue** [comment]
!build

**Pull request merged**
