### PR TITLE
Don't predicate trivial splits

### PR DESCRIPTION
**Pull request by jacobhinkle**
This small change just avoids adding predicates when an `IterDomain` is split by a constant factor of 1. The predicate is not needed in this case since 1 evenly divides any extent. It also moves a repeated independent check outside a loop.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Review by zasdfgbnm — APPROVED** [review]

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
@xwang233 heads up that the CI died at the `dnf` step of the docker build. See https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/73067209

**Comment by xwang233** [comment]
yeah, that step is always flaky, I restarted the job

**Pull request merged**
