### PR TITLE
[MatMul] Prolog build out, adding automatic swizzle generator for a few tile sizes

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This PR tries to build out matmul CTA tiling support, prioritizing Ampere ones at the moment. 

Also in this PR is an inline bank conflict check utility that reports bank conflict on shared memory accesses.

Remaining TODO:
 - add asymmetric swizzle operators to support more irregular tile sizes.

### CODE REVIEW

**Comment by xwang233** [comment]
!build

**Comment by xwang233** [comment]
!build

**Comment by xwang233** [comment]
!build

**Comment by zasdfgbnm** [comment]
Superseded by https://github.com/NVIDIA/Fuser/pull/155

**Pull request closed without merging**
