### PR TITLE
Cleaning up duplication between ValGraphBFS and IRBFS

### PR DESCRIPTION
**Pull request by naoyam**
Moved BFS functions from val_graph_visitor and iter_visitor to bfs.h as common template functions.

Just code movement and refactoring. There should be no change in the actual logic.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Review by zasdfgbnm — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
Build error seems real

**Comment by naoyam** [comment]
> Build error seems real

Yeah, will look into them. I haven't seen any problem but maybe it's a clang-vs-gcc difference.

**Comment by naoyam** [comment]
H100 manually checked

**Pull request merged**
