### PR TITLE
Make insertShardedAxisReordering a preseg pass. 

### PR DESCRIPTION
**Pull request by wujingyue**

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
cc @xwang233 

This ⁠unrelated, refactoring PR and another (https://github.com/NVIDIA/Fuser/pull/2611) failed nvfuser-ci/jit_python_tests_17_A100 due to OOM: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/101728986

The error message is
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 39.39 GiB of which 7.94 MiB is free. Process 1141055 has 39.37 GiB memory in use. Of the allocated memory 9.27 GiB is allocated by PyTorch, and 4.41 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)​
```

**Comment by xwang233** [comment]
Those tests started failing in main since 7/14. Still investigating which commit caused that.

**Review by cowanmeg — APPROVED** [review]

**Comment by wujingyue** [comment]
!build

**Pull request merged**
