### PR TITLE
Remove num_warp_k != 1 branch in matmul scheduler

### PR DESCRIPTION
**Pull request by jacobhinkle**
This is legacy code that is not currently in use. Instead, we now assert that `warp_tile.k == cta_tile.k`.

(Diff best viewed with `Hide whitespace`)

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by xwang233** [comment]
!build --diff-bench

**Comment by drzejan2** [comment]
The changes look good to me. During sync you mentioned that you had difficulties to verify the legacy code path - have you tried to manipulate heuristics ([link](https://github.com/NVIDIA/Fuser/blob/78343694da4c7795e035363bfbe867d10a3a327a/csrc/scheduler/matmul_utils.cpp#L116)) so `cta.k` != `warp.k` ?

**Review by drzejan2 — APPROVED** [review]

**Comment by drzejan2** [comment]
> The changes look good to me. During sync you mentioned that you had difficulties to verify the legacy code path - have you tried to manipulate heuristics ([link](https://github.com/NVIDIA/Fuser/blob/78343694da4c7795e035363bfbe867d10a3a327a/csrc/scheduler/matmul_utils.cpp#L116)) so `cta.k` != `warp.k` ?
> 
> @zasdfgbnm for visibility

Discussed offline, we are good to proceed with cleaning up. Later, we may get back to the topic where `cta.k` != `warp.k` but this should be done as a separate feature.

@jacobhinkle thank you for preparing this cleaning.

**Review by drzejan2 — APPROVED** [review]

**Comment by jacobhinkle** [comment]
Benchmark diff shows differences in layernorm and softmax http://nv/e5M/nvfuser_github_ci/codegen_diff_p11867343_j78729398_1704314898313304944_codediff_101530e_b9a33d0_custom_command_20240103_201534.html

These are unrelated to this PR but they might be signs of non-determinism in register buffer aliasing with the persistent scheduler. cc @liqiangxl

**Comment by liqiangxl** [comment]
> Benchmark diff shows differences in layernorm and softmax http://nv/e5M/nvfuser_github_ci/codegen_diff_p11867343_j78729398_1704314898313304944_codediff_101530e_b9a33d0_custom_command_20240103_201534.html
> 
> These are unrelated to this PR but they might be signs of non-determinism in register buffer aliasing with the persistent scheduler. cc @liqiangxl

The baseline used in the diff is `[101530e IdModel: Add the Permissive graph (#1522)]` which doesn't include the new PR allowing register alias of different vectorization factors. The diff is expected.

**Comment by jacobhinkle** [comment]
> The baseline used in the diff is `[101530e IdModel: Add the Permissive graph (#1522)]` which doesn't include the new PR allowing register alias of different vectorization factors. The diff is expected.

Ah ok. Sorry for the noise then. I thought the code diff would use the merge-base, but that change might not be in CI yet. Thanks.

**Pull request merged**
