### PR TITLE
clang-tidy should lint headers and cuda files

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@naoyam This is the reason why https://github.com/NVIDIA/Fuser/pull/325 is not catched by clang-tidy.

**Review by rdspring1 — APPROVED** [review]
LGTM

**Review by naoyam — APPROVED** [review]
Thanks for the fix. Guess there're more clang-tidy errors to fix.

**Comment by zasdfgbnm** [comment]
> Thanks for the fix. Guess there're more clang-tidy errors to fix.

Yeah, there are. PR authors will be responsible for these fixes. :)

**Pull request merged**
