### PR TITLE
Add an option to build with asan.

### PR DESCRIPTION
**Pull request by wujingyue**
Tested:

```
$ pip install -e .
$ nm -an bin/nvfuser_tests | grep asan
<empty>
$ python setup.py develop --build-with-asan
$ nm -an bin/nvfuser_tests | grep asan
...
00000000024f3840 B __odr_asan._ZN7nvfuser38NVFuserTest_FusionDefinition_CUDA_Test10test_info_E
00000000024f38e0 B __odr_asan._ZN7nvfuser35NVFuserTest_PyFusionCache_CUDA_Test10test_info_E
00000000024f3980 B __odr_asan._ZN7nvfuser43NVFuserTest_RecordFunctorEquality_CUDA_Test10test_info_E
0000000002528fa0 B __odr_asan._ZN5torch8autograd47_GLOBAL__N__551c3bf8_14_rng_kernels_cu_8fdfe6fb13graph_task_idE
```

### CODE REVIEW

**Review by xwang233 — APPROVED** [review]
LGTM, thanks for adding that!

**Comment by naoyam** [comment]
Don't you need to do some additional configurations like `ASAN_OPTIONS`? Last time I tried asan I had some problem with CUDA.  Something like https://github.com/google/sanitizers/issues/629

**Comment by wujingyue** [comment]
> Don't you need to do some additional configurations like `ASAN_OPTIONS`? Last time I tried asan I had some problem with CUDA. Something like [google/sanitizers#629](https://github.com/google/sanitizers/issues/629)

Yes. That's needed at run time not build time.

**Comment by naoyam** [comment]
> > Don't you need to do some additional configurations like `ASAN_OPTIONS`? Last time I tried asan I had some problem with CUDA. Something like [google/sanitizers#629](https://github.com/google/sanitizers/issues/629)
> 
> Yes. That's needed at run time not build time.

Could you please add something to https://github.com/NVIDIA/Fuser/wiki/Developer-guide?

**Comment by wujingyue** [comment]
> > > Don't you need to do some additional configurations like `ASAN_OPTIONS`? Last time I tried asan I had some problem with CUDA. Something like [google/sanitizers#629](https://github.com/google/sanitizers/issues/629)
> > 
> > 
> > Yes. That's needed at run time not build time.
> 
> Could you please add something to https://github.com/NVIDIA/Fuser/wiki/Developer-guide?

Done! https://github.com/NVIDIA/Fuser/wiki/Developer-guide#asan

**Pull request merged**
