### PR TITLE
Enable IdModel conditionally

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Will rebase this PR after https://github.com/NVIDIA/Fuser/pull/2389 is merged.

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
LGTM

**Comment by zasdfgbnm** [comment]
mark as draft for now to avoid accidental merge.

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
