### PR TITLE
Try to enforce concurrency group

### PR DESCRIPTION
**Pull request by nWEIdia**
Per @wujingyue's request and @xwang233 's suggestion, adding concurrency rule to avoid runs that may be duplicated.

### CODE REVIEW

**Comment by wujingyue** [comment]
Thanks -- you waste no time! I'll defer approval to @xwang233

**Review by xwang233 — APPROVED** [review]
Thanks for adding this!

**Comment by nWEIdia** [comment]
This PR has 3 commits, however recent commit of the three did not cause auto-cancellation of the two previous commits' workflows. Do you see anything missing or should we merge it and see if it helps at all?

**Comment by xwang233** [comment]
`Lint / standalone-build (pull_request)` appears to be cancelled in the previous two commits?

**Comment by nWEIdia** [comment]
> `Lint / standalone-build (pull_request)` appears to be cancelled in the previous two commits?

That was via my manual intervention...

**Comment by wujingyue** [comment]
> This PR has 3 commits, however recent commit of the three did not cause auto-cancellation of the two previous commits' workflows. Do you see anything missing or should we merge it and see if it helps at all?

FWIW, I noticed https://github.com/nektos/act, which might help.

**Comment by wujingyue** [comment]
Did you figure out how to test this? The feature is still useful. Although less ideal, I don't mind merging the PR and rolling it back if doesn't work.

**Comment by nWEIdia** [comment]
Looking at the nektos/act, I'm still unsure how to test concurrency, maybe the best way to test is to merge it and roll it back if it is not helping with the issue. Thanks!

**Pull request merged**
