### PR TITLE
Reduce CI time on installing CUDA and PyTorch

### PR DESCRIPTION
**Pull request by zasdfgbnm**
It makes no sense to install the entire CUDA, such as, nsight compute, etc. These are not dependencies of nvFuser.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
GitHub is broken again. I keep reopening my PR to trigger CI, but keep getting CI failures.

**Comment by zasdfgbnm** [comment]
GitHub is broken again. I keep reopening my PR to trigger CI, but keep getting CI failures.

**Review by rdspring1 — APPROVED** [review]
LGTM

**Comment by jjsjann123** [comment]
Nice~~

We might want to do this in our manylinux pip wheel build as well. So we don't have to copy the entire cuda TK directory into the manylinux docker container. cc'ing @xwang233

**Pull request merged**
