### PR TITLE
Fix random seed in multidevice mlp test

### PR DESCRIPTION
**Pull request by cowanmeg**
Only use at::manual_seed(getATenRandomSeed()) to control random seed in reference and nvFuser programs.

### CODE REVIEW

**Comment by cowanmeg** [comment]
!build

**Review by wujingyue — COMMENTED** [review]
This is a strict improvement, so LGTM. However, according to https://github.com/NVIDIA/Fuser/pull/2676#discussion_r1697697414 and the discussion around it, isn't the right fix to fork the state so we don't need to reset the state? IIUC, `at::manual_seed(...)` resets the state regardless of which seed to use.

**Comment by cowanmeg** [comment]
I think fork is also changing the state since it returns the offset back to where it began. Here we reset the seed to the default to force the offset to 0. We could read the offset before the reference and set the offset back.

**Comment by wujingyue** [comment]
> I think fork is also changing the state since it returns the offset back to where it began. 

Yes, there's still a difference between resetting the state to the beginning of the scope and resetting the state all the way to the beginning of the program. I'll need to think more about it -- I've yet to understand whether that's just a difference or has larger implication.

**Comment by cowanmeg** [comment]
For actual training, I would say resetting to 0 would introduce correlation so there is larger implications.

**Review by wujingyue — APPROVED** [review]

**Comment by wujingyue** [comment]
This is good enough for now so LGTM! 

fork_rng is worth considering. It resets the state for a smaller scope. It starts to make a difference when we run several fusions in a test and might not want their RNGs to correlate. 

Currently, fork_rng doesn't exist in the C++ API, so it needs extra plumbing to be able to use it.

**Pull request merged**
