### PR TITLE
Allocation domain inference patch mma like op

### LINKED ISSUE #2354: `RuntimeError: Stride mismatch with contiguity info.`
env
- H100
- `torch.__version__ = '2.4.0a0+gitfb696ef'`
- cuda = `12.5`
- `nvfuser.version() = '0.2.6+gita286c31'`

repro

```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T1 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False, stride_order=[0])
    T2 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T3 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[2, 1, 0])
    T4 = fd.ops.linear(T3, T2, T1)
    S5 = fd.define_scalar(1.41421, dtype=DataType.Double)
    S6 = fd.ops.reciprocal(S5)
    T7 = fd.ops.mul(T4, S6)
    T8 = fd.ops.erf(T7)
    S9 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T10 = fd.ops.mul(S9, T8)
    S11 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T12 = fd.ops.add(S11, T10)
    T13 = fd.ops.mul(T4, T12)
    T14 = fd.ops.linear(T13, T0)
    fd.add_output(T4)
    fd.add_output(T13)
    fd.add_output(T14)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn((1179648,), dtype=torch.float32, device='cuda:0').as_strided((768, 1536), (1536, 1)),
    torch.randn((1536,), dtype=torch.float32, device='cuda:0').as_strided((1536,), (1,)),
    torch.randn((1179648,), dtype=torch.float32, device='cuda:0').as_strided((1536, 768), (768, 1)),
    torch.randn((6291456,), dtype=torch.float32, device='cuda:0').as_strided((2048, 4, 768), (3072, 768, 1)),
]
fd.execute(inputs)
```

error

```log
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 139, in execute
    result = self._execute(
RuntimeError: Stride mismatch with contiguity info.  allocation domain: iS116{( (( (( getMetaData(T4) )).logical_size ))[2] )}, iS117{( (( (( getMetaData(T4) )).logical_size ))[0] )}, iS118{( (( (( getMetaData(T4) )).logical_size ))[1] )} dim: 2 expected stride: 1 actual stride: 1536
Exception raised from validateAllocationSizesAndStrides at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:237 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fb5794521e1 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x7b9490 (0x7fb579ae7490 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x7b9e78 (0x7fb579ae7e78 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: nvfuser::Expr::evaluate(nvfuser::ExpressionEvaluator const&, std::unordered_map<nvfuser::Val const*, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>, std::hash<nvfuser::Val const*>, std::equal_to<nvfuser::Val const*>, std::allocator<std::pair<nvfuser::Val const* const, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool> > > >&) const + 0x11b (0x7fb5798a54eb in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x48daa7 (0x7fb5797bbaa7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x42a8fa (0x7fb5797588fa in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x42b1e8 (0x7fb5797591e8 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x45c8d0 (0x7fb57978a8d0 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: nvfuser::FusionExecutor::runFusion(nvfuser::KernelArgumentHolder&, nvfuser::LaunchParams const&, nvfuser::CompileParams, std::vector<at::Tensor, std::allocator<at::Tensor> >) + 0x6c7 (0x7fb57978bee7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x64274e (0x7fb57997074e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x648011 (0x7fb579976011 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #11: nvfuser::FusionKernelRuntime::runWithInputs(nvfuser::KernelArgumentHolder&) + 0xa9 (0x7fb579976869 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x3fe (0x7fb5799817be in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x3c8 (0x7fb579b6eb98 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x19be25 (0x7fb5794c9e25 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x210962 (0x7fb57953e962 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x29ff80 (0x7fb5795cdf80 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #32: <unknown function> + 0x29d90 (0x7fb7b9838d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #33: __libc_start_main + 0x80 (0x7fb7b9838e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

torch.__version__ = '2.4.0a0+gitfb696ef', torch.version.cuda = '12.5'
nvfuser.version() = '0.2.6+gita286c31'
Traceback (most recent call last):
  File "/opt/pytorch/lightning-thunder/nvfuser_failure_repro.py", line 37, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 139, in execute
    result = self._execute(
RuntimeError: Stride mismatch with contiguity info.  allocation domain: iS116{( (( (( getMetaData(T4) )).logical_size ))[2] )}, iS117{( (( (( getMetaData(T4) )).logical_size ))[0] )}, iS118{( (( (( getMetaData(T4) )).logical_size ))[1] )} dim: 2 expected stride: 1 actual stride: 1536
Exception raised from validateAllocationSizesAndStrides at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:237 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fb5794521e1 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x7b9490 (0x7fb579ae7490 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x7b9e78 (0x7fb579ae7e78 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: nvfuser::Expr::evaluate(nvfuser::ExpressionEvaluator const&, std::unordered_map<nvfuser::Val const*, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool>, std::hash<nvfuser::Val const*>, std::equal_to<nvfuser::Val const*>, std::allocator<std::pair<nvfuser::Val const* const, dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, long, bool> > > >&) const + 0x11b (0x7fb5798a54eb in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x48daa7 (0x7fb5797bbaa7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x42a8fa (0x7fb5797588fa in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x42b1e8 (0x7fb5797591e8 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x45c8d0 (0x7fb57978a8d0 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: nvfuser::FusionExecutor::runFusion(nvfuser::KernelArgumentHolder&, nvfuser::LaunchParams const&, nvfuser::CompileParams, std::vector<at::Tensor, std::allocator<at::Tensor> >) + 0x6c7 (0x7fb57978bee7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x64274e (0x7fb57997074e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x648011 (0x7fb579976011 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #11: nvfuser::FusionKernelRuntime::runWithInputs(nvfuser::KernelArgumentHolder&) + 0xa9 (0x7fb579976869 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #12: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x3fe (0x7fb5799817be in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #13: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x3c8 (0x7fb579b6eb98 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x19be25 (0x7fb5794c9e25 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x210962 (0x7fb57953e962 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x29ff80 (0x7fb5795cdf80 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #32: <unknown function> + 0x29d90 (0x7fb7b9838d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #33: __libc_start_main + 0x80 (0x7fb7b9838e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

```

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #2354 

Disables allocation order inference propagation for matmul/mma/linear.

### CODE REVIEW

**Comment by jjsjann123** [comment]
This is just an intermediate step to fix failing tests. Ideally we should pull of this issue https://github.com/NVIDIA/Fuser/issues/2425

**Comment by jjsjann123** [comment]
!build

**Review by Priya2698 — APPROVED** [review]
LGTM. Thanks for the quick patch

**Review by Priya2698 — APPROVED** [review]
LGTM. Thanks for the quick patch

**Comment by jjsjann123** [comment]
Oops, looks like python test is failing with cache... Let me double check that.

**Comment by jjsjann123** [comment]
err. that test failure is dumb. no idea how I let that slipped through...

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
Looks like our CI is down.

Given the low impact from this PR and I think I have patched the failing test (from earlier ci runs) locally. I'm going to merge this PR as-is. :crossed_fingers:

**Pull request merged**
