### PR TITLE
Pip patch nvrtc

### PR DESCRIPTION
**Pull request by jjsjann123**
1. patch `rpath` for library targets, so pip installed nvfuser will find pip installed nvrtc as well as pytorch libraries.
2. added `-install_requires=` option to `setup.py`, this allows us to manually specify dependencies for pip packages, handles deployment on environment with no cuda installation. (hint nvrtc-cu11 & nvrtc-cu12)

During build we have access to cuda TK and that's where we are getting nvrtc from.

For wheel package, we need to specify the nvrtc pip package dependency. Because there's no guarantee that at runtime system there exists libnvrtc, since we are not using the nvrtc stub from pytorch.

Currently upstream supports cu117/cu118 and the secrete cu121, which requires nvidia-cuda-nvrtc-cu11 or nvidia-cuda-nvrtc-cu12 respectively. (I guess that part should/could be automated, but I'm too lazy to do that)

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
@xwang233 This one is ready for review and my local tests with cu121 seems to be working as well~~

**Review by xwang233 — APPROVED** [review]
build & tests passed

**Pull request merged**
