### PR TITLE
Fix ops.full printing

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Fixes https://github.com/NVIDIA/Fuser/issues/133.

Example from the issue:
```py
from nvfuser import FusionDefinition, DataType
import torch

def nvfuser_fusion_id3(fd : FusionDefinition) -> None :
    C0 = fd.define_constant(0, dtype=DataType.Int)
    T1 = fd.ops.full([4, 4], C0, dtype=DataType.Double)
    fd.add_output(T1)

with FusionDefinition() as fd:
    nvfuser_fusion_id3(fd)

out = fd.execute([])
```
now prints as:
```py
def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    S0 = fd.define_scalar(0, dtype=DataType.Int)
    T1 = fd.ops.full(fill_value=S0, shape=[4, 4], dtype=DataType.Double)
    fd.add_output(T1)
```
which uses a valid function signature:
```py
n [3]: fd.ops.full??
Docstring: full(self: nvfuser._C._FusionDefinition.Operators, shape: List[int], fill_value: nvfuser._C.Scalar, dtype: nvfuser._C.DataType) -> nvfuser._C.Tensor
Type:      method
```

### CODE REVIEW

**Review by kevinstephano — APPROVED** [review]
LGTM

**Comment by kevinstephano** [comment]
!build

**Comment by kevinstephano** [comment]
!build

**Comment by IvanYashchuk** [comment]
!build

**Comment by IvanYashchuk** [comment]
@kevinstephano, there was a real failure in tests that I fixed. Could you type the new "!build" command? I'm not authorized to do that.

**Comment by naoyam** [comment]
!build

**Comment by kevinstephano** [comment]
!build

**Comment by kevinstephano** [comment]
I keep getting distracted and forget to check the tests in a timely fashion to get this finally landed.  Sorry about the delay. 🙁

**Comment by IvanYashchuk** [comment]
All checks have passed now!

**Pull request merged**
