### PR TITLE
Alias allocations with same size elements despite different dtypes

### PR DESCRIPTION
**Pull request by jacobhinkle**
Currently the `reuseMemoryAllocations` lowering pass reuses `TensorView`s if they have compatible shapes and vectorization, and the same dtype. This PR replaces the dtype condition with a check that the size of each element is the same.

It is somewhat rare in our test suite that we find opportunities to re-use one buffer with another of a different type, but it does happen. For example, one case in `FusionWelfordShmoo_CUDA` corresponding to `testWelford(DataType::ComplexFloat, 1, 320, 256);` currently shows:
```
ptxas info    : Used 61 registers, 16 bytes smem, 464 bytes cmem[0]
```
With the current PR, this becomes
```
ptxas info    : Used 59 registers, 16 bytes smem, 464 bytes cmem[0]
```
since we re-use two register `TensorView`s that change from `int64_t` to `std::complex<float>`.

Re-using shared memory in these cases is likely always beneficial, but the effect of explicitly re-using registers is hard to analyze since the compiler pipeline is so complicated. It is likely rarely harmful, so this behavior is on by default. However, it can be disabled using `DisableOption::ReuseMismatchedTypeRegisters` or `NVFUSER_DISABLE=reuse_mismatched_type_registers`.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
Assuming it is safe to do this, I am a bit surprised NVRTC doesn't find this opportunity by itself.

**Comment by jacobhinkle** [comment]
!build

**Comment by zasdfgbnm** [comment]
Are you saying my claim in https://github.com/NVIDIA/Fuser/issues/221 about reusing registers are useless is wrong? This is 🤯.

**Comment by jacobhinkle** [comment]
> Are you saying my claim in https://github.com/NVIDIA/Fuser/issues/221 about "reusing registers are useless" is wrong? This is 🤯.

I think so! I was planning to try this for smem tensors then noticed it has an effect for registers. Maybe I am missing some reason this is unsafe so it is not done automatically.

**Review by zasdfgbnm — APPROVED** [review]

**Pull request merged**
