### PR TITLE
Lazily load and invoke driver API

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Suggest starting review from `csrc/driver_api.h`

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by naoyam — COMMENTED** [review]
Should we delete this line in CMakeLists.txt?
```
target_link_libraries(${NVFUSER_CODEGEN} PUBLIC CUDA::cuda_driver)
```

**Comment by zasdfgbnm** [comment]
> Should we delete this line in CMakeLists.txt?
> 
> ```
> target_link_libraries(${NVFUSER_CODEGEN} PUBLIC CUDA::cuda_driver)
> ```

I think we should. But this option is only for submodule build. I don't think changing this will make nvFuser stop linking with `libcuda.so`. More build changes are required, but I don't have an idea on how to do it. I think build changes should go to a separate PR.

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
