### PR TITLE
Fix cupti build

### PR DESCRIPTION
**Pull request by zasdfgbnm**
`libcupti.so` does not exist in `${CUDA_TOOLKIT_ROOT_DIR}/lib64/`

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
Errrr, the failure does not make sense. I freshly downloaded a run file to install cuda, and there is no `/path/to/cuda/lib64/libcupti.so`. In my archlinux, the path also follow the run file. Why ubuntu move files around?

**Comment by zasdfgbnm** [comment]
!build

**Comment by jjsjann123** [comment]
I'm totally out of context here.

Are we just struggling to find cupti at runtime?
We can try get cupti from pypi instead. https://pypi.org/project/nvidia-cuda-cupti-cu12/
Similar to how we are getting nvrtc. We can add this relative path to RPATH. cc'ing @xwang233

**Comment by zasdfgbnm** [comment]
> Are we just struggling to find cupti at runtime?

Yes, exactly.



> We can try get cupti from pypi instead. https://pypi.org/project/nvidia-cuda-cupti-cu12/
> Similar to how we are getting nvrtc. We can add this relative path to RPATH. cc'ing @xwang233

Yeah, this is also possible. My current PR should work with runfile-installed CUDA and on archlinux. But I don't have a preference on which is better.

**Comment by zasdfgbnm** [comment]
> But I don't have a preference on which is better.

Which makes more sense in terms of packaging wheel?

**Comment by jjsjann123** [comment]
> > But I don't have a preference on which is better.
> 
> Which makes more sense in terms of packaging wheel?

oh it definitely is the pypi thing makes more sense. i.e. people can pip install torch and pip install nvfuser to have it running. Nobody want to mess with CUDA installation :laughing:

**Comment by jjsjann123** [comment]
I think the only thing you need to change here is just the `CMakeLists.txt` to add the proper RPATH.
We'll need to update our CI script in the manylinux build to pass the "proper" cupti dependency per our cuda version. Which maybe @xwang233 could help with that?!

**Comment by zasdfgbnm** [comment]
I will close this PR and let @xwang233 help.

**Comment by zasdfgbnm** [comment]
Had some offline chat with @xwang233 . Let's use our local CUDA for local development, and use pypi for wheel release. Reopen this PR.

**Review by xwang233 — APPROVED** [review]
If this can fix your local build on arch, go for it.

**Pull request merged**
