### PR TITLE
Parametrize Hopper matmul tests

### PR DESCRIPTION
**Pull request by jacobhinkle**

### CODE REVIEW

**Review by rdspring1 — COMMENTED** [review]
Is this ready for review?

**Comment by jacobhinkle** [comment]
> Is this ready for review?

Not quite. I was hitting some errors so I put it aside to work on avoiding broadcasts in the MmaOp for now. But thanks for the reminder. I'll give it another shot shortly.

**Comment by rdspring1** [comment]
The PR runs fine in #3404. Was it a specific shape that was failing?
Would you like to merge the PR as-is and make a note of the failing shapes?

**Comment by jacobhinkle** [comment]
It runs fine. I had been trying to extend it to accept allocation domains on the inputs, but that's more complicated than I thought. So let's merge as is and we can tweak later.

**Review by rdspring1 — APPROVED** [review]

**Pull request merged**
