### PR TITLE
Add unit test for issue 1279

### PR DESCRIPTION
**Pull request by rdspring1**
The issue #1279 was resolved, so this PR adds a unit tests for the issue.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!test

**Review by jjsjann123 — APPROVED** [review]

**Comment by jjsjann123** [comment]
Just for reference. We think the issue is likely fixed by #1898

**Comment by rdspring1** [comment]
https://github.com/NVIDIA/Fuser/pull/1898 allows the concretization pass to create static shapes for factory operations before segmentation.

**Pull request merged**
