### PR TITLE
Remove non-dunder op methods from python tensors/scalars

### PR DESCRIPTION
**Pull request by jacobhinkle**
The methods such as `tv.sum()` is marginally more convenient than the equivalent `fd.ops.sum(tv)`, but requires a lot of boilerplate in `python_bindings.cpp`. In order to reduce the maintenance burden, this PR removes all of these types of methods. We do keep the "dunder" methods such as `__add__` so that we can perform `tv1 + tv2` and similar operations.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by xwang233** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
@kevinstephano I believe this is ready.

**Review by kevinstephano — APPROVED** [review]
LGTM

**Pull request merged**
