### PR TITLE
reorder outer reduction tv in inner-outer scheduler when there are view ops in the fusion

### PR DESCRIPTION
**Pull request by liqiangxl**
**Issue**:  The IDs involved in view transforms are moved to the outer most positions in the loop domain, e.g. `T0[i0, i2, i3] --> T3[i0, i2*i3]`, `propagateReshapeTransforms` moves `{i2*i3}` to the outer most position and the loop domain becomes ` (iS31{( i2 * i3 )}, iS0{i0})`. To maintain the original reduction axis, for reduction tv we should reorder the loop domain back to its original logical domain, this is done for inner reduction in innerOuter scheduler but not for outer reduciton.
(1) Inner reduction tv after  `propagateReshapeTransforms`
```
T3_l_float[ rS13{( i2 * i3 )}, iS12{i0} ]
 logical domain : (iS12{i0}, rS13{( i2 * i3 )})
 contiguity: t n
 loop domain : (rS13{( i2 * i3 )}, iS12{i0})
```
(2) Inner reduction tv after `reorder(domainReorderAsLogicalMap)`
```
T3_l_float[ iS12{i0}, rS13{( i2 * i3 )} ]
 logical domain : (iS12{i0}, rS13{( i2 * i3 )})
 contiguity: t n
 loop domain : (iS12{i0}, rS13{( i2 * i3 )})
```
(3) Outer reduction tv after  `propagateReshapeTransforms`
```
T6_l_float[ iS19{( i2 * i3 )}, rS18{i0} ]
 logical domain : (rS18{i0}, iS19{( i2 * i3 )})
 contiguity: n t
 loop domain : (iS19{( i2 * i3 )}, rS18{i0})
```
`reorder(domainReorderAsLogicalMap)` is not used for Outer reduction tv. This leads to error `Cannot rfactor axes that are not reduction axes.` when the scheduler tries to rFactor outer dim, which is `iS19{( i2 * i3 )`

**Fix**: Add `reorder(domainReorderAsLogicalMap)` for outer reduction tv.

**Results**: Added a unit test, err is fixed. Outer reduction tv is correctly reordered as:
```
T6_l_float[ rS18{i0}, iS19{( i2 * i3 )} ]
 logical domain : (rS18{i0}, iS19{( i2 * i3 )})
 contiguity: n t
 loop domain : (rS18{i0}, iS19{( i2 * i3 )})
```

### CODE REVIEW

**Comment by liqiangxl** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
:clap:

**Comment by liqiangxl** [comment]
!build

**Comment by jjsjann123** [comment]
quick note from our discussion. Let's verify that this is indeed a functional issue on ToT. i.e. repro that the added cpp test would hit an error.

**Comment by liqiangxl** [comment]
> quick note from our discussion. Let's verify that this is indeed a functional issue on ToT. i.e. repro that the added cpp test would hit an error.

Without the fix in this PR, the newly added test tiggers the following err in the current main branch:
```
[ RUN      ] InnerOuterReshapeTest.ReshapeOuterDimTrueOrFalse/false
unknown file: Failure
C++ exception with description " INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/transform_rfactor.cpp":294, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Cannot rfactor axes that are not reduction axes.
Exception raised from runReplay at /opt/pytorch/nvfuser/csrc/transform_rfactor.cpp:294 (most recent call first):
```
The reason was described in the PR description:
```
reorder(domainReorderAsLogicalMap) is not used for Outer reduction tv. This leads to error Cannot rfactor axes that are not reduction axes. when the scheduler tries to rFactor outer dim, which is iS19{( i2 * i3 )
```

**Pull request merged**
