### PR TITLE
patching missing fusion guard

### PR DESCRIPTION
**Pull request by jjsjann123**
fixes: #477

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Could you explain why this wasn't needed before?

**Comment by jjsjann123** [comment]
> Could you explain why this wasn't needed before?

well... don't have an answer to that yet. Let me pull an older container to figure out if it's going through a different code path...
Frankly speaking, I'm pretty surprised this isn't causing tons of failures yet. :shrug:

**Review by zasdfgbnm — APPROVED** [review]
Stamping as this fixes the CI and looks low risk to accept. But still, we need to understand why this becomes needed recently.

**Comment by jjsjann123** [comment]
> Stamping as this fixes the CI and looks low risk to accept. But still, we need to understand why this becomes needed recently.

Updated comment in the original issue. I'll try to merge this PR.

**Pull request merged**
