### PR TITLE
#754: newScalar, newConstant -> create<Val>

### PR DESCRIPTION
**Pull request by tfogal**

### CODE REVIEW

**Review by zasdfgbnm — APPROVED** [review]
Thanks for the cleanup. Are you able to do `!build`?

**Comment by tfogal** [comment]
!build

**Comment by tfogal** [comment]
As of ~30 min ago, should be able to...

**Comment by zasdfgbnm** [comment]
@tfogal Is this ready to merge?

**Comment by tfogal** [comment]
Yep! Looks like I didn't click "ready for review" before, oops

**Pull request merged**
