### PR TITLE
Add correctness tests for remaining unary-float operations

### PR DESCRIPTION
**Pull request by rdspring1**
This PR adds tests for the following operations:
- abs, acosh, asin, asinh, atan, atanh, cos, cosh, erf, erfc, erfcinv, erfinv, exp, exp2, expm1, lgamma, log, log10, log1p, log2, reciprocal, rsqrt, sign, sin, sinh, sqrt, tan, tanh

The `elementwise_unary_torch` input generator creates random values for a function's input domain. It does not test specific small, large, or extremal ('-inf', 'inf', 'nan') input values.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by kevinstephano** [comment]
Could you note in the main description what you are numerically testing in this PR.

**Review by kevinstephano — APPROVED** [review]
LGTM

**Pull request merged**
