### PR TITLE
Clear pytorch allocator occasionally in pytest_ops.py

### PR DESCRIPTION
**Pull request by jacobhinkle**
This should fix the OOM errors in CI on V100

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
It seems that the V100 test did not run for some reason, so I can't tell yet whether the OOM error is addressed.

**Comment by jacobhinkle** [comment]
!build

**Comment by Priya2698** [comment]
V100 jobs have been removed for most tests except multi-GPU.
CC: @xwang233 to confirm.

**Comment by xwang233** [comment]
> V100 jobs have been removed for most tests except multi-GPU. CC: @xwang233 to confirm.

That is exactly correct.

**Pull request closed without merging**
