### PR TITLE
Skip serializing `FusionKernelRuntime` if it is not compiled

### PR DESCRIPTION
**Pull request by rdspring1**
This PR avoids the following error when the `FusionKernelRuntime` is not compiled in serde test suite.

```
RuntimeError: compiled_kernel_ != nullptr && (!compiled_kernel->cubin.empty() || !compiled_kernel->ptx.empty())
```

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by jjsjann123** [comment]
sorry somehow forgot about this one.

**Review by jjsjann123 — COMMENTED** [review]
QQ: was this the case for a no-op fusion or something?

Is there an existing test failure that this PR patches, otherwise, can we add a python test as well.

**Comment by rdspring1** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
stamping just to keep CI green.

**Comment by jjsjann123** [comment]
!build

**Comment by rdspring1** [comment]
Replace with https://github.com/NVIDIA/Fuser/pull/2061

**Pull request closed without merging**
