### PR TITLE
Adaptive layernorm host benchmark

### PR DESCRIPTION
**Pull request by Priya2698**
This benchmark adds host benchmarking for the `adaptive layernorm forward` fusion.

Screenshot 2024-10-21 at 2 23 47 PM

### CODE REVIEW

**Comment by naoyam** [comment]
IIRC, there was some context about this particular case. What was the original case?

**Comment by Priya2698** [comment]
> IIRC, there was some context about this particular case. What was the original case?

Yes, IIRC, this case was important for dynamic shape latency. CC: @kevinstephano

**Comment by naoyam** [comment]
Can you please the background context as a code comment?

**Comment by naoyam** [comment]
Looks good to me. I'll let @kevinstephano stamp the PR.

**Review by kevinstephano — COMMENTED** [review]
LGTM

**Review by kevinstephano — APPROVED** [review]
LGTM

**Comment by xwang233** [comment]
!build

**Pull request merged**
