### PR TITLE
removing dynamo tests 

### PR DESCRIPTION
**Pull request by jjsjann123**
nvfuser backend has been removed from primtorch https://github.com/pytorch/pytorch/pull/105789

### CODE REVIEW

**Comment by jacobhinkle** [comment]
Should we also update `manual_ci.sh`?

**Review by jacobhinkle — APPROVED** [review]
:+1:

**Comment by IvanYashchuk** [comment]
There was a PR for that https://github.com/NVIDIA/Fuser/pull/638 😄

**Comment by jjsjann123** [comment]
oops, I totally forgot that one.

**Comment by jjsjann123** [comment]
Looks like CI is mostly clean.
I'm closing this one in favor of #638

**Pull request closed without merging**
