### PR TITLE
Fix benchmark

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/NVIDIA/Fuser/issues/96

### CODE REVIEW

**Comment by naoyam** [comment]
Why did it cause the error message? Can we detect the error and give a better error message?

**Comment by zasdfgbnm** [comment]
> Why did it cause the error message? Can we detect the error and give a better error message?

When the inputs is given to `compileFusion`, it will try to infer launch parameters and will try to compute shared memory usage. However, the fusion is scheduled like `split(i, blockDim.x)`, which can not be infered without the launch constraints.

**Review by naoyam — APPROVED** [review]
LGTM, though still unclear why this was working.

**Comment by naoyam** [comment]
Looks like those benchmarks are not the only ones that do `compileFusion` a scheduled fusion without passing launch constraints.

**Comment by liqiangxl** [comment]
here is another one, https://github.com/NVIDIA/Fuser/pull/102
after this, all the benchmarks work fine.

**Comment by naoyam** [comment]
Thanks @liqiangxl. Could you please do a quick check to find where this started to happen? I wonder if my PR of cleaning up index types might be the reason, but I'm pretty sure I ran all the benchmarks. Looking at the recent merged PRs, I don't see anything particularly suspicious.

**Comment by liqiangxl** [comment]
It failed at least on the initial commit of this new Fuser repo. Let me check the old one.

**Pull request merged**
