### PR TITLE
Add LL suffix to Int literals

### PR DESCRIPTION
**Pull request by jacobhinkle**
In https://github.com/NVIDIA/Fuser/issues/973#issuecomment-1741343225, it was mentioned that expressions on `DataType::Int` constants are not necessarily safe from overflow. For example, an `exp` expression on `Int` constants currently prints like the example `2 ** 30`. Integer literals that are not very large will be compiled as 32-bit ints, so this arithmetic will be taking place at too low precision. This PR addresses this issue by adding a suffix of `LL` for `Int` constants so that these will translate to long long, which is 64-bit (see comment in code and second reference below on why we don't use `L` instead).

References:
- https://en.cppreference.com/w/cpp/language/integer_literal
- https://en.cppreference.com/w/cpp/language/types

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM.

Note that this should not be necessary because we always have an explicit cast like `(nvfuser_index_t)2^30`, and `nvfuser_index_t` should be `int` only when we determine all indexing integers should be less than `INT_MAX`.

**Comment by jacobhinkle** [comment]
> LGTM.
> 
> Note that this should not be necessary because we always have an explicit cast like `(nvfuser_index_t)2^30`, and `nvfuser_index_t` should be `int` only when we determine all indexing integers should be less than `INT_MAX`.

That is true for `Index`, but `Int` constants can also be used in expressions. I just pushed a test that fails on main with this output:
```
======= Codegen output for kernel: kernel1 =======

__global__ void kernel1(Tensor<int64_t, 0, 0> T0) {
  int64_t i0;
  i0 = 65536 * 65536;
  T0[0] = i0;
}

======================================

ATen: 4.29497e+09
[ CUDALongType{} ]
NVFuser: 0
[ CUDALongType{} ]
```
On this branch it passes and prints the following:
```
======= Codegen output for kernel: kernel1 =======

__global__ void kernel1(Tensor<int64_t, 0, 0> T0) {
  int64_t i0;
  i0 = 65536LL * 65536LL;
  T0[0LL] = i0;
}

======================================

ATen: 4.29497e+09
[ CUDALongType{} ]
NVFuser: 4.29497e+09
[ CUDALongType{} ]
```
A number of tests that compare codegen strings are currently failing. I'll fix those up then merge.

**Comment by jacobhinkle** [comment]
!build

**Comment by naoyam** [comment]
> > LGTM.
> > Note that this should not be necessary because we always have an explicit cast like `(nvfuser_index_t)2^30`, and `nvfuser_index_t` should be `int` only when we determine all indexing integers should be less than `INT_MAX`.
> 
> That is true for `Index`, but `Int` constants can also be used in expressions. I just pushed a test that fails on main with this output:
> 
> ```
> ======= Codegen output for kernel: kernel1 =======
> 
> __global__ void kernel1(Tensor<int64_t, 0, 0> T0) {
>   int64_t i0;
>   i0 = 65536 * 65536;
>   T0[0] = i0;
> }
> 
> ======================================
> 
> ATen: 4.29497e+09
> [ CUDALongType{} ]
> NVFuser: 0
> [ CUDALongType{} ]
> ```
> 
> On this branch it passes and prints the following:
> 
> ```
> ======= Codegen output for kernel: kernel1 =======
> 
> __global__ void kernel1(Tensor<int64_t, 0, 0> T0) {
>   int64_t i0;
>   i0 = 65536LL * 65536LL;
>   T0[0LL] = i0;
> }
> 
> ======================================
> 
> ATen: 4.29497e+09
> [ CUDALongType{} ]
> NVFuser: 4.29497e+09
> [ CUDALongType{} ]
> ```
> 
> A number of tests that compare codegen strings are currently failing. I'll fix those up then merge.

That's a good point. Thanks for the fix!

**Pull request merged**
