### PR TITLE
Rename FusionExector to KernelExecutor, fe to ke, fec to executor_cache

### PR DESCRIPTION
**Pull request by naoyam**
This is just mechanical name change only. Intended to simplify #3263.

### CODE REVIEW

**Comment by naoyam** [comment]
!test

**Review by wujingyue — APPROVED** [review]

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
Changed lines after this PR:

```
+2,614 −2,216
```
https://github.com/NVIDIA/Fuser/pull/3351/files

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!build

**Pull request merged**
