### PR TITLE
TorchScript integration removal

### PR DESCRIPTION
**Pull request by jjsjann123**
Removes TorchScript integration code

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
Let's see if the internal pipeline actually went through. :crossed_fingers:

**Comment by jjsjann123** [comment]
Looks like there's still some symbol issue across torch packages.

```
ImportError: /usr/local/lib/python3.10/site-packages/nvfuser/lib/libnvfuser_codegen.so: undefined symbol: _ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEENS_14SourceLocationEPKcb
```

I'm guessing we can switch our `TORCH_WARN`/`TORCH_WARN_ONCE` to some home cooked utility?!

**Comment by jjsjann123** [comment]
Even though this one doesn't fix the lib compatibility issue, I guess we should still move forward and merge this one since it's functional. cc'ing @xwang233

**Review by xwang233 — APPROVED** [review]

**Comment by naoyam** [comment]
10K lines of removal 🎉

**Pull request merged**
