### PR TITLE
Fix `SliceOpRecord::operator()` by ignoring reduction dimensions. 

### PR DESCRIPTION
**Pull request by wujingyue**
Before this PR, the repro ran into an out-of-bound index error.

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
:pray: Oops, sorry about this one.

**Comment by jjsjann123** [comment]
!build

**Pull request merged**
