### PR TITLE
Hopper Mma tests without `BroadcastOp`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/NVIDIA/Fuser/issues/1628

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by drzejan2 — APPROVED** [review]
Changes look good - thank you for simplifying the mma tests for Hopper and exposing helpers so we can reuse them in tests.

**Comment by zasdfgbnm** [comment]
Internal test failure seems to be unrelated

**Pull request merged**
