### PR TITLE
Add `AbstractTensor::unzip`

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by jacobhinkle — APPROVED** [review]
What do you think of the name `unzip` as an alternative to `unbatch`? e.g. [unzip](https://hackage.haskell.org/package/base-4.20.0.1/docs/Prelude.html#v:unzip)

**Comment by zasdfgbnm** [comment]
> What do you think of the name `unzip` as an alternative to `unbatch`? e.g. [unzip](https://hackage.haskell.org/package/base-4.20.0.1/docs/Prelude.html#v:unzip)

makes sense. Changed

**Comment by zasdfgbnm** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM too

**Pull request merged**
