### PR TITLE
Adding an option to put a `-version-tag=[TAG]` option

### PR DESCRIPTION
**Pull request by jjsjann123**
This is to allow us customize wheel pkg version for nightly posting

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
FYI: Python has an official tool to infer version from git https://github.com/pypa/setuptools_scm

**Comment by jjsjann123** [comment]
> FYI: Python has an official tool to infer version from git https://github.com/pypa/setuptools_scm

Looks pretty handy. I did a quick test on that one, seems like it requires a git tag to bump the version that it infers. I feel it will work nicely with releases, if we don't care much about people bumping versioning number in their PR.
We can discuss this and switch over once we have the repo up.

```
root@e81c848e5cc2:/jiej/playground/toy_wheel# python setup.py --version
0.0.9.dev1+gd263139
root@e81c848e5cc2:/jiej/playground/toy_wheel# git log
commit d263139283ab740d51e08f7b117d4cee093e31fb (HEAD -> master)
Author: jjsjann123 <jiej@nvidia.com>
Date:   Tue Apr 11 11:38:59 2023 -0700

    adding one commit

commit c9d24f34d4aa019ba1300474f6459258d8fd4898 (tag: v0.0.8)
Author: jjsjann123 <jiej@nvidia.com>
Date:   Tue Apr 11 11:31:32 2023 -0700

    initial commit
root@e81c848e5cc2:/jiej/playground/toy_wheel# cat setup.py
from setuptools import setup, find_packages

packages = find_packages()

# note we need to create a version tag in git to infer current version

setup(
  name="nvfuser",
  use_scm_version=True,
  setup_requires=['setuptools_scm'],
  #version="0.0.1",
  author="Jie Jiang",
  author_email="alex.jann2012@gmail.com",
  description="example package",
  packages=packages,
)
root@e81c848e5cc2:/jiej/playground/toy_wheel#
```

**Comment by zasdfgbnm** [comment]
For development versions like `0.0.9.dev1+gd263139`, pypi will not allow you to release them. So the development version  is really just an internal tracker for developers. But using that tool also means, whenever you want to bump up the version, you will need a new tag. So we might end up with lots of tags on GitHub.

**Comment by jjsjann123** [comment]
lots of tags doesn't sound like a really bad thing... Also looking at how frequent we bump the version txt, we might not be too bad with it.

> pypi will not allow you to release them.

I'm aware of that, but we use internal tool to push to pypi, which I think actually likes this. Especially for nightly pip wheel, we would also want to add a date tag there so they'll always push the latest to nightly.

**Review by xwang233 — APPROVED** [review]
LGTM

**Pull request merged**
