### PR TITLE
Disable propagation rule matmul test

### PR DESCRIPTION
**Pull request by jjsjann123**
a temporary patch. for details see #1810

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]

**Comment by jjsjann123** [comment]
I don't understand this... How could it still fail here while building against stable torch succeeded in the other PR: https://github.com/NVIDIA/Fuser/pull/1809 
:confused: 

```
#18 131.1 In file included from /workspace/Fuser/benchmark/batch_norm_channels_last_backward.cpp:25:
#18 131.1 /workspace/Fuser/test/utils.h: In function ‘bool nvfuser::maybeClearAllocator(int64_t)’:
#18 131.1 /workspace/Fuser/test/utils.h:395:26: error: cannot convert ‘c10::DeviceIndex*’ {aka ‘signed char*’} to ‘int*’
#18 131.1   395 |     c10::cuda::GetDevice(&device_index);
#18 131.1       |                          ^~~~~~~~~~~~~
#18 131.1       |                          |
#18 131.1       |                          c10::DeviceIndex* {aka signed char*}
```

**Comment by jjsjann123** [comment]
Err seems like my previous patch did miss the test util thing. I'll patch that again.

Meanwhile, why are we getting different torch version from `pip install torch --index-url https://download.pytorch.org/whl/cu121`?!?!?!

looks like the previous ci build was getting 2.2.0, while this one pulls 2.2.1.
cc'ing @xwang233

**Comment by xwang233** [comment]
> Err seems like my previous patch did miss the test util thing. I'll patch that again.
> 
> Meanwhile, why are we getting different torch version from `pip install torch --index-url https://download.pytorch.org/whl/cu121`?!?!?!
> 
> looks like the previous ci build was getting 2.2.0, while this one pulls 2.2.1. cc'ing @xwang233

🤔  Can you provide CI job links?

**Comment by jjsjann123** [comment]
https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/83483604
https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/83475915

These two jobs are probably only 1 hour~ away from each other.

There's no rush in patching this. I have a repro locally and I'm using that to verify my second patch.

**Comment by jjsjann123** [comment]
CI clears on A100. I'm merging this one.

**Comment by xwang233** [comment]
> https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/83483604 https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/83475915
> 
> These two jobs are probably only 1 hour~ away from each other.
> 
> There's no rush in patching this. I have a repro locally and I'm using that to verify my second patch.

I saw a 
```
#17 sha256:c69557c548808dbbeb250ab0fbf01449d09425a9ad0338e0a854ded79d15f2f3
#17 CACHED
```
in the docker image build
😆

**Pull request merged**
