### PR TITLE
avoid 0 batch in layer norm backward

### LINKED ISSUE #465: layer norm backward failed on (108, 32)
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id94(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguity=[True, True], dtype=DataType.Half, is_cpu=False)
    T1 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguity=[True, True], dtype=DataType.Half, is_cpu=False)
    T2 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguity=[True, True], dtype=DataType.Half, is_cpu=False)
    T3 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Half, is_cpu=False)
    T4 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Half, is_cpu=False)
    T5 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Half, is_cpu=False)
    T6 = fd.define_tensor(symbolic_sizes=[-1], contiguity=[True], dtype=DataType.Half, is_cpu=False)
    T7 = fd.ops.cast(T0, dtype=DataType.Float)
    T8 = fd.ops.cast(T1, dtype=DataType.Float)
    T9 = fd.ops.cast(T3, dtype=DataType.Float)
    T10 = fd.ops.cast(T4, dtype=DataType.Float)
    S11 = fd.define_scalar(32, dtype=DataType.Int)
    T12 = fd.ops.broadcast_in_dim(T5, output_shape=[108, 32], broadcast_dims=[0])
    T13 = fd.ops.sub(T2, T12)
    T14 = fd.ops.broadcast_in_dim(T6, output_shape=[108, 32], broadcast_dims=[0])
    T15 = fd.ops.mul(T13, T14)
    T16 = fd.ops.broadcast_in_dim(T9, output_shape=[108, 32], broadcast_dims=[1])
    T17 = fd.ops.mul(T7, T16)
    T18 = fd.ops.mul(S11, T17)
    T19 = fd.ops.sum(T17, axes=[1], keepdim=False, dtype=DataType.Null)
    T20 = fd.ops.broadcast_in_dim(T19, output_shape=[108, 32], broadcast_dims=[0])
    T21 = fd.ops.mul(T17, T15)
    T22 = fd.ops.sum(T21, axes=[1], keepdim=False, dtype=DataType.Null)
    T23 = fd.ops.broadcast_in_dim(T22, output_shape=[108, 32], broadcast_dims=[0])
    T24 = fd.ops.mul(T15, T23)
    T25 = fd.ops.sub(T18, T20)
    T26 = fd.ops.sub(T25, T24)
    S27 = fd.ops.reciprocal(S11)
    T28 = fd.ops.mul(S27, T14)
    T29 = fd.ops.mul(T28, T26)
    T30 = fd.ops.mul(T7, T15)
    T31 = fd.ops.sum(T30, axes=[0], keepdim=False, dtype=DataType.Null)
    T32 = fd.ops.sum(T7, axes=[0], keepdim=False, dtype=DataType.Null)
    T33 = fd.ops.cast(T29, dtype=DataType.Half)
    T34 = fd.ops.cast(T31, dtype=DataType.Half)
    T35 = fd.ops.cast(T32, dtype=DataType.Half)
    fd.add_output(T33)
    fd.add_output(T34)
    fd.add_output(T35)

with FusionDefinition() as fd:
    nvfuser_fusion_id94(fd)

inputs = [
    torch.randn((108, 32), dtype=torch.float16, device='cuda:0').as_strided((108, 32), (32, 1)),
    torch.randn((108, 32), dtype=torch.float16, device='cuda:0').as_strided((108, 32), (32, 1)),
    torch.randn((108, 32), dtype=torch.float16, device='cuda:0').as_strided((108, 32), (32, 1)),
    torch.randn((32,), dtype=torch.float16, device='cuda:0').as_strided((32,), (1,)),
    torch.randn((32,), dtype=torch.float16, device='cuda:0').as_strided((32,), (1,)),
    torch.randn((108,), dtype=torch.float16, device='cuda:0').as_strided((108,), (1,)),
    torch.randn((108,), dtype=torch.float16, device='cuda:0').as_strided((108,), (1,)),
]
fd.execute(inputs)

### PR DESCRIPTION
**Pull request by liqiangxl**
Fix #465 
The vectorization factor was not correctly calculated in `checkCombinedReductionShape`

### CODE REVIEW

**Review by naoyam — COMMENTED** [review]
The change seems to make sense, but what do you mean by "avoid 0 batch"?

**Comment by liqiangxl** [comment]
> The change seems to make sense, but what do you mean by "avoid 0 batch"?

The calculated batch size is 0 in the original branch for case with a hidden size of 32. It will be vecorized by 8, then start with 8 threads per block. batch size = 32 / 8 / 8 = 0.

**Comment by naoyam** [comment]
> > The change seems to make sense, but what do you mean by "avoid 0 batch"?
> 
> The calculated batch size is 0 in the original branch for case with a hidden size of 32. It will be vecorized by 8, then start with 8 threads per block. batch size = 32 / 8 / 8 = 0.

Should we add an assertion?

**Comment by liqiangxl** [comment]
> > > The change seems to make sense, but what do you mean by "avoid 0 batch"?
> > 
> > 
> > The calculated batch size is 0 in the original branch for case with a hidden size of 32. It will be vecorized by 8, then start with 8 threads per block. batch size = 32 / 8 / 8 = 0.
> 
> Should we add an assertion?

This was captured by the assertion we already have:
```
  TORCH_INTERNAL_ASSERT(
    iop.inner_vect * iop.inner_batch * threads_per_block == inner_dim_numel,
    " inner_dim_numel must be dividable by the multiplication of a quarter warp and vectorize_factor");
```

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
