### PR TITLE
avoid assert when consumer_innermost_ndims == 0

### LINKED ISSUE #1895: [AllocationDomain][ReductionScheduler] Unexpected producer RF ID
Running into error: `C++ exception with description "false INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp":981, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Unexpected producer RF ID: iS14{512}
Exception raised from getVectorizationBreakPointOfReductionProducer at /opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp:981 (most recent call first):`

Repro cpp test.
```
TEST_F(NVFuserTest, ReductionSchedulerRepro) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());
  long x = 2L, y = 8L, z = 8L, w = 16L, h = 512L;
  auto tv0 = TensorViewBuilder()
                 .ndims(5)
                 .shape({-1, -1, -1, -1, -1})
                 .contiguity({true, true, true, true, true})
                 .strideOrder({4, 3, 2, 0, 1})
                 .build();
  fusion->addInput(tv0);
  auto tv1 = full(
      {IrBuilder::create<Val>(x),
       IrBuilder::create<Val>(y),
       IrBuilder::create<Val>(z),
       IrBuilder::create<Val>(w),
       IrBuilder::create<Val>(h)},
      fusion->oneVal(),
      DataType::Float);
  auto tv2 = mul(tv0, tv1);
  auto tv3 = sum(tv2, {2, 4});
  fusion->addOutput(tv3);
  std::vector<IterDomain*> tv3_dom = {
      tv3->axis(0), tv3->axis(1), tv3->axis(2), tv3->axis(4), tv3->axis(3)};
  tv3->setAllocationDomain(tv3_dom, true);

  // tv1 is a constant tensor, and its domains are constant.
  // Its constant domains are used in ExactMappedExtentSubstitutionPass
  // to substitute the domains of tv0.
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 =
      at::randn({x, y, z, w, h}, options)
          .as_strided({x, y, z, w, h}, {w * h * z * y, w * h * z, w * h, 1, w});
  std::vector<c10::IValue> inputs({t0});

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs(inputs);

  auto ref = t0.to(at::kDouble).sum({2, 4});
  testValidate(
      executor_cache.fusion(), cg_outputs, inputs, {ref}, __LINE__, __FILE__);
}
```

Kernel looks something like this:
```
%kernel {
T1_l[ iS5{2}, iS6{8}, iS7{8}, iS8{16}, iS9{512} ]
   = full({2, 8, 8, 16, 512}, float(1));
T2_l[ iS10{2}, iS11{8}, iS12{8}, iS13{16}, iS14{512} ]
   = T0_g[ iS20{2}, iS21{8}, iS22{8}, iS23{16}, iS24{512} ]
   * T1_l[ iS5{2}, iS6{8}, iS7{8}, iS8{16}, iS9{512} ];
T3_g[ iS15{2}, iS16{8}, rS17{8}, iS18{16}, rS19{512} ]
   = reduction( T2_l[ iS10{2}, iS11{8}, iS12{8}, iS13{16}, iS14{512} ], op = add, initial value = float(0), allreduce = false )

TransformPrinter :
T0_g[ iS20{2}, iS21{8}, iS22{8}, iS23{16}, iS24{512} ]
 root domain : (iS20{2}, iS21{8}, iS22{8}, iS23{16}, iS24{512})
 allocation domain : (iS20{2}, iS21{8}, iS22{8}, iS24{512}, iS23{16})
 contiguity: t t t t t
 leaf domain : (iS20{2}, iS21{8}, iS22{8}, iS23{16}, iS24{512})
T1_l[ iS5{2}, iS6{8}, iS7{8}, iS8{16}, iS9{512} ]
 root domain : (iS5{2}, iS6{8}, iS7{8}, iS8{16}, iS9{512})
 contiguity: t t t t t
 leaf domain : (iS5{2}, iS6{8}, iS7{8}, iS8{16}, iS9{512})
T2_l[ iS10{2}, iS11{8}, iS12{8}, iS13{16}, iS14{512} ]
 root domain : (iS10{2}, iS11{8}, iS12{8}, iS13{16}, iS14{512})
 contiguity: t t t t t
 leaf domain : (iS10{2}, iS11{8}, iS12{8}, iS13{16}, iS14{512})
T3_g[ iS15{2}, iS16{8}, rS17{8}, iS18{16}, rS19{512} ]
 root domain : (iS15{2}, iS16{8}, rS17{8}, iS18{16}, rS19{512})
 allocation domain : (iS15{2}, iS16{8}, rS17{8}, rS19{512}, iS18{16})
 contiguity: t t n n t
 leaf domain : (iS15{2}, iS16{8}, rS17{8}, iS18{16}, rS19{512})
}
```

gdb backtrace:
```
Thread 1 "nvfuser_tests" hit Breakpoint 1, nvfuser::nvfCheckFail (func=0x555556c69ad0 "getVectorizationBreakPointOfReductionProducer", file=0x555556c68c58 "/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp", line=981, msg="false INTERNAL ASSERT FAILED at \"/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp\":981, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Unexpected p"...) at /opt/pytorch/nvfuser/csrc/exceptions.cpp:266
266         const std::string& msg) {
(gdb) bt
#0  nvfuser::nvfCheckFail (func=0x555556c69ad0 "getVectorizationBreakPointOfReductionProducer", file=0x555556c68c58 "/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp", line=981, 
    msg="false INTERNAL ASSERT FAILED at \"/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp\":981, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Unexpected p"...) at /opt/pytorch/nvfuser/csrc/exceptions.cpp:266
#1  0x000055555584c949 in nvfuser::nvfErrorFail (func=0x555556c69ad0 "getVectorizationBreakPointOfReductionProducer", file=0x555556c68c58 "/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp", line=981, 
    condMsg=0x555556c69cf0 "false INTERNAL ASSERT FAILED at \"/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp\":981, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. ", userMsg="Unexpected producer RF ID: iS14{512}") at /opt/pytorch/nvfuser/csrc/exceptions.cpp:293
#2  0x0000555555ef0b95 in nvfuser::vectorize_helper::getVectorizationBreakPointOfReductionProducer (reduction_consumer=0x7fff3199fb80, reduction_producer=0x7fff31b85480, consumer_innermost_ndims=0)
    at /opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.cpp:981
#3  0x0000555555e8ab4f in nvfuser::getReductionHeuristics (fusion=0x7fff31840100, runtime_info=..., data_cache=0x7fff31ba7a80) at /opt/pytorch/nvfuser/csrc/scheduler/reduction.cpp:1107
#4  0x0000555555ea17c4 in nvfuser::HeuristicSummary::HeuristicSummary (this=0x7fff31ba7a80, fusion=0x7fff31840100, heuristic=nvfuser::ScheduleHeuristic::Reduction, runtime_info=...)
    at /opt/pytorch/nvfuser/csrc/scheduler/registry.cpp:315
#5  0x0000555555f347f2 in std::make_unique<nvfuser::HeuristicSummary, nvfuser::Fusion*&, nvfuser::ScheduleHeuristic, nvfuser::SchedulerRuntimeInfo&> () at /usr/include/c++/11/bits/unique_ptr.h:962
#6  0x0000555555f164e4 in nvfuser::SegmentedFusion::makeInitialSchedulerEntry (this=0x7fff31b87880, sg=0x7fff31acb3c0, runtime_info=...) at /opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp:4347
#7  0x0000555555f166c4 in nvfuser::SegmentedFusion::makeInitialHeuristics (this=0x7fff31b87880, inputs=..., runtime_info=...) at /opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp:4359
#8  0x0000555555aedb9f in nvfuser::FusionKernelRuntime::FusionKernelRuntime (this=0x7fff334d12c0, fusion=std::unique_ptr<nvfuser::Fusion> = {...}, args=..., serde_buffer=0x0, 
    forced_index_type=std::optional<nvfuser::PrimDataType> [no contained value], fusion_id=0, concrete_id=1, runtime_id=0, auto_schedule=true) at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1080
#9  0x0000555555afe027 in std::make_unique<nvfuser::FusionKernelRuntime, std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, decltype(nullptr), std::optional<nvfuser::PrimDataType>&, long&, long&, unsigned long, bool const&>(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >&&, nvfuser::KernelArgumentHolder const&, decltype(nullptr)&&, std::optional<nvfuser::PrimDataType>&, long&, long&, unsigned long&&, bool const&) () at /usr/include/c++/11/bits/unique_ptr.h:962
#10 0x0000555555aec09f in nvfuser::FusionExecutorCache::getKernelRuntimeFor (this=0x7fffffffd250, args=..., forced_index_type=std::optional<nvfuser::PrimDataType> [no contained value])
    at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:817
#11 0x0000555555aea3c9 in nvfuser::FusionExecutorCache::runFusionWithInputs (this=0x7fffffffd250, inputs=..., forced_index_type=std::optional<nvfuser::PrimDataType> [no contained value], 
    selected_device=std::optional<signed char> [no contained value]) at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:533
#12 0x0000555556527c52 in nvfuser::NVFuserTest_Reduction3DConstantIterationDomain_Test::TestBody (this=0x7fff44f50ea0) at /opt/pytorch/nvfuser/test/test_gpu3.cpp:7986
#13 0x0000555556963db1 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x7fff44f50ea0, method=&virtual testing::Test::TestBody(), 
    location=0x555556ee032b "the test body") at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:2612
#14 0x000055555695d869 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x7fff44f50ea0, method=&virtual testing::Test::TestBody(), location=0x555556ee032b "the test body")
    at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:2648
#15 0x0000555556939c56 in testing::Test::Run (this=0x7fff44f50ea0) at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:2687
#16 0x000055555693a771 in testing::TestInfo::Run (this=0x7fff47a820c0) at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:2836
#17 0x000055555693b177 in testing::TestSuite::Run (this=0x7fff48223a00) at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:3015
#18 0x000055555694b69e in testing::internal::UnitTestImpl::RunAllTests (this=0x7fff44ef1a00) at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:5920
#19 0x0000555556964d3e in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x7fff44ef1a00, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x55555694b284 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x555556ee0d78 "auxiliary test code (environments or event listeners)") at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:2612
#20 0x000055555695e933 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x7fff44ef1a00, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x55555694b284 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x555556ee0d78 "auxiliary test code (environments or event listeners)") at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:2648
#21 0x0000555556949c9f in testing::UnitTest::Run (this=0x5555575f80e0 <testing::UnitTest::GetInstance()::instance>) at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest.cc:5484
#22 0x0000555556913b0c in RUN_ALL_TESTS () at /opt/pytorch/nvfuser/third_party/googletest/googletest/include/gtest/gtest.h:2317
#23 0x0000555556913a85 in main (argc=1, argv=0x7fffffffdaf8) at /opt/pytorch/nvfuser/third_party/googletest/googletest/src/gtest_main.cc:64
```

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #1895

In `getVectorizationBreakPointOfReductionProducer`, the existing logic walks through mapped innermost iterdomain on reduction producer to find break_point. However, it doesn't account for case where no innermost iterdomain is mapped (i.e. `consumer_innermost_ndims == 0`) and triggers a false assert.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Comment by naoyam** [comment]
The PR title and actual change don't seem to match...

```
if (producer_innermost_ids.empty()) {
```

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
