### PR TITLE
Update `LoadStoreOp::toString`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
`predicate()` is available only in kernel IR, so we should check container type otherwise we will not be able to print `LoadStoreOp` in a fusion IR.

### CODE REVIEW

**Comment by naoyam** [comment]
Not sure what you mean. 

>  Disallow setting predicate in fusion IR is sufficient to ensure consistency

If the setter is not allowed, why do we need to allow the getter?

**Comment by zasdfgbnm** [comment]
> Not sure what you mean.
> 
> > Disallow setting predicate in fusion IR is sufficient to ensure consistency
> 
> If the setter is not allowed, why do we need to allow the getter?

Because we need the getter to tell me that there is no predicate.

**Comment by naoyam** [comment]
> Because we need the getter to tell me that there is no predicate.

Hmm, I'm a little worried about this change. I think the reason we put the assertion is that in the Fusion IR, there's no concept of the predicate is yet introduced, so semantically it doesn't make sense to query if there's a predicate. In other words, in the Kernel IR, getting `nullptr` from `Expr::predicate()` means the expression has no inline predicate. But in the Fusion IR, what does it mean? Eventually, when lowered to Kernel, it may have an inline predicate or not, but we don't know yet at the Fusion IR stage.

This assertion is just for safety that we won't do any stupid mistake of using `Expr::predicate()` in the Fusion IR, and I think it's a reasonable safety check. Why do you want to remove it?

**Comment by zasdfgbnm** [comment]
Currently,
```
PYTORCH_NVFUSER_DUMP="fusion_ir" ./build/nvfuser_tests --gtest_filter=*FusionAmpereMatmul_CUDA*
```
is failing, because of this assert. It is failing because in `LoadStoreOp::toString` we are doing

```C++
std::string LoadStoreOp::toString(int indent_size) const {
  std::stringstream ss;
  std::string optype = load_store_type2string(opType());
  indent(ss, indent_size) << out()->toString() << "\n";
  indent(ss, indent_size + 1) << " = " << optype << "( " << in()->toString();
  if (predicate()) {
    ss << ", " << std::endl;
    indent(ss, indent_size + 1)
        << std::string(optype.size() + 5, ' ') << predicate()->toInlineString();
  }
  ss << " )\n";
  return ss.str();
}
```
So we can no longer print `LoadStoreOp` inside a fusion IR.

We can of course change `LoadStoreOp::toString` to make it print differently for kernel IR and fusion IR, but I don't think this approach makes more sense compared to just make `predicate()` return a `nullptr` for fusion IR. In my opinion, `predicate()` should tell me there is no predicate regardless of the reason (when I want to know there is no predicate, I don't really care whether it is because this is not a kernel or because this is a kernel whose lowering has not generated the predicate yet).

**Comment by naoyam** [comment]
> We can of course change `LoadStoreOp::toString` to make it print differently for kernel IR and fusion IR, but I don't think this approach makes more sense compared to just make `predicate()` return a `nullptr` for fusion IR. In my opinion, `predicate()` should tell me there is no predicate regardless of the reason (when I want to know there is no predicate, I don't really care whether it is because this is not a kernel or because this is a kernel whose lowering has not generated the predicate yet).

Sure, it's fine in this case since it's just printing and has nothing to do with correctness, but I'm more concerned for more general cases. Why don't we do `if (is-kernel-ir) { print(predicate()}` for now? If it shows up repeatedly, yeah, I'd agree it's tedious, but otherwise, I'd prefer being extra cautious with the assertion.

**Comment by zasdfgbnm** [comment]
> > We can of course change `LoadStoreOp::toString` to make it print differently for kernel IR and fusion IR, but I don't think this approach makes more sense compared to just make `predicate()` return a `nullptr` for fusion IR. In my opinion, `predicate()` should tell me there is no predicate regardless of the reason (when I want to know there is no predicate, I don't really care whether it is because this is not a kernel or because this is a kernel whose lowering has not generated the predicate yet).
> 
> Sure, it's fine in this case since it's just printing and has nothing to do with correctness, but I'm more concerned for more general cases. Why don't we do `if (is-kernel-ir) { print(predicate()}` for now? If it shows up repeatedly, yeah, I'd agree it's tedious, but otherwise, I'd prefer being extra cautious with the assertion.

Yeah, sure, let me update this PR.

**Review by naoyam — APPROVED** [review]
LGTM. Thanks for the update!

**Pull request merged**
