### PR TITLE
Print `PolymorphicValue` and special case `at::Tensor`

### PR DESCRIPTION
**Pull request by crcrpar**
to avoid printing all the elements of Tensor.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Could you copy paste https://github.com/NVIDIA/Fuser/pull/735/files#diff-4c82f4bffe6f0389dc9713b36c9b2b262a0eb9a170b8a9622ab5297b236f0946R258 to this PR and use it here?

**Comment by crcrpar** [comment]
with that PR I think the change I want to see is `debug() << " " << *args[i] << std::endl;` instead of https://github.com/NVIDIA/Fuser/pull/742/files#diff-e72d395ea8a3ab3d2a909dfb3677beac1bbd89336b54ee858867f652b48be4f0L1427. Thus I think it'd be also nice to make the change in 735 and close this PR

**Comment by zasdfgbnm** [comment]
> with that PR I think the change I want to see is `debug() << " " << *args[i] << std::endl;` instead of

Sorry, did you mean to say `debug() << " " << toString(*args[i]) << std::endl;`?

**Comment by crcrpar** [comment]
> > with that PR I think the change I want to see is `debug() << " " << *args[i] << std::endl;` instead of
> 
> Sorry, did you mean to say `debug() << " " << toString(*args[i]) << std::endl;`?

er, yes. you're right

**Comment by zasdfgbnm** [comment]
Changes added in https://github.com/NVIDIA/Fuser/pull/735

**Pull request closed without merging**
