### PR TITLE
NVFUSER_DUMP=fusion_ir_preseg prints out transforms.

### PR DESCRIPTION
**Pull request by wujingyue**
Preseg passes (i.e. MarkAliasesPrepare and AllocationDomainInference) take care of allocation domain propagation. I found it more useful to print out the transforms as well as the math.

### CODE REVIEW

**Comment by wujingyue** [comment]
!test

**Review by naoyam — APPROVED** [review]
While the change itself looks completely fine, why did such many tests fail?

**Comment by wujingyue** [comment]
Looks like a testing infra's problem: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/124847021

I'll try to run the tests again...

**Comment by wujingyue** [comment]
!test

**Pull request merged**
