### PR TITLE
patching API GUARD

### PR DESCRIPTION
**Pull request by jjsjann123**
patching API version guard so we'll still be able to build against older pytorch version.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Review by naoyam — APPROVED** [review]

**Review by xwang233 — COMMENTED** [review]
Is it a duplicate for TORCH_VERSION_GREATER macro? https://github.com/NVIDIA/Fuser/pull/1752/files#diff-5df7a5b64ccec9873e9f1a49bb8026390b8671b92aa0f8671b3dd540034cf8acR391

**Comment by jjsjann123** [comment]
> Is it a duplicate for TORCH_VERSION_GREATER macro? https://github.com/NVIDIA/Fuser/pull/1752/files#diff-5df7a5b64ccec9873e9f1a49bb8026390b8671b92aa0f8671b3dd540034cf8acR391

Yes. Let me try to clean it up then.

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
stable just passed. This is looking promising :)

**Pull request merged**
