### PR TITLE
Cleanup fusion transformations printting

### PR DESCRIPTION
**Pull request by zasdfgbnm**
When reading Jacob's slides this morning, I feel it would be more convenient to read the transformations if leaf domains are also printed. Besides, `IrTransformPrinter::printTransforms` needs cleanup.

New print
```C++
T5_l[ iblockIdx.x23{( ceilDiv(i0, 128) )}, iblockIdx.y25{( ceilDiv(i3, 128) )}, rS27{( ceilDiv(i2, 32) )}, rS77{( ceilDiv(32, 16) )}, ithreadIdx.z69{( ceilDiv(128, 64) )}, ithreadIdx.y71{( ceilDiv(128, 64) )}, iS73{( ceilDiv(64, 16) )}, iS75{( ceilDiv(64, 8) )}, iMMA153{( ceilDiv(16, 8) )}, ithreadIdx.x157{( 8 * ( ceilDiv(8, 2) ) )}, iMMA156{2}, rMMA78{16} ] ca_pos( 2 ) produce_pos( 6 )
 root domain : (iS10{i0}, iS11{i3}, rS12{i2})
 contiguity: t t t
  Split: iS10{i0} by factor 128 -> iblockIdx.x23{( ceilDiv(i0, 128) )}, iS24{128}, start offset: 0, stop offset: 0
  Split: iS11{i3} by factor 128 -> iblockIdx.y25{( ceilDiv(i3, 128) )}, iS26{128}, start offset: 0, stop offset: 0
  Split: rS12{i2} by factor 32 -> rS27{( ceilDiv(i2, 32) )}, rS28{32}, start offset: 0, stop offset: 0
  Split: rS28{32} by factor 16 -> rS77{( ceilDiv(32, 16) )}, rMMA78{16}, start offset: 0, stop offset: 0
  Split: iS24{128} by factor 64 -> ithreadIdx.z69{( ceilDiv(128, 64) )}, iS70{64}, start offset: 0, stop offset: 0
  Split: iS26{128} by factor 64 -> ithreadIdx.y71{( ceilDiv(128, 64) )}, iS72{64}, start offset: 0, stop offset: 0
  Split: iS70{64} by factor 16 -> iS73{( ceilDiv(64, 16) )}, iS74{16}, start offset: 0, stop offset: 0
  Split: iS72{64} by factor 8 -> iS75{( ceilDiv(64, 8) )}, iS76{8}, start offset: 0, stop offset: 0
  Split: iS74{16} by factor 8 -> iMMA153{( ceilDiv(16, 8) )}, iS154{8}, start offset: 0, stop offset: 0
  Split: iS76{8} by factor 2 -> iS155{( ceilDiv(8, 2) )}, iMMA156{2}, start offset: 0, stop offset: 0
  Merge: iS154{8} and iS155{( ceilDiv(8, 2) )} -> ithreadIdx.x157{( 8 * ( ceilDiv(8, 2) ) )}
 leaf domain : (iblockIdx.x23{( ceilDiv(i0, 128) )}, iblockIdx.y25{( ceilDiv(i3, 128) )}, rS27{( ceilDiv(i2, 32) )}, rS77{( ceilDiv(32, 16) )}, ithreadIdx.z69{( ceilDiv(128, 64) )}, ithreadIdx.y71{( ceilDiv(128, 64) )}, iS73{( ceilDiv(64, 16) )}, iS75{( ceilDiv(64, 8) )}, iMMA153{( ceilDiv(16, 8) )}, ithreadIdx.x157{( 8 * ( ceilDiv(8, 2) ) )}, iMMA156{2}, rMMA78{16})
```

### CODE REVIEW

**Comment by jacobhinkle** [comment]
Good idea to explicitly label the leaf domain. Now it is printed twice. Maybe would be neater to remove the printing of the tensordomain in first line? That's tougher since it would mean hacking toString or manually printing the remaining parts of the TensorView.

**Comment by zasdfgbnm** [comment]
Yes, it is printed twice, but is this a problem? Why not just let it print twice?

**Comment by jacobhinkle** [comment]
> Why not just let it print twice?

No good reason besides avoiding redundancy. The cleanup changes look good and this makes it more clear that what we're seeing is a leaf domain.

**Review by jacobhinkle — APPROVED** [review]
LGTM

**Pull request merged**
