### PR TITLE
version bump to 0.2.0

### PR DESCRIPTION
**Pull request by jjsjann123**
remove patch_nvfuser utils, as we are dropping support for pytorch 2.1.
bumping version to 0.2.0

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
failing CI is just flaky. Nice catch on the version bump advisory. :clap: @xwang233

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Review by kevinstephano — APPROVED** [review]
LGTM

**Comment by jjsjann123** [comment]
I'm ok with the test as-is I'll merge this PR.

**Pull request merged**
