### PR TITLE
Revert "Compile fusion segments in parallel"

### PR DESCRIPTION
**Pull request by naoyam**
Reverts NVIDIA/Fuser#130

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
What's wrong with https://github.com/NVIDIA/Fuser/pull/130?

**Comment by naoyam** [comment]
Lots of tests are failing with Debug build:

```
[ RUN      ] NVFuserTest.DynamicTransform3_CUDA
unknown file: Failure
C++ exception with description "device_or_default(device_opt).type() == DeviceType::CPU INTERNAL ASSERT FAILED at "/raid/nmaruyama/debug1/pytorch/aten/src/ATen/EmptyTensor.cpp":280, please report a bug to PyTorch.
Exception raised from empty_strided_cpu at /raid/nmaruyama/debug1/pytorch/aten/src/ATen/EmptyTensor.cpp:280 (most recent call first):
frame #0: <unknown function> + 0xf3cc0 (0x7f4c4f0dbcc0 in /raid/nmaruyama/debug1/pytorch/build/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x48 (0x7f4c61bd2ca8 in /raid/nmaruyama/debug1/pytorch/build/lib/libtorch_cpu.so)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x62 (0x7f4c4f0dacb2 in /raid/nmaruyama/debug1/pytorch/build/lib/libc10.so)
frame #3: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x9c (0x7f4c4f0d8d4c in /raid/nmaruyama/debug1/pytorch/build/lib/libc10.so)
```

**Comment by zasdfgbnm** [comment]
Let me try to repro, I don't see any failure in `--debinfo`.

**Comment by rdspring1** [comment]
It is because of https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/EmptyTensor.cpp#L280. It is only a pytorch debug-build check.

I think the fix is to use at https://github.com/NVIDIA/Fuser/blob/main/csrc/executor_kernel_arg.cpp#L638
```
  auto meta_tensor = at::detail::empty_strided_meta(
      sizes,
      strides,
      dtype,
      c10::nullopt,
      c10::Device(c10::DeviceType::Meta, 0),
      c10::nullopt);
  arguments_.push_back(getAbstractTensorArg(at::Tensor(meta_tensor)));
```

**Comment by naoyam** [comment]
The assertion is only checked with Debug. 

```
 TORCH_INTERNAL_ASSERT_DEBUG_ONLY(device_or_default(device_opt).type() == DeviceType::CPU);
```

**Comment by zasdfgbnm** [comment]
I still can not repro. Based on the discussion, we need to debug build PyTorch as well?

**Comment by naoyam** [comment]
> It is because of https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/EmptyTensor.cpp#L280. It is only a pytorch debug-build check.
> 
> I think the fix is to use at https://github.com/NVIDIA/Fuser/blob/main/csrc/executor_kernel_arg.cpp#L638
> 
> ```
>   auto meta_tensor = at::detail::empty_strided_meta(
>       sizes,
>       strides,
>       dtype,
>       c10::nullopt,
>       c10::Device(c10::DeviceType::Meta, 0),
>       c10::nullopt);
>   arguments_.push_back(getAbstractTensorArg(at::Tensor(meta_tensor)));
> ```

Is this an easy fix? I'll close this revert PR then.

**Comment by rdspring1** [comment]
https://github.com/NVIDIA/Fuser/pull/377 fixed the tests for me. I'll run all the tests now.
@naoyam Can you try on your build?

**Comment by naoyam** [comment]
Works for me now. Thanks for the quick fix!

**Pull request closed without merging**
