### PR TITLE
Prioritize using zero index

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/NVIDIA/Fuser/issues/2763

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by naoyam** [comment]
Could you add a short description why this is a problem and how the change fixes it?

**Comment by naoyam** [comment]
> Could you add a short description why this is a problem and how the change fixes it?

Never mind, I saw your comment on the issue page.

**Review by naoyam — APPROVED** [review]
LGTM

**Review by jacobhinkle — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
