### PR TITLE
Remove shift

### PR DESCRIPTION
**Pull request by naoyam**
Removed `shift`-related code, including `ShiftOp` and `GatherOp` IR nodes and their tests.

The existing implementation is not used and is quite dated. If these ops would ever need to be supported, we would want to think about these ops as IterDomain ops.

### CODE REVIEW

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
!build --diff --diff-bench --pybench

**Comment by naoyam** [comment]
!build --diff --diff-bench --pybench

**Comment by naoyam** [comment]
The codegen diffs seem to be just variable name changes.

**Review by zasdfgbnm — APPROVED** [review]

**Pull request merged**
