### PR TITLE
Overlap: replace at::matmul_out by mul_out+sum_out in ATen implementation of rs-based pipelining

### PR DESCRIPTION
**Pull request by samnordmann**
`at::matmul_out` seems to allocate intermediate buffer, resulting in cudaMalloc with significant overheads in the execution trace. To have better control on allocation, we used those two unfused ATen ops, i.e., pointiwise multiply and sum reduction.

Stacked on top of
- #2665.

### CODE REVIEW

**Comment by samnordmann** [comment]
!build

**Comment by naoyam** [comment]
@samnordmann Replacing MMA with mul-sum doesn't seem ideal. I think we should continue investigating why cudaMalloc is involved. Can you create an issue with a repro?

**Comment by samnordmann** [comment]
> @samnordmann Replacing MMA with mul-sum doesn't seem ideal. I think we should continue investigating why cudaMalloc is involved. Can you create an issue with a repro?

Here is the issue:
https://github.com/NVIDIA/Fuser/issues/2673

Let me know if you want a more minimal reproducer which is fully torch contained

**Comment by samnordmann** [comment]
We will keep using `matmul_out` according to the results of #2673

**Pull request closed without merging**
