### PR TITLE
Add new test `HopperRS.MultipleTile`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Adding a new test checking stride inference, reqiures https://github.com/NVIDIA/Fuser/pull/3002

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
LGTM

**Comment by naoyam** [comment]
The build failure seems real?

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by jacobhinkle — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
Test failures seems real. Looks like some of my latest changes in https://github.com/NVIDIA/Fuser/pull/3002 breaks this.

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
