### PR TITLE
rename all nvfuser benchmarks start with NvFuserScheduler_

### PR DESCRIPTION
**Pull request by liqiangxl**
The CI is filtering nvfuser benchmark cases with `NvFuserScheduler_*`, however the names of some nvfuser cases are not started with `NvFuserScheduler_`. This PR adds `NvFuserScheduler_` to these cases.

### CODE REVIEW

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM. Some of the benchmarks are not really about the scheduler. That's fine for now, but we should reconsider naming when we move the benchmarks to Python. CC: @Priya2698

**Comment by liqiangxl** [comment]
!build

**Pull request merged**
