### PR TITLE
Pass allow_self_mapping to IterDomainGraph.

### LINKED ISSUE #1791: IdModel failed on valid fusions (even with allow_self_mapping on).
```
$ git fetch origin wjy/idmodel
$ git checkout wjy/idmodel
$ _bn && bin/nvfuser_tests --gtest_filter=IdModelTest*
...
[----------] 15 tests from IdModelTest (192 ms total)

[----------] Global test environment tear-down
[==========] 15 tests from 1 test suite ran. (192 ms total)
[  PASSED  ] 13 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] IdModelTest.SomeButNotAllArePermuted
[  FAILED  ] IdModelTest.PermutedDifferently

 2 FAILED TESTS
```

For your convenience, the two tests are [here](https://github.com/NVIDIA/Fuser/blob/wjy/idmodel/test/test_id_model.cpp#L923-L958).

### PR DESCRIPTION
**Pull request by wujingyue**
Validation fails otherwise. Fixes #1791.

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by naoyam** [comment]
I'm not sure what we should do here. The validation failure is expected. Skipping the validation may be fine for some cases, but it won't solve the limitation of self-mapped domains.

**Comment by wujingyue** [comment]
Note that IterDomainGraph, the reference implementation, already has the `allow_self_mapping` flag. All I did is to make sure that flag is consistent with IdModel's `allow_self_mapping`. Does that make any sense to you?

**Comment by naoyam** [comment]
OK, it makes sense. Another workaround would be just skipping the validation, which would be eventually removed when `ComputeAtMap` is completely replaced by `IdModel`.

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
