### PR TITLE
TMA store to global memory after stmatrix

### PR DESCRIPTION
**Pull request by protonu**
Modified the stmatrix to store to global memory using TMA store.

### CODE REVIEW

**Comment by protonu** [comment]
!build

**Comment by zasdfgbnm** [comment]
Could we keep this unit test unit? We can add a separate test with stmatrix + TMA, and keep this test as small as just stmatrix. One interesting thing to study in that separate stmatrix test is, are we currently accessing smem with bank conflict? If yes, is our `getBankConflictInfo` capable of catching it? And how to swizzle it in a way that is consistent with TMA?

**Comment by protonu** [comment]
@zasdfgbnm  Thanks - great points! I was trying to not increase the number of tests we have. How about I add this to the single tile Mma test; where we can use `stmatrix` in addition to TMA load/store. Then as a next step I could investigate bank conflicts.

**Comment by zasdfgbnm** [comment]
> @zasdfgbnm Thanks - great points! I was trying to not increase the number of tests we have. How about I add this to the single tile Mma test; where we can use `stmatrix` in addition to TMA load/store. Then as a next step I could investigate bank conflicts.

Sounds reasonable to me. Make sure don't add a new MMA test because it takes really. Could we add it to `SingleTileWithTMALoadStore`?

**Comment by protonu** [comment]
This work is no longer needed - we'll create a separate test with mma + stmatrix + tma

**Pull request closed without merging**
