### PR TITLE
Remove Volta matmul support

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by drzejan2 — APPROVED** [review]
With this change the support for Volta architecture will be dropped - will there be a architecture support matrix?

**Comment by zasdfgbnm** [comment]
> With this change the support for Volta architecture will be dropped - will there be a architecture support matrix?

I think we mainly care about Ampere and Hopper. But supporting Turing is not much additional work, so also Turing.

**Pull request merged**
