### PR TITLE
Avoid symbolic output extent in newOutputDomain

### LINKED ISSUE #357: Symbolic iter domains should not exact map when aligned
I am trying to make the following test pass:
```c++
// Test dynamic pad followed by broadcast resolution
TEST_F(NVFuserTest, DynamicPadBroadcast_CUDA) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  TensorView* tv1 = makeSymbolicTensor(2);
  fusion.addInput(tv1);

  // 2d axis order here is YX
  auto ypad = IrBuilder::create<Int>();
  fusion.addInput(ypad);
  auto xpad = IrBuilder::create<Int>();
  fusion.addInput(xpad);

  // two-way resizes to cut square tv down to broadcastable size in either axis
  auto tv0_pad = pad(tv0, {fusion.zeroVal(), xpad, fusion.zeroVal(), ypad});

  // This will potentially resolve the y or x broadcast
  auto p = mul(tv0_pad, tv1);
  fusion.addOutput(p);

  fusion.printMath();
/*
Inputs:                                                                                                                          
  T0_g[ iS0{i0}, iS1{i2} ], float                                                                                                
  T1_g[ iS2{i3}, iS3{i4} ], float                                                                                                
  i5, int64_t                                                                                                                    
  i6, int64_t                                                                                                                    
Outputs:                                                                                                                         
  T3_g[ iS8{( i0 + i5 )}, iS9{( i2 + i6 )} ], float                                                                              
                                                                                                                                 
%kernel_math {                                                                                                                   
T2_l[ ?S5{( i0 + i5 )}rf, ?S7{( i2 + i6 )}rf ]                                                                                   
   = pad( T0_g[ iS0{i0}, iS1{i2} ], {0, i5, 0, i6} )                                                                             
T3_g[ iS8{( i0 + i5 )}, iS9{( i2 + i6 )} ]                                                                                       
   = T2_l[ ?S5{( i0 + i5 )}rf, ?S7{( i2 + i6 )}rf ]                                                                              
   * T1_g[ iS2{i3}, iS3{i4} ];                                                                                                   
}
*/

  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn({5, 5}, options);
  at::Tensor at_y = at::randn({5, 5}, options);

  std::vector<c10::IValue> aten_inputs({at_x, at_y, 0, 0});
  std::vector<at::Tensor> outputs;

  // shrink first axis so that the multiplication resolves a broadcast
  aten_inputs[2] = -4;
  aten_inputs[3] = 0;
  outputs = fusion_executor_cache.runFusionWithInputs(aten_inputs);
  testValidate(fusion_executor_cache.fusion(), outputs, aten_inputs, {at_x[0].unsqueeze(0) * at_y}, __LINE__, __FILE__);
}
```
During concretization, we try and evaluate the extent of dynamic resize. In this case, we want to evaluate extents of `?S5{( i0 + i5 )}rf` and `?S7{( i2 + i6 )}rf`. To compute these we use an expression evaluator, which actually throws an error:
> C++ exception with description "known_size == this_size INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/expr_evaluator.cpp":210, please report a bug to PyTorch. Conflicting sizes: 5, 1 

The following initial values are bound correctly based on inputs:
> Binding 5 to i0
> Binding 5 to i2
> Binding 5 to i3
> Binding 5 to i4
> Binding -4 to i5
> Binding 0 to i6

The error comes in `ExpressionEvaluator::propagateBoundValuesThroughExactMaps` when evaluating `i0 + i5` which evaluates to 1 but has `known_size == 5`. I believe this is because earlier, the multiplication sees a `Symbolic` domain aligned with an `Iteration` domain and interprets this as an exact map. I think the fix is to adjust the exact map condition to never set an exact mapping to/from `Symbolic` domains.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #357

There are a combination of issues address by this PR. First, as noted in the issue, we should not exact map between `Symbolic` domains. However, there is still an issue where the output extent, computed at Fusion definition, is sometimes set equal to the symbolic extent even though that extent might concretize to 1 and then become a resolved broadcast. In those cases we should either use any `Iteration` extents if available, or if we have an unambiguous `Symbolic` extent, we can use it.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
I've encountered an interesting limitation. For a dynamic resize resulting in a broadcast, we may have a concretized root domain of type `Iteration` that's resized to a `Broadcast` rfactor domain. For example, as of now the example in #357 concretizes (properly?) to
```
Inputs:
  T0_g[ iS0{i0}, iS1{i2} ], float
  T1_g[ iS2{i3}, iS3{i4} ], float
  i5, int64_t
  i6, int64_t
Outputs:
  T3_g[ iS8{i3}, iS9{i4} ], float
  T2_g[ bS10{( i0 + i5 )}rf, iS11{( i2 + i6 )}rf ], float

%kernel_math {
T2_g[ bS10{( i0 + i5 )}rf, iS11{( i2 + i6 )}rf ]
   = pad( T0_g[ iS0{i0}, iS1{i2} ], {0, i5, 0, i6} )
T3_g[ iS8{i3}, iS9{i4} ]
   = T2_g[ bS10{( i0 + i5 )}rf, iS11{( i2 + i6 )}rf ]
   * T1_g[ iS2{i3}, iS3{i4} ];
```
This currently fails when building `ComputeAtMap` while building the structure used to define concrete IDs, `ConcretizedBroadcastDomains` at this check: https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/analysis/trivial_broadcast.cpp#L99. I believe this assumes that a broadcast will come from a `BroadcastOp`, and tries to map every `Broadcast` root ID to its "original" root ID, meaning the ID in the root of the input to a `BroadcastOp`. In the case of `Resize` we don't have a separate TV op representing the broadcast, so to satisfy this assumption we would need to insert an op at concretization to separately broadcast after concretizing all resized `IterDomain`s as `Iteration`. That's a bit invasive, so I'm checking to see if in this case it might be safe to use the resize itself as the concrete ID.

**Comment by jacobhinkle** [comment]
Note that `reshape` does not trigger this error because during concretization/static reshape, broadcasts are detected and actual `broadcast` ops are inserted. This may be the way to go; I can detect broadcast output domains that come from `Resize` op while processing a TV and ideally _remove_ them then insert the broadcast on that TV. I'm not exactly sure how best to remove that ID without it being a `Broadcast`. One option is to `Merge` that ID with its neighbor assuming it has any. I will continue thinking about this.

**Comment by naoyam** [comment]
It seems to me that the problem lies in `ConcretizedBroadcastDomains`. If we extend it to handle broadcast IDs produced by IterDomain expressions, should the problem be fixed?

**Comment by jacobhinkle** [comment]
> If we extend it to handle broadcast IDs produced by IterDomain expressions, should the problem be fixed?

 I believe so.

**Comment by naoyam** [comment]
OK, then I think that would be preferred over adding broadcast ops. Let me know if you need any help.

**Pull request closed without merging**
