### PR TITLE
clean normalization_outer

### PR DESCRIPTION
**Pull request by liqiangxl**
similar to #923
(1) Transformed private static functions in the OuterPersistentKernelScheduler class into utility functions within an anonymous namespace.
(2) Removed checks/calculations that are unrelated to outer persistent scheduler.

### CODE REVIEW

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
