### PR TITLE
add unroll to pointwise scheduler

### PR DESCRIPTION
**Pull request by liqiangxl**
**What is in this PR?** This PR allows unroll on top of vectorization in pointwise scheduler.
**Why want to do this?** See [doc](https://docs.google.com/document/d/14GFuGodBatD-g7_Ws--4QEjPZGAAPOPZOhjrETX-gX8/edit#heading=h.mp3o4wf6epgb) for details.
Unroll may save loaded data when there is outer broadcast Tv in the fusion. For example `y = gelu(x + bias)`
where x is `T0[i1, i2]`, and bias is `T1[b, i3]`. For this case, 2D pointwise scheduler is used, when `unroll = 2` in outer dim, we can save one load of T1 due to the broadcast. For T1 we only need to load one row:
```
 Array<__half, 8, 8> T18;
  T18.set(__half(0));
  if (b3) {
    loadGlobalToLocal<__half, /*vec_size=*/8, /*is_volatile=*/false, CacheOp::AllLevels>(&T18[0],  &T1[(i0 + i1)]);
  }
```
For T0 we need to load two rows:
```
   #pragma unroll
    for(nvfuser_index_t i6 = 0; i6 < 2; ++i6) {
      loadGlobalToLocal<__half, /*vec_size=*/8, /*is_volatile=*/false, CacheOp::Streaming>(&T17[(8 * i6)],  &T0[(i2 + (T0.logical_size[1LL] * (i6 + nvfuser_zero)))]);
    }
```
**Follow ups:**  This PR only enables this feature, but not used in the heuristics. So, there is no change in the generated code. Further work is tuning heuristics to allow vectorization & unroll at the same time for better performance.

### CODE REVIEW

**Comment by liqiangxl** [comment]
!build --diff

**Comment by liqiangxl** [comment]
!build --diff

**Comment by liqiangxl** [comment]
!build --diff

**Comment by liqiangxl** [comment]
Sanitinzer failures are not realated to this PR. Also can't reproduce locally.
```
00:38:10 [ RUN      ] ScatterGatherTest.TorchGatherSumAdd
00:38:10 To reproduce: NVFUSER_TEST_RANDOM_SEED=1727804883 NVFUSER_TEST_ATEN_RANDOM_SEED=0 nvfuser_tests --gtest_filter='ScatterGatherTest.TorchGatherSumAdd'
00:38:10 unknown file: Failure
00:38:10 C++ exception with description " INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/tests/cpp/validator.cpp":110, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
00:38:10 
00:38:10 Validation error in output 0 on line 296 in file /opt/pytorch/nvfuser/tests/cpp/test_scatter_gather.cpp.
00:38:10   Detected max abs error of: 5.72205e-06
00:38:10     absolute tolerance was set to 4.4778e-06
00:38:10     and relative tolerance set to 4.4778e-08
```

**Comment by liqiangxl** [comment]
Hi @xwang233, do you have any suggestions about this [CI](https://nv/e2E/114153076) failure? I got Segmentation fault without saying which test fails.
```
00:38:04 [97f0e8df8e72:556  :0:556] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x18)
00:38:04 ==== backtrace (tid:    556) ====
00:38:04  0 0x0000000000042520 __sigaction()  ???:0
00:38:04  1 0x0000000000411613 cudbgMain()  ???:0
00:38:04  2 0x00000000000752b9 ???()  /usr/local/cuda-12.6/compute-sanitizer/libsanitizer-public.so:0
00:38:04  3 0x000000000007fb8c ???()  /usr/local/cuda-12.6/compute-sanitizer/libsanitizer-public.so:0
00:38:04  4 0x000000000007fb69 ???()  /usr/local/cuda-12.6/compute-sanitizer/libsanitizer-public.so:0
00:38:04  5 0x00000000000806b1 ???()  /usr/local/cuda-12.6/compute-sanitizer/libsanitizer-public.so:0
00:38:04  6 0x000000000007fa52 ???()  /usr/local/cuda-12.6/compute-sanitizer/libsanitizer-public.so:0
00:38:04  7 0x0000000000045495 secure_getenv()  ???:0
00:38:04  8 0x0000000000045610 exit()  ???:0
00:38:04  9 0x0000000000029d97 __libc_init_first()  ???:0
00:38:04 10 0x0000000000029e40 __libc_start_main()  ???:0
00:38:04 11 0x000000000034c795 _start()  ???:0
00:38:04 =================================
```

**Comment by xwang233** [comment]
Seems to be some teardown issue and looks safe to me. I restarted the job.

**Review by rdspring1 — APPROVED** [review]
LGTM

**Pull request merged**
