### PR TITLE
Add standalone build CI

### PR DESCRIPTION
**Pull request by zasdfgbnm**
I think it would be convenient to know the build result without having to `!build`.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
I thought building nvfuser is almost as fast as real time, until I added this new pipeline. How can it be so slow?😟😟😟😟😟
Do we have: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners ?

**Comment by zasdfgbnm** [comment]
Unfortunately, this CI does not run as fast as I expected. But I think it is still useful.

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Review by rdspring1 — APPROVED** [review]
LGTM. Do we want to make this a mandatory check?

**Review by jjsjann123 — APPROVED** [review]
:shipit:

**Pull request merged**
