### PR TITLE
fix FusionReshapeMagicSchedule6_CUDA on H100

### PR DESCRIPTION
**Pull request by liqiangxl**
trivial fix for [ FAILED ] NVFuserTest.FusionReshapeMagicSchedule6_CUDA at #301 
Afther this PR, all the remaining failures on H100 are validation errors and should be fixed by syncthreads.

### CODE REVIEW

**Comment by naoyam** [comment]
The test fails because the problem size is too small for H100? If so, can we adjust the size based on the device properties?

**Comment by liqiangxl** [comment]
> The test fails because the problem size is too small for H100? If so, can we adjust the size based on the device properties?

Yes. I adjusted to 1024 x 1024 instead of sm_count x 128, just to avoid further change of threads per block in the heuristics. The number should be safe for several years.

**Comment by naoyam** [comment]
Have you adjusted the size already? Is the test working fine now?

**Comment by liqiangxl** [comment]
> Have you adjusted the size already? Is the test working fine now?

This is weired. I don't know why this PR was closed. reopened it.

**Review by csarofeen — APPROVED** [review]
LGTM

**Pull request merged**
