### PR TITLE
Variable name remapping to reduce string compare failure

### PR DESCRIPTION
**Pull request by zasdfgbnm**
I am tired of updating the string compare tests. So I remap variable names to make generated code more stable.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by naoyam** [comment]
One slight concern is this could hide accidental code changes. For example, we might accidentally introduce some non-deterministic code, which would then cause variable names fluctuate. We should fix such non determinism, but it would be hidden by this PR, right?

I don't think this is a big concern, though. As long as non determinism manifests not just as variable name changes but also as some other changes, we should be able to detect it.

**Comment by zasdfgbnm** [comment]
> One slight concern is this could hide accidental code changes. For example, we might accidentally introduce some non-deterministic code, which would then cause variable names fluctuate. We should fix such non determinism, but it would be hidden by this PR, right?
> 
> I don't think this is a big concern, though. As long as non determinism manifests not just as variable name changes but also as some other changes, we should be able to detect it.

Yes, you are right. I agree with such concern. I think this is a tradeoff of whether we want to take the pain of having to update these tests and being unable to easily diff the kernels across PR vs whether we want to be strict on determinism. I prefer to be convenient, because expr simplifier is being adopted in more and more subsystems, and such adoption will make the string compare test to be more likely to fail. If we take this convenience, in the future, we can be more comfortable in writing more string compare tests, and these new string compare tests might also increase safety generally.

**Comment by zasdfgbnm** [comment]
BTW, this would also increase the readability of the generated code. It is easy for us to see `i15` and find where it is defined and used, compared to `i15608`.

**Comment by naoyam** [comment]
Yeah, I agree. This is a better tradeoff.

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
