### PR TITLE
Do not bother propagating vectorize parallel types to transformed producers

### PR DESCRIPTION
**Pull request by naoyam**
I believe this is no longer necessary as the index map is propagated from the loop indexing, which is built using the consumer parallel types.

Originally done in #242

### CODE REVIEW

**Review by zasdfgbnm — APPROVED** [review]

**Comment by naoyam** [comment]
No test failure. Benchmarks result in the exactly same generated code.

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
Everything seems fine both on A100 and V100.

**Comment by naoyam** [comment]
!build

**Pull request merged**
