### PR TITLE
Associate each fusion cache with its local rank in distributed setting.

### PR DESCRIPTION
**Pull request by rdspring1**
### Problem:
Currently, automatic serialization saves a single cache regardless of the number of devices. In a distributed setting, each process restores its fusion cache from the same common workspace. However, this workspace only contains the CUDA kernels for a single device. The remaining processes must recompile the kernels for their devices.

### Solution:
A separate process is created for each device with `ddp` or `fsdp` and each process contains a separate `FusionCache`. This PR associates each fusion cache with its local rank in a distributed setting, allowing automatic serialization to create a separate workspace for each device. During deserialization, each process loads the workspace associated with its local rank.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by jjsjann123** [comment]
sorry for jumping on this late. looks like we now have conflicts on this PR.

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Pull request merged**
