### PR TITLE
Consolidate benchmarking and functional tests into 2 high level directories for both python and C++

### PR DESCRIPTION
**Pull request by kevinstephano**
I am consolidating our tests and benchmarks under two high level directories such that we don't have separate high level directories for C++ and Python tests and benchmarks.  I am also moving the `kernel_db` and `python_frontend` testing under high level test directory from where they lived in `csrc`.  

```
benchmarks/python/
benchmarks/cpp/
tests/python/
tests/cpp/
```

This PR addresses Issue #1926.

### CODE REVIEW

**Comment by kevinstephano** [comment]
!build

**Comment by jjsjann123** [comment]
```
thunder/tests/test_cudnn_executor.py::[1mtest_vjp_correctness_sdpa_cudnnex_manual_grad_forward_scaled_dot_product_attention_nvfuser_cuda_float16[0m - AssertionError: Tensor-likes are not close!
```

^^^ this failure seems to be unrelated.

```
ERROR: file or directory not found: python_tests/test_normalization.py
ERROR: file or directory not found: python_tests/pytest_ops.py
```
Meanwhile, we need to update the CI script to run the right tests.

That's also apparently less test scripts than what we have currently under python_tests. So I wonder what's with our CI script?

**Review by jjsjann123 — APPROVED** [review]
I'm stamping this change and will let @xwang233 patch up the CI part.

**Comment by xwang233** [comment]
!build

**Comment by xwang233** [comment]
!build

**Comment by xwang233** [comment]
I think this is good to go now. Internal CI scripts have been updated. cc @kevinstephano @jjsjann123

**Comment by jjsjann123** [comment]
CI looks good. the only failing one I think is not nvfuser related. I'm merging this.

**Pull request merged**
