### PR TITLE
cache query patch

### PR DESCRIPTION
**Pull request by jjsjann123**
`_exist_schedule` forgot to return the value, ended up with each execution iteration re-schedule the same fusion.

existing python tests needs to clear cache. Since we use input look up for cache key, which doesn't distinguish scalar value changes.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

**Review by rdspring1 — APPROVED** [review]
LGTM.

Does this get rid of the `Warning: You are overwriting the current user schedule for a definition!` message?

**Comment by jjsjann123** [comment]
> LGTM.
> 
> Does this get rid of the `Warning: You are overwriting the current user schedule for a definition!` message?

Yep it did. I only notice this after seeing that warning and got suspicious about it.

**Comment by jjsjann123** [comment]
cc'ing @xwang233 could you remind me of what's running inside the `jit_python_bc_advisory` tests? Is it taking the cpp code base and running with testing scripts from main?

That would explain the failure....

**Comment by xwang233** [comment]
> cc'ing @xwang233 could you remind me of what's running inside the `jit_python_bc_advisory` tests? Is it taking the cpp code base and running with testing scripts from main?
> 
> That would explain the failure....

`jit_python_bc_advisory` runs python script from the merge base of your PR and main, on your PR build, to detect any python API changes. If there are changes, you should modify the version.txt file and bc_advisory job will be skipped.

**Pull request merged**
