### PR TITLE
Move from `unittests` to `pytest` in all `tests/python` files

### PR DESCRIPTION
**Pull request by Priya2698**
This PR removes instances of `unittest` to consistently use `pytest`.
Also, modifies the test files to be invoked directly through `pytest` for consistency in CI.

### CODE REVIEW

**Review by rdspring1 — COMMENTED** [review]
LGTM

**Review by rdspring1 — APPROVED** [review]

**Comment by Priya2698** [comment]
@xwang233 did you already commit the changes in the CI? I can run a pipeline then.

**Comment by xwang233** [comment]
> @xwang233 did you already commit the changes in the CI? I can run a pipeline then.

I was in a meeting. Just merged the changes in CI script. Feel free to start a new pipeline then.

**Comment by Priya2698** [comment]
!build --serde

**Comment by Priya2698** [comment]
!build --serde

**Pull request merged**
