### PR TITLE
Bind TensorMetaData to PrecomputedValues

### PR DESCRIPTION
**Pull request by jacobhinkle**
This was found when implementing #2714. We currently do not bind TensorMetaData for input tensors to PrecomputedValues. This means we cannot evaluate expressions that contain them, which can lead to errors. This PR binds these metadata structs, which I think is the expected behavior.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]

**Comment by jacobhinkle** [comment]
I believe the test failures are due to printing, which is fixed in #2810

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
I am currently seeing failures since `NaiveValueMachine` is being asked to compute ops it had previously not needed to. I think the fix is simply to implement the missing ops, since this should be a more efficient path so the fact it's getting more exercise is probably a good thing.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Pull request merged**
