### PR TITLE
make `patch-nvfuser` verbose for debugging

### PR DESCRIPTION
**Pull request by Borda**
It will help for the eventual debugging of this process.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
LGTM.

@xwang233 we might also try to import after patching the binaries and report an error if the patch didn't work.

**Comment by xwang233** [comment]
>try to import after patching the binaries and report an error if the patch didn't work

Do you want `patch-nvfuser` script to also do a check and see if the patched version works?

**Comment by Borda** [comment]
> Do you want `patch-nvfuser` script to also do a check and see if the patched version works?

yes, that would make sense to me...

**Comment by xwang233** [comment]
We need to make sure we don't `import torch` or `import nvfuser` before the patch.

I'm a bit worrying to "hot patch" the library within the same python process and then try to import it and see if it works.

**Comment by Borda** [comment]
> We need to make sure we don't `import torch` or `import nvfuser` before the patch.

maybe we can insert some code to `__init__` and patch it to be called only once...
or explore the following post-setup alternative - [Post-install script with Python setuptools](https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools)

**Comment by Borda** [comment]
@jjsjann123 @zasdfgbnm seems all is :green_circle:

**Pull request merged**
