### PR TITLE
Print duration as seconds for better error message.

### PR DESCRIPTION
**Pull request by wujingyue**
The test failed
[once](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/116949080/viewer), but it's unclear from the error message how off the expectations are.

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Review by samnordmann — COMMENTED** [review]
1) I am looking for the first time at how this test is implemented and I don't think it is relevant. Passing/failing the test is neither a necessary nor sufficient condition for the barrier's success/failure. The fact that it failed [here](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/116949080/viewer) proves this point. The test will probably fail more frequently as we move to larger multi-nodes systems. I suggest to completely remove this test, which only adds maintenance debts without testing what it is intended to.
2) Isn't there a more native way to print time_point than manually converting it to double? I'm surprised there is no `<<` operator for this type.
3) If the unit matters, then we should make it explicit in the error message: even with this patch the reader won't be able to know that it is in seconds
4) Shouldn't we make the comparison as time_point, before conversion to double, which is only here for pretty printing?

**Comment by wujingyue** [comment]
> Passing/failing the test is neither a necessary nor sufficient condition for the barrier's success/failure.

I don't think I follow this. Anyhow, for the context, this was added as a regression test for https://github.com/pytorch/pytorch/pull/129908. 

> Casting to double seems like a heavy hammer here.

Agreed -- I hope C++20 will make this easier: https://en.cppreference.com/w/cpp/chrono/duration/operator_ltlt.

**Comment by wujingyue** [comment]
> What I mean is that the unit test does not test the barrier collective

I don't follow that. This test verifies https://github.com/NVIDIA/Fuser/issues/2499, a bug in "the barrier collective" fixed by 
@eqy's https://github.com/pytorch/pytorch/pull/129908, doesn't show up again.

**Comment by samnordmann** [comment]
> > What I mean is that the unit test does not test the barrier collective
> 
> I don't follow that. This test verifies #2499, a bug in "the barrier collective" fixed by @eqy's [pytorch/pytorch#129908](https://github.com/pytorch/pytorch/pull/129908), doesn't show up again.

yes, but it is only incidental

**Comment by naoyam** [comment]
@samnordmann 

> yes, but it is only incidental

The original issue of some rank missing a proper synchronization doesn't seem just incidental, so the test itself seems to make sense to me. 

This particular failure seems to be due to how we verify the barrier behavior, which may not be very robust as Sam pointed out, but for now if it works on the system scale we usually test and benchmark, I'd say it's good enough.

One way to improve the robustness may be something like: let rank0 spin wait for 1ms (or some reasonably longer time than actual barrier latency) and call `barrier`, while the other ranks immediately call `barrier`. The barrier latency should be larger than 1ms on all ranks. This way, missing a proper synchronization should be always visible no matter how noisy the actual barrier implementation would be.

**Review by samnordmann — APPROVED** [review]
Thanks for addressing the comments!

**Comment by wujingyue** [comment]
!build

**Pull request merged**
