### PR TITLE
Add more doc for ExpandOp and BroadcastOp.

### PR DESCRIPTION
**Pull request by wujingyue**

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
LGTM.

**Comment by jjsjann123** [comment]
always feel silly that we have to wait on all CI to merge trivial PRs like this. :disappointed:

**Comment by wujingyue** [comment]
> always feel silly that we have to wait on all CI to merge trivial PRs like this. 😞

I got the impression that approved and tested PRs can be automatically merged? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by jjsjann123** [comment]
I was just talking about that we have to wait for the test to be tested. This PR is literally just updating comments. We don't need to check build before merging it. :shrug:

**Pull request merged**
