### PR TITLE
Restructure baseline benchmarks

### PR DESCRIPTION
**Pull request by Priya2698**
This PR restructures the baseline benchmarks:
1. use `with_executor` to centralize executor definitions. Thanks to @jacobhinkle for this suggestion.
2. Move torch definitions to a separate file for reuse between forward and backward benchmark files.

### CODE REVIEW

**Comment by xwang233** [comment]
!test --pybench --dev

**Comment by xwang233** [comment]
!test --pybench --dev

**Comment by Priya2698** [comment]
Benchmarking results are at: http://nv/eo9
I do not see any performance impact except for `dropout_rmsnorm_fwd` for both eager and torchcompile. I'll compare it with this week's result to see if the performance has changed since this PR should not have any perf impact.

**Review by jacobhinkle — APPROVED** [review]
LGTM

**Comment by Priya2698** [comment]
!build --dev

**Comment by Priya2698** [comment]
!test --pybench --dev

**Comment by Priya2698** [comment]
!build

**Pull request merged**
