### PR TITLE
Revert "Update Flatbuffers to v2.0.7 to support cpp17"

### PR DESCRIPTION
**Pull request by rdspring1**
Reverts NVIDIA/Fuser#283 because upstream PyTorch uses v2.0.5.

Workaround for issue #281 is to comment out https://github.com/google/flatbuffers/blob/v2.0.5/CMakeLists.txt#L254-L321 in third_party/flatbuffers

### CODE REVIEW

**Comment by mmigdal-nv** [comment]
Same issue here, thank you!

**Review by zasdfgbnm — APPROVED** [review]
I will submit a PR to PyTorch core to update it to 2.0.7, but for now, let's just keep consistent with PyTorch.

**Comment by zasdfgbnm** [comment]
BTW, "we have to keep all our submodules the same version as PyTorch" sounds like an unnecessary limitation, we should remove this limitation at some point.

**Comment by zasdfgbnm** [comment]
https://github.com/pytorch/pytorch/pull/100716

**Pull request merged**
