### PR TITLE
replaceSymbolicSizes

### PR DESCRIPTION
**Pull request by naoyam**
can't repro but this seems to be the right thing to do

Update: added a standalone repro

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff-bench

**Comment by naoyam** [comment]
@jacobhinkle As I mentioned offline, there's one test that had register usage jump, but I still think this is the right thing to do. I started the diff check with the benchmarks as well.

**Review by jacobhinkle — APPROVED** [review]
LGTM

**Comment by naoyam** [comment]
@jacobhinkle No codegen change with the benchmarks.

**Pull request merged**
