### PR TITLE
Allow cat op to accept tensors with Symbolic axes

### LINKED ISSUE #1554: Fusion definition fails when cat has symbolic inputs
The following fails at the last line
```python
from nvfuser import FusionDefinition, DataType

with FusionDefinition() as fd:
    S0 = fd.define_scalar(None, dtype=DataType.Double)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(None, dtype=DataType.Int)
    S4 = fd.define_scalar(None, dtype=DataType.Int)
    S5 = fd.define_scalar(None, dtype=DataType.Int)
    S6 = fd.define_scalar(None, dtype=DataType.Int)
    S7 = fd.define_scalar(None, dtype=DataType.Int)
    S8 = fd.define_scalar(None, dtype=DataType.Int)
    T9 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T10 = fd.define_tensor(shape=[-1, -1, -1, -1], contiguity=[True, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T11 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[2, 1, 0])
    T12 = fd.ops.mul(T10, S1)
    T13 = fd.ops.permute(T12, dims=[0, 1, 3, 2])
    T14 = fd.ops.mul(T9, S0)
    T15 = fd.ops.permute(T14, dims=[0, 2, 1, 3])
    S16 = fd.define_scalar(4, dtype=DataType.Int)
    S17 = fd.define_scalar(64, dtype=DataType.Int)
    S18 = fd.define_scalar(768, dtype=DataType.Int)
    V19 = fd.define_vector([S16, S17, S18], dtype=DataType.Int)
    T20 = fd.ops.reshape(T15, new_shape=V19)
    T21 = fd.ops.permute(T13, dims=[0, 2, 1, 3])
    S22 = fd.define_scalar(4, dtype=DataType.Int)
    S23 = fd.define_scalar(64, dtype=DataType.Int)
    S24 = fd.define_scalar(768, dtype=DataType.Int)
    V25 = fd.define_vector([S22, S23, S24], dtype=DataType.Int)
    T26 = fd.ops.reshape(T21, new_shape=V25)
    T27 = fd.ops.cat([T20, T26, T11], dim=2)
```
The error is
> RuntimeError: (inp_root_id->isIteration() || inp_root_id->isBroadcast()) && !inp_root_id->maybePartial() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/ops/alias.cpp":662, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Unsupported IterDomain to concatenate: ?S33{( (nvfuser_index_t)(768) )}rf 

The `cat` op works with both `Iteration` and `Broadcast` inputs (expanded and not), so the definition op should just accept `Symbolic` unconditionally I believe.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #1554.

### CODE REVIEW

**Comment by wujingyue** [comment]
Does this PR just need a stamp or is it concerning?

**Comment by wujingyue** [comment]
!build

**Comment by jacobhinkle** [comment]
Looks like there are real failures. I'll have a look soon.

**Comment by wujingyue** [comment]
!build

**Review by wujingyue — APPROVED** [review]

**Comment by wujingyue** [comment]
!build

**Pull request merged**
