### PR TITLE
Llu/min block size

### PR DESCRIPTION
**Pull request by liqiangxl**
Test min_threads_per_block using 3 values:
(1) One warp, so we can use single warp reduction and sync.
(2) Two warps, so we can achieve 100% occupancy since most GPUs allow 32 blocks per SM.
(3) Four warps, number recommended by the cuda-c-best-practices-guide.

Perf change from 32 to 64 is :
image
Perf change from 64 to 128
image

Analysis:
(1) Perf change from 32 to 64 is mainly due to the increase of occupancy.
(2) Perf change from 64 to 128 is mainly due to the decrease of persistent buffer size. e.g. if we use `min_threads_per_block = 64` for case `NvFuserScheduler_LayerNormFusedOp_fp16/8192/4096`. After vectorization of 8, we will start with `bdimx = 64`, then calculate `persistent batch = 8`. If use `min_threads_per_block = 128`, the calculated `persistent batch = 4`

Conclusion:
use 128.

Raw data:
https://github.com/liqiangxl/playground/tree/main/benchmarks/a100_80G/0526_block_size

### CODE REVIEW

**Comment by naoyam** [comment]
> Perf change from 64 to 128 is mainly due to the decrease of persistent buffer size. e.g. if we use min_threads_per_block = 64 for case NvFuserScheduler_LayerNormFusedOp_fp16/8192/4096. After vectorization of 8, we will start with bdimx = 64, then calculate persistent batch = 8. If use min_threads_per_block = 128, the calculated persistent batch = 4

The persistent buffer size per thread block isn't changed, right? Why does that matter?

**Comment by liqiangxl** [comment]
> > Perf change from 64 to 128 is mainly due to the decrease of persistent buffer size. e.g. if we use min_threads_per_block = 64 for case NvFuserScheduler_LayerNormFusedOp_fp16/8192/4096. After vectorization of 8, we will start with bdimx = 64, then calculate persistent batch = 8. If use min_threads_per_block = 128, the calculated persistent batch = 4
> 
> The persistent buffer size per thread block isn't changed, right? Why does that matter?

Yes. persistent buffer size per thread block is NOT changed. But this changed the work load per thread.

**Comment by naoyam** [comment]
So, why does that increase the performance as much as 3x?

**Comment by liqiangxl** [comment]
> NvFuserScheduler_LayerNormFusedOp_fp16/8192/4096

Because persistent buffer batch of 8 caused register spills while 4 does not.

**Comment by naoyam** [comment]
How much?

**Comment by liqiangxl** [comment]
> How much?

```
ptxas info    : 307 bytes gmem
ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel5ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
ptxas info    : Function properties for _ZN11CudaCodeGen7kernel5ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
ptxas         .     776 bytes stack frame, 776 bytes spill stores, 820 bytes spill loads
ptxas info    : Used 128 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]
```

**Comment by naoyam** [comment]
Why so many spill? Is this again because we underestimate? No spill with 128 threads?

**Comment by liqiangxl** [comment]
> Why so many spill? Is this again because we underestimate? No spill with 128 threads?

This is a case where we have two persistent buffers, one is float and the other one is half, total register for buffer is: (4+2)x8x**8**/4 = 96, plus overhead of 40, we have 136 ,then adjust to 128.

with 128 threads, total register for buffer is: (4+2)x8x**4**/4 = 48, plus overhead of 40, we have 88 ,then adjust to 80.
```
ptxas info    : 307 bytes gmem
ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel4ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
ptxas info    : Function properties for _ZN11CudaCodeGen7kernel4ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
ptxas         .     8 bytes stack frame, 4 bytes spill stores, 6 bytes spill loads
ptxas info    : Used 80 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]
```

**Comment by naoyam** [comment]
> > Why so many spill? Is this again because we underestimate? No spill with 128 threads?
> 
> This is a case where we have two persistent buffers, one is float and the other one is half, total register for buffer is: (4+2)x8x**8**/4 = 96, plus overhead of 40, we have 136 ,then adjust to 128.
> 

What's the actual minimum register count? 700 bytes of spill seems too much just for the reduction by 8, no?

**Comment by liqiangxl** [comment]
> > > Why so many spill? Is this again because we underestimate? No spill with 128 threads?
> > 
> > 
> > This is a case where we have two persistent buffers, one is float and the other one is half, total register for buffer is: (4+2)x8x**8**/4 = 96, plus overhead of 40, we have 136 ,then adjust to 128.
> 
> What's the actual minimum register count? 700 bytes of spill seems too much just for the reduction by 8, no?

155 registers. a little higher than the estimated value of 136.

root@nvdl-a112-d002:/opt/pytorch/playground/benchmarks# PYTORCH_NVFUSER_MAX_REG_COUNT=255 PYTORCH_NVFUSER_DUMP=ptxas_verbose /opt/pytorch/nvfuser/build/nvfuser_bench --benchmark_min_time=0.000001 --benchmark_filter=NvFuserScheduler_LayerNormFusedOp_fp16
```
NvFuserScheduler_TIMM_LayerNorm_fp16___GRAPH/NvFuserScheduler_TIMM_LayerNorm_fp16 will be repeated at least 120 times.
The number of inputs is very large. Baseline_TIMM_LayerNorm_fp16 will be repeated at least 270 times.
The number of inputs is very large. Baseline_TIMM_LayerNorm_fp16 will be repeated at least 120 times.
2023-05-26T11:59:50-07:00
Running /opt/pytorch/nvfuser/build/nvfuser_bench
Run on (64 X 3593.2 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x32)
  L1 Instruction 32 KiB (x32)
  L2 Unified 512 KiB (x32)
  L3 Unified 16384 KiB (x8)
Load Average: 0.61, 2.38, 2.81
ptxas info    : 307 bytes gmem
ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
ptxas info    : Function properties for _ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 155 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                            Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
NvFuserScheduler_LayerNormFusedOp_fp16___GRAPH/NvFuserScheduler_LayerNormFusedOp_fp16/8192/4096/manual_time        176 us          432 us            1 bytes_per_second=709.884G/s Red On Fastest Dim // Persistent Kernel //  // Iteration Domain:  // Inner Reduction Domain: cross block reduction / pad to warp / persistent batch - 8 / vectorize / factor 8/Launch_Parameters[block(1/1/64)/grid(1/1/8192)/256]
```

**Comment by naoyam** [comment]
It doesn't seem just a little since we set the maximum of 128. What is the actual count with 128 threads?

**Comment by liqiangxl** [comment]
> PYTORCH_NVFUSER_MAX_REG_COUNT=255 PYTORCH_NVFUSER_DUMP=ptxas_verbose /opt/pytorch/nvfuser/build/nvfuser_bench --benchmark_min_time=0.000001 --benchmark_filter=NvFuserScheduler_LayerNormFusedOp_fp16



> It doesn't seem just a little since we set the maximum of 128. What is the actual count with 128 threads?

Only 91, which is very close to our estimated value of 88. I am not surprised by these data because the register estimation and heuristics was tunned using a initial threads per block of 128 (4 warp schedulers).
```
ptxas info    : 307 bytes gmem
ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
ptxas info    : Function properties for _ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 91 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]
```

**Comment by liqiangxl** [comment]
> > > PYTORCH_NVFUSER_MAX_REG_COUNT=255 PYTORCH_NVFUSER_DUMP=ptxas_verbose /opt/pytorch/nvfuser/build/nvfuser_bench --benchmark_min_time=0.000001 --benchmark_filter=NvFuserScheduler_LayerNormFusedOp_fp16
> > 
> > 
> > > It doesn't seem just a little since we set the maximum of 128. What is the actual count with 128 threads?
> > 
> > 
> > Only 91, which is very close to our estimated value of 88. I am not surprised by these data because the register estimation and heuristics was tunned using a initial threads per block of 128 (4 warp schedulers).
> > ```
> > ptxas info    : 307 bytes gmem
> > ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
> > ptxas info    : Function properties for _ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
> > ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> > ptxas info    : Used 91 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]
> > ``p`
> 
> Why do you think this is expected? Why do we underestimate the register usage with 64 threads so much?

Looks like what matters is the batch size of persistent buffers. For 64 threads, the batch is 8. For 128 threads, the batch is 4.

(1) For 64 threads per block, hidden size of 64 x 8 x (4, 8, 10)
Buffer     Batch:---- 4--------8----10
Estimated Reg:----88----136--160
Actual       Reg:----91----155--188

(2) For 128 threads per block, hidden size of 128 x 8 x (4, 8, 10)
Buffer     Batch:---- 4--------8----10
Estimated Reg:----88----136--160
Actual       Reg:----91----155--188

So,
(1) for 10 batches, under estimated by  1 - 160/188 = 14.9%
(2) for 8 batches, under estimated by  1 - 136/155 = 12.2%
(3) for 4 batches, under estimated by 1 - 88/91    = 3.3%

The under estimation is because this case is a fused op while the original heuristics was tunned using a pure layer norm.
If 128 threads per block also hit a case with 8 batches and register usaged is 128 (reduced from 136) rather than 155, the bandwidth is also 3 times lower than case with 155 registers. 260 GB/s VS 850 GB/s.

Conclusion:
The persistent buffer issue in this case is solved in #419. But we have no control of other fused ops that may introduce an additional persistent buffer. So the revision is probabally (1) as you previously suggested, we can also limit the adjustment by an absolute value instead of just a relative value. `Maybe something like X - min(B, A * X) so that at most reducing B registers.` B should be smaller than 8 to avoid doing this 136 -> 128 adjustment. (2) stop using estimaged register if there are more than 1 buffer since we are entering an untested zone.

**Comment by naoyam** [comment]
> > > > PYTORCH_NVFUSER_MAX_REG_COUNT=255 PYTORCH_NVFUSER_DUMP=ptxas_verbose /opt/pytorch/nvfuser/build/nvfuser_bench --benchmark_min_time=0.000001 --benchmark_filter=NvFuserScheduler_LayerNormFusedOp_fp16
> > > 
> > > 
> > > > It doesn't seem just a little since we set the maximum of 128. What is the actual count with 128 threads?
> > > 
> > > 
> > > Only 91, which is very close to our estimated value of 88. I am not surprised by these data because the register estimation and heuristics was tunned using a initial threads per block of 128 (4 warp schedulers).
> > > ```
> > > ptxas info    : 307 bytes gmem
> > > ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
> > > ptxas info    : Function properties for _ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
> > > ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> > > ptxas info    : Used 91 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]
> > > ``p`
> > > ```
> > 
> > 
> > Why do you think this is expected? Why do we underestimate the register usage with 64 threads so much?
> 
> Looks like what matters is the batch size of persistent buffers. For 64 threads, the batch is 8. For 128 threads, the batch is 4.
> 
> (1) For 64 threads per block, hidden size of 64 x 8 x (4, 8, 10) Buffer Batch:---- 4--------8----10 Estimated Reg:----88----136--160 Actual Reg:----91----155--188
> 
> (2) For 128 threads per block, hidden size of 128 x 8 x (4, 8, 10) Buffer Batch:---- 4--------8----10 Estimated Reg:----88----136--160 Actual Reg:----91----155--188
> 
> So, (1) for 10 batches, under estimated by 1 - 160/188 = 14.9% (2) for 8 batches, under estimated by 1 - 136/155 = 12.2% (3) for 4 batches, under estimated by 1 - 88/91 = 3.3%

Wow, interesting. So from batch size of 8 to 10, the register usage jumps from 155 to 188, meaning using 33 more registers even just for the increase of the batch size by 2? Any idea why?

> 
> The under estimation is because this case is a fused op while the original heuristics was tunned using a pure layer norm. 

Why could a fused op affect the increase? I'd understand that with fused ops maybe the overhead factor would be increased, but that doesn't seem to explain the above non-linear increase.

**Comment by naoyam** [comment]
> > > > > PYTORCH_NVFUSER_MAX_REG_COUNT=255 PYTORCH_NVFUSER_DUMP=ptxas_verbose /opt/pytorch/nvfuser/build/nvfuser_bench --benchmark_min_time=0.000001 --benchmark_filter=NvFuserScheduler_LayerNormFusedOp_fp16
> > > > 
> > > > 
> > > > > It doesn't seem just a little since we set the maximum of 128. What is the actual count with 128 threads?
> > > > 
> > > > 
> > > > Only 91, which is very close to our estimated value of 88. I am not surprised by these data because the register estimation and heuristics was tunned using a initial threads per block of 128 (4 warp schedulers).
> > > > ```
> > > > ptxas info    : 307 bytes gmem
> > > > ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_' for 'sm_80'
> > > > ptxas info    : Function properties for _ZN11CudaCodeGen7kernel1ENS_6TensorINS_6__halfELi1ELi1EEENS0_IS1_Li2ELi2EEES2_S2_S2_S3_
> > > > ptxas         .     0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
> > > > ptxas info    : Used 91 registers, 16 bytes smem, 464 bytes cmem[0], 8 bytes cmem[2]
> > > > ``p`
> > > > ```
> > > 
> > > 
> > > Why do you think this is expected? Why do we underestimate the register usage with 64 threads so much?
> > 
> > 
> > Looks like what matters is the batch size of persistent buffers. For 64 threads, the batch is 8. For 128 threads, the batch is 4.
> > (1) For 64 threads per block, hidden size of 64 x 8 x (4, 8, 10) Buffer Batch:---- 4--------8----10 Estimated Reg:----88----136--160 Actual Reg:----91----155--188
> > (2) For 128 threads per block, hidden size of 128 x 8 x (4, 8, 10) Buffer Batch:---- 4--------8----10 Estimated Reg:----88----136--160 Actual Reg:----91----155--188
> > So, (1) for 10 batches, under estimated by 1 - 160/188 = 14.9% (2) for 8 batches, under estimated by 1 - 136/155 = 12.2% (3) for 4 batches, under estimated by 1 - 88/91 = 3.3%
> 
> > Wow, interesting. So from batch size of 8 to 10, the register usage jumps from 155 to 188, meaning using 33 more registers even just for the increase of the batch size by 2? Any idea why?
> 
> There is a vectorization factor of 8. So the increased buffer size is 16. And increased register should be 16 x (2+4)/4 = 24
> 

What does the case with no fused op look like? Does it also show a similar trend?

I wonder if we should also account for the register usage due to unrolling. That was I empirically observed with grid outer normalization, so I did:

https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/normalization_utils.cpp#L166

Since it's vectorized by 8, increasing the batch size by 1 would expand the unrolled iteration count by 8. Assuming `nvfuser_index_t` is `int`, it could imply 8 more registers, so increasing the batch size by 2 would lead to `24 + 8 * 2 = 40` more registers. That's larger than the actual increase of 33, which is likely because the compiler doesn't just allocate a new register for each loop iteration.

This behavior shouldn't depend on if there are fused ops or not, so let's see the non-fused case.

And assuming the above speculation is right, it seems the register usage of the 64-thread/batch-8 case is still better than the 128-thread/batch-4 case as the total number of registers per thread block is 9920 vs 11648. What is the occupancy of the 64-thread case? Can six blocks be active?

**Comment by liqiangxl** [comment]
> What does the case with no fused op look like? Does it also show a similar trend?
For layer norm without fused op, the estimated is almost identical to what is actually used and there is no spill. For batch of 4, 8, and 10 the `estimated (actual)` usages are `56 (55), 72 (72), 80 (80).`

>What is the occupancy of the 64-thread case? Can six blocks be active?
Yes. blocks_per_sm= 6, warps_per_sm= 12, occupancy= 18.75%

**Comment by naoyam** [comment]
> > What does the case with no fused op look like? Does it also show a similar trend?
> 
> For layer norm without fused op, the estimated is almost identical to what is actually used and there is no spill. For batch of 4, 8, and 10 the `estimated (actual)` usages are `56 (55), 72 (72), 80 (80).`

OK, so that looks very different from the fused case, and we have no idea why. This seems like a problem we should look into more closely since the max-register heuristic could result in significant spills and we don't exactly know when it would happen.

> 
> > What is the occupancy of the 64-thread case? Can six blocks be active?
> 
> Yes. blocks_per_sm= 6, warps_per_sm= 12, occupancy= 18.75%

So, assuming the active blocks in the case of 124 threads is 5, the active warps should be 20. While the active warp count is 12 with the 64-thread case, its work per thread is 2x, so the effective occupancy should be 24 vs 20. Still don't understand why the 64-thread case can be slower than the 128-thread case.

**Comment by liqiangxl** [comment]
> effective occupancy should be 24

Can we do this conversion? I think the workload per thread is doubled but these workload are serialized and we don't have an overlap between memcpy and computation. However in the other case we may have overlap by swithing warps.

What's the next step we should do? As previously posted, we may have two options:
(1) as you previously suggested, we can also limit the adjustment by an absolute value instead of just a relative value. Maybe something like X - min(B, A * X) so that at most reducing B registers. B should be smaller than 8 to avoid doing this 136 -> 128 adjustment.
(2) stop using estimaged register if there are more than 1 buffer since we are entering an untested zone.

**Comment by naoyam** [comment]
> > effective occupancy should be 24
> 
> Can we do this conversion? I think the workload per thread is doubled but these workload are serialized and we don't have an overlap between memcpy and computation. However in the other case we may have overlap by swithing warps.

That might be what's actually happening, but isn't everything unrolled? Shouldn't all the loads and subsequent uses be independent until the cross-block reduction? 

> 
> What's the next step we should do? As previously posted, we may have two options: (1) as you previously suggested, we can also limit the adjustment by an absolute value instead of just a relative value. Maybe something like X - min(B, A * X) so that at most reducing B registers. B should be smaller than 8 to avoid doing this 136 -> 128 adjustment. (2) stop using estimaged register if there are more than 1 buffer since we are entering an untested zone.

I think there are two interesting results here that we may want to incorporate into the overall heuristics design. So far, we generally assume that:

- Prefer smaller thread blocks with larger work-per-thread factors. Compared to larger blocks with smaller work per thread, it should lead to more efficient register usage, which would make the overall effective occupancy higher and achieve better performance
- Register usage count should linearly depend on the per-thread work factor

Clearly, both of them are not the case here. I'd be hesitant to make any heuristic change without understanding why.

**Pull request merged**
