### PR TITLE
Forbid non-tensor outputs.

### LINKED ISSUE #1172: "IndexError: _Map_base::at" with scalar output
Reproducer:
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    S0 = fd.define_scalar(None, dtype=DataType.Double)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    T2 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    T3 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    S4 = fd.define_scalar(1.41421, dtype=DataType.Double)
    S5 = fd.ops.reciprocal(S4)
    T6 = fd.ops.mul(T3, S5)
    T7 = fd.ops.erf(T6)
    S8 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T9 = fd.ops.mul(S8, T7)
    S10 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T11 = fd.ops.add(S10, T9)
    T12 = fd.ops.mul(T2, T11)
    T13 = fd.ops.mul(T2, T3)
    S14 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T15 = fd.ops.mul(S14, T13)
    T16 = fd.ops.mul(T15, S1)
    S17 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T18 = fd.ops.mul(T16, S17)
    S19 = fd.define_scalar(3.14159, dtype=DataType.Double)
    S20 = fd.ops.sqrt(S19)
    S21 = fd.ops.reciprocal(S20)
    T22 = fd.ops.mul(T18, S21)
    T23 = fd.ops.neg(T6)
    T24 = fd.ops.mul(T23, T6)
    T25 = fd.ops.exp(T24)
    T26 = fd.ops.mul(T22, T25)
    S27 = fd.ops.reciprocal(S0)
    T28 = fd.ops.mul(T26, S27)
    T29 = fd.ops.add(T12, T28)
    fd.add_output(S20)
    fd.add_output(T29)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    1.4142135623730951,
    0.5,
    torch.randn((44800,), dtype=torch.float32, device='cuda:0').as_strided((5, 5, 1792), (8960, 1792, 1)),
    torch.randn((44800,), dtype=torch.float32, device='cuda:0').as_strided((5, 5, 1792), (8960, 1792, 1)),
]
fd.execute(inputs)
```
```py
Traceback (most recent call last):
  File "/home/iyashchuk/dev/nvfuser/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
IndexError: _Map_base::at
```

### PR DESCRIPTION
**Pull request by wujingyue**
Previously, the check was done only at `FusionExecutor::compileFusion`. However, the segmenter [skips non-tensor
outputs](https://github.com/NVIDIA/Fuser/blob/bce26ef4589066bd9765cea2ca61254031cd26a3/csrc/fusion_segmenter.cpp#L3286) before `FusionExecutor::compileFusion` sees them. This happens for users of the higher-level `FusionExecutorCache`.

The only exception is that we allow PipelineVal whose original value is a TensorView. 

Fixes #1172.

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
Thanks for the fix.

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
Apparently, three tests are unhappy with this PR... 👀 

```
00:20:34 [  FAILED  ] NVFuserTest.FusionTopoSort_CUDA
00:20:34 [  FAILED  ] NVFuserTest.Pipeline_CUDA
00:20:34 [  FAILED  ] MultiDeviceTest.Pipeline
```

**Comment by jacobhinkle** [comment]
> Apparently, three tests are unhappy with this PR... 👀
> 
> ```
> 00:20:34 [  FAILED  ] NVFuserTest.FusionTopoSort_CUDA
> 00:20:34 [  FAILED  ] NVFuserTest.Pipeline_CUDA
> 00:20:34 [  FAILED  ] MultiDeviceTest.Pipeline
> ```

Looks like you could change the TopoSort example to use TVs for the outputs. For the Pipeline tests you may need to detect `PipelineVal` and in those cases check that `val->as<PipelineVal>->getOriginalVal()->asA<TensorView>()`.

**Comment by wujingyue** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]

**Pull request merged**
