### PR TITLE
Revert "Remove NVFUSER_DISTRIBUTED.  (#2155)"

### PR DESCRIPTION
**Pull request by Aidyn-A**
This PR reverts #2155.

The reason for that is we are hitting the following error on Jetson:
```
Traceback (most recent call last):
  File "/opt/pytorch/fuser/setup.py", line 423, in <module>
    main()
  File "/opt/pytorch/fuser/setup.py", line 365, in main
    cmake()
  File "/opt/pytorch/fuser/setup.py", line 303, in cmake
    raise RuntimeError(
RuntimeError: nvFuser requires PyTorch to be built with USE_DISTRIBUTED on.
```

cc @wujingyue @xwang233

### CODE REVIEW

**Comment by xwang233** [comment]
I suggest we use a warning or an optional env var to bypass this check, instead of reverting the entire PR.

**Comment by xwang233** [comment]
@Aidyn-A  can you try if commenting out the check resolves the build issue on Jetson?

**Comment by wujingyue** [comment]
> @Aidyn-A can you try if commenting out the check resolves the build issue on Jetson?

It'll likely cause a linker issue -- declarations in c10d headers are used but not defined. Won't it? 

That being said, I think it's safer and quicker to revert the PR before trying out other solutions.

**Comment by Aidyn-A** [comment]
Yeah, bypassing the check indeed causes linking failures:
```
communicator.cpp:(.text+0x308): undefined reference to `c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&)'
communicator.cpp:(.text+0xfd0): undefined reference to `c10d::PrefixStore::PrefixStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::intrusive_ptr<c10d::Store, c10::detail::intrusive_target_default_null_type<c10d::Store> >)'
collect2: error: ld returned 1 exit status
```

**Comment by wujingyue** [comment]
!build --dist

**Pull request merged**
