### PR TITLE
Fix error message: disambiguate 'name's.

### PR DESCRIPTION
**Pull request by tfogal**
The `name` argument shadows the member variable that was meant to be referenced here. This changes the error message to e.g.:

  Field FOO not found in struct Tensor<float, 2, 2>

### CODE REVIEW

**Comment by tfogal** [comment]
!build

**Review by zasdfgbnm — APPROVED** [review]

**Comment by tfogal** [comment]
!build

**Comment by tfogal** [comment]
!build

**Comment by tfogal** [comment]
Infra failure:
```
$ git clone --recursive https://github.com/nvidia/fuser [...obfuscated...]
Cloning into 'Fuser'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3354 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
```
trying again.

**Comment by tfogal** [comment]
!build

**Comment by tfogal** [comment]
!build

**Comment by tfogal** [comment]
!build

**Comment by tfogal** [comment]
Guess it passed this time :-)

Thanks much for merging! I seemed to have struck a series of unfortunate windows when testing this in CI there, hah

**Pull request merged**
