### PR TITLE
FusionExecutorCache runs sharding-related preseg passes. 

### PR DESCRIPTION
**Pull request by wujingyue**
Separated from #2635. This implements step 4 of [this plan](https://docs.google.com/document/d/1Wvh_vJYmA_LETfVNovb8mXPK95zmPOTUccauF-DX2h8/edit).

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

**Review by naoyam — COMMENTED** [review]
LGTM. I'll let @cowanmeg give a stamp.

**Comment by wujingyue** [comment]
!build

**Review by cowanmeg — APPROVED** [review]
LGTM as well! Thanks for splitting this off into a smaller PR

**Pull request merged**
