### PR TITLE
add sync to warp reduction runtime avoid smem data race

### PR DESCRIPTION
**Pull request by liqiangxl**
Add sync to warp reduction runtime avoid smem data race. It solves #271

### CODE REVIEW

**Comment by liqiangxl** [comment]
doubled tested. The error is gone. Originally we are doing 2 reductions per block with bdimy = 2. However, current warp reduction only supports bdimy = 1. So the validation error may happen if the racing is happening a lot.

**Comment by naoyam** [comment]
I actually didn't remember it doesn't work when blockDim.y > 1. If so, the codegen backend should not use the warp reduction. IIRC, this is where we decide if it's valid:

https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/utils.h#L107-L109

Should the function need a fix?

**Comment by liqiangxl** [comment]
> I actually didn't remember it doesn't work when blockDim.y > 1. If so, the codegen backend should not use the warp reduction. IIRC, this is where we decide if it's valid:
> 
> https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/utils.h#L107-L109
> 
> Should the function need a fix?

The implementation of `warpReduceTIDX` seems support ` blockDim.y > 1`, I need to check what is the root cause.

**Comment by liqiangxl** [comment]
In the generated code we have two warp reductions immediately followed by two block broadcasts, all these four ops are using the same shared memory address. There is a lack of sync at the end of warp reduction.
```
    warp::warpReduceTIDX<false, true>(T8[0], T31[0], [](float &a, float b) { a = a + b; }, static_cast<float*>(shared_mem), true, static_cast<float>(0.00000000000000000e+00));
    warp::warpReduceTIDX<false, true>(T11[0], T37[0], [](float &a, float b) { a = a + b; }, static_cast<float*>(shared_mem), true, static_cast<float>(0.00000000000000000e+00));

    float T9[1];
    broadcast::blockBroadcast<true, false, false, true>(T9[0], T8[0], static_cast<float*>(shared_mem), true);
    float T12[1];
    broadcast::blockBroadcast<true, false, false, true>(T12[0], T11[0], static_cast<float*>(shared_mem), true);

```
#271 is fixed after a sync is added.

**Review by naoyam — APPROVED** [review]
Nice catch! Thanks for the fix.

**Pull request merged**
