### PR TITLE
Change Serde Enum Syntax

### PR DESCRIPTION
**Pull request by rdspring1**
This PR enables the `scoped_enums` flag when compiling the flatbuffers schema. The generated header file now use the strongly typed enum and follows regular enum syntax. See `no-prefix` and `scoped_enums` flags in https://flatbuffers.dev/flatbuffers_guide_using_schema_compiler.html for more details.

e.g., The PR changes syntax from Flatbuffers style `serde::RecordType_End` to standard cpp syntax `serde::RecordType::End`

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Review by jjsjann123 — APPROVED** [review]
Looks like just mechanical changes.
I do like the new style more. :shipit:

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Pull request merged**
