### PR TITLE
Rewrite sync insertion for async expressions with commit-wait flavor (`wgmma`, TMA store)

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This PR changes how we insert async wait expressions on async operations that have a commit-wait flavor (`wgmma`, TMA store). In the past, we always just insert a `commit; wait 0;` right after the async operation itself in the `ReadAfterWriteSyncs` pass, which means, we just force making these async operations synchronous. With this PR, I have changed it to:
- `ReadAfterWriteSyncs` will only insert the RAW async wait before the first read, just like how `__syncthreads();` are inserted.
- Added a new pass `WarAsyncWaitInserter` that runs after the circular buffering pass that will be responsible for WAR async waits.

Sketch of generated code for the `HopperMatmulTest.HSH_NT_128BSwizzle` test with `stages=4` and `prefetch=2`:

```C++
// prologue loop:
for i in 0..prefetch :
  TMA load A for stage i;
  TMA load B for stage i;
// main loop:
for i in 0..N-prefetch:
  TMA load A for stage (i + prefetch) % num_stages;
  TMA load B for stage (i + prefetch) % num_stages;
  wait for TMA load of stage i % num_stages;
  wgmma;
  commit wgmma;
  wait wgmma num_stages - prefetch - 1;
// epilogue loop:
for i in N-prefetch..N:
  wait for TMA load of stage i % num_stages;
  wgmma;
commit wgmma;
wait wgmma 0;
store result from register to gmem
```
where the commit and wait of wgmma in the main loop is inserted by the `WarAsyncWaitInserter` pass, and the top level commit and wait of wgmma is inserted by the `ReadAfterWriteSyncs` pass.

Note that the `cp.async` is also an async expression of the same flavor. Instead of unifying it with the new sync insertion approach, I decided not to touch it to save my time.

Perf of `HopperMatmulTest.HSH_NT_128BSwizzle`:

Looks like pipelining MMA has little perf benefit, but on the other hand, changing the epilogue from:
```C++
for:
  wait TMA load;
  wgmma;
  commit wgmma;
  wait wgmma 0;
```

into 

```C++
for:
  wait TMA load;
  wgmma;
commit wgmma;
wait wgmma 0;
```

does help the perf (benchmarked with `stages=4`, `prefetch=3`):

```
 Time (%)  Total Time (ns)  Instances  Avg (ns)   Med (ns)   Min (ns)  Max (ns)  StdDev (ns)                                                  Name                                                
 --------  ---------------  ---------  ---------  ---------  --------  --------  -----------  ----------------------------------------------------------------------------------------------------
     14.9          1325753          1  1325753.0  1325753.0   1325753   1325753          0.0  <unnamed>::nvfuser_none_f0_c0_r0_g0(<unnamed>::Tensor<<unnamed>::__half, (int)3, (int)3>, <unnamed>…
      8.8           783100          1   783100.0   783100.0    783100    783100          0.0  nvjet_hsh_192x192_64x3_2x1_v_bz_coopB_NTN   
```

Perf nvFuser/cuBLAS: `59%`, previously `55.7%` according to https://github.com/NVIDIA/Fuser/issues/3137.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
!build --diff

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build --diff

**Comment by zasdfgbnm** [comment]
!build --diff

**Comment by naoyam** [comment]
```
// main loop:
for 0..N-2:
  TMA load A;
  TMA load B;
  wait for TMA load;
  wgmma;
  commit wgmma;
  wait wgmma 1;
```

Does `wait wgmma 1;` wait for the `wgmma` issued right before it? I suppose previously it was 

```
// main loop:
for 0..N-2:
  TMA load A;
  TMA load B;
  wait for TMA load;
  wgmma;
  commit wgmma;
  wait wgmma 0;
```

IIRC, `0` of `wait wgmma` means it waits all of pending `wgmma` instructions, right?

**Comment by zasdfgbnm** [comment]
> Does wait wgmma 1; wait for the wgmma issued right before it? I suppose previously it was

Not sure what "the wgmma issued right before it" means. If it refers to the wgmma in the previous iteration, then yes.

According to https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#asynchronous-warpgroup-level-matrix-instructions-wgmma-wait-group:

> `wgmma.wait_group` instruction will cause the executing thread to wait until only N or fewer of the most recent wgmma-groups are pending and all the prior wgmma-groups committed by the executing threads are complete. 

> IIRC, `0` of `wait wgmma` means it waits all of pending `wgmma` instructions, right?

Yes

**Comment by naoyam** [comment]
> > Does wait wgmma 1; wait for the wgmma issued right before it? I suppose previously it was
> 
> Not sure what "the wgmma issued right before it" means. If it refers to the wgmma in the previous iteration, then yes.
> 
> According to https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#asynchronous-warpgroup-level-matrix-instructions-wgmma-wait-group:
> 
> > `wgmma.wait_group` instruction will cause the executing thread to wait until only N or fewer of the most recent wgmma-groups are pending and all the prior wgmma-groups committed by the executing threads are complete.
> 

Thanks for the pointer. That clarified my understanding. For whatever reason, I often get confused and assume that the N parameter means the oldest N calls are synchronized. 

> And
> 
> > IIRC, `0` of `wait wgmma` means it waits all of pending `wgmma` instructions, right?
> 
> Yes

Thanks

**Comment by naoyam** [comment]
> Sketch of generated code for the `HopperMatmulTest.HSH_NT_128BSwizzle` test with `stages=4` and `prefetch=2`:
> 
> ```c++
> // prologue loop:
> for 0..2 :
>   TMA load A;
>   TMA load B;
> // main loop:
> for 0..N-2:
>   TMA load A;
>   TMA load B;
>   wait for TMA load;
>   wgmma;
>   commit wgmma;
>   wait wgmma 1;
> // epilogue loop:
> for N-2..N:
>   wait for TMA load;
>   wgmma;
> commit wgmma;
> wait wgmma 0;
> store result from register to gmem
> ```

Could you please rewrite this pseudo code with the number of stages and prefetch distance being parameterized? For example, IIUC, `wait wgmma 1;` should be `wait wgmma P-1;`, where `P` is the number of prefetch distance.

**Comment by zasdfgbnm** [comment]
> Could you please rewrite this pseudo code with the number of stages and prefetch distance being parameterized? For example, IIUC, `wait wgmma 1;` should be `wait wgmma P-1;`, where `P` is the number of prefetch distance.

Updated the original comment https://github.com/NVIDIA/Fuser/pull/3191#issue-2589928835

**Comment by zasdfgbnm** [comment]
> For example, IIUC, `wait wgmma 1;` should be `wait wgmma P-1;`, where `P` is the number of prefetch distance.

It should be `num_stages - P - 1`

**Comment by zasdfgbnm** [comment]
!build --diff

**Review by naoyam — APPROVED** [review]
LGTM, but the CI failure is a real failure?

**Comment by zasdfgbnm** [comment]
> LGTM, but the CI failure is a real failure?

Good question, I am also wondering the same. It is a segfault at exit. According to my past experience, this is mostly due to wrong tear-down order of dependencies (for example trying to destroy a cuBLAS handle after the CUDA context has been destroyed), this PR does not change any at-exit behavior, so I hope it is not. Let me see if I can rerun the failed pipeline.

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
I will ignore that CI failure for now and just merge. It takes forever to get a result on H100.

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
