### PR TITLE
fixing multidevice build

### PR DESCRIPTION
**Pull request by jjsjann123**
API change coming from https://github.com/pytorch/pytorch/pull/119421

### CODE REVIEW

**Comment by jjsjann123** [comment]
patching issue mentioned in: https://github.com/NVIDIA/Fuser/pull/1752#issuecomment-1937897678

My naive understanding going through the code base is that, we are always using buffer count of 1 any way from the assert, so the API change here really shouldn't have changed anything. cc'ing @samnordmann

**Comment by jjsjann123** [comment]
!build

**Review by kwen2501 — APPROVED** [review]
LGTM!
Sorry about the break :)

**Review by naoyam — APPROVED** [review]

**Comment by naoyam** [comment]
The build still seems failing. Does it also need the version guard?

**Comment by naoyam** [comment]
```
/opt/pytorch/nvfuser/csrc/multidevice/communication.cpp
#12 63.49 /opt/pytorch/nvfuser/csrc/multidevice/communication.cpp: In member function ‘virtual c10::intrusive_ptr<c10d::Work> nvfuser::Reduce::post(nvfuser::Communicator&, std::optional<nvfuser::CommunicatorBackend>)’:
#12 63.49 /opt/pytorch/nvfuser/csrc/multidevice/communication.cpp:240:15: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<at::Tensor>, at::Tensor>::value_type’ {aka ‘at::Tensor’} to ‘std::vector<at::Tensor>&’
#12 63.49   240 |         buf.at(0), params_.src_bufs.at(0), options);
```

**Comment by jjsjann123** [comment]
> The build still seems failing. Does it also need the version guard?

I believe internal failure are because we are building against our container image.. which has an outdated code base. cc'ing @xwang233 to confirm that.

**Comment by xwang233** [comment]
Yes, the internal image has pytorch from last night, which has the PR reverted and not-yet relanded.

**Comment by jjsjann123** [comment]
> The build still seems failing. Does it also need the version guard?

I don't think we can version guard anything here. Since it's API change on ToT...

**Comment by jjsjann123** [comment]
Merging as-is since nightly build succeeded.

**Pull request merged**
