### PR TITLE
Add new test `HopperSS.MultipleTile`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Adding a new test checking stride inference, reqiures https://github.com/NVIDIA/Fuser/pull/3002

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
Looks good to my eyes

**Comment by zasdfgbnm** [comment]
!build

**Review by jacobhinkle — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Comment by zasdfgbnm** [comment]
!build

**Pull request merged**
