### PR TITLE
Internal only Python API matmul functions

### PR DESCRIPTION
**Pull request by kevinstephano**
Three internal matmul functions are exposed.  These is not intended to be the final matmul API, therefore, they are marked as internal as the final version should not be layout specific.
- `ops._matmul_nn` 
- `ops._matmul_nt`
- `ops._matmul_tn`
- `ops._matmul_tt`

We need to figure out how we want to represent and communicate, top-to-bottom, stride ordering in order to determine the matmul layout. In order to plumb ops for measurement and scheduling experimentation, all the way up to the python API, these 4 functions are explicitly being  written separately but are intended to be integrated into one function.

**Pytorch's `matmul` Implementation Notes**:
Pytorch Matmul's are calculating (M x K) @ (K x M) = [M, N]                                                                                                                                                                                                                              Pytorch has a default output of row-major (N) which is not to be confused with Cublas that defaults to column-major (M) such that Pytorch's Eager mode swaps input1 and input2 when giving them to Cublas such that N is produced on the inner dimension.

**Pytorch's `Linear` Implementation Notes**:                                                                                                                                                                                                                                                               
Pytorch's Linear operation defaults to producing a Column-major output [N, M] for it's forward pass that is the opposite if the same inputs were presented to Pytorch's matmul where input1 = weights and input2 = activations.

TODOS:

- [x] Write up PR description
- [ ] Make Python tests
- [ ] Feedback 
- [x]  Add 2-D Tensor asserts for now.

### CODE REVIEW

**Comment by kevinstephano** [comment]
I started this draft PR for exposing explicit matmul functions all the way up through Python.  My expectation is we will switch to a unified function `ops.matmul` instead of explicit layout based functions.  In the meantime, is there anything you thing should be be included or changed? cc @zasdfgbnm @mmigdal-nv @drzejan2

**Comment by zasdfgbnm** [comment]
I think your current approach makes sense as a temporary solution. Regarding NN, we are not supporting NN yet, but I think you can leave it the way you are currently doing. I will change this when I added NN support.

And side note: I will soon post a PR that makes the definition of matmul even harder: the users will not only need to know the layout, but also they need to specify whether they are defining matmul for Volta, Turing, Ampere, or Hopper. I will take care of the frontend change needed in that PR. And the after that PR, I will start cleaning things up, and eventually, the users would just need to define Mul-Sum.

**Comment by zasdfgbnm** [comment]
FYI: I am changing the definition of matmul in https://github.com/NVIDIA/Fuser/pull/234 and adding NN support. This PR does the required refactor to enable NN support, but it also make the already bad user interface even worse. Users will need to specify the architecture when defining matmul. See https://github.com/NVIDIA/Fuser/pull/234/files#diff-f94b49585cbc077ddcf917a6f97496d1c5f289bb95c174caf4dc5fbd18c529b7 for how things has changed.

**Comment by kevinstephano** [comment]
Replacing this PR with a PR #272.

**Pull request closed without merging**
