### PR TITLE
Llu/welford complex

### PR DESCRIPTION
**Pull request by liqiangxl**
deleted python api, which caused python frontend error.
https://github.com/NVIDIA/Fuser/pull/91

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
haha that's an easy fix.

Do we still want the python API tho?

**Comment by jjsjann123** [comment]
!build

**Comment by liqiangxl** [comment]
> Do we still want the python API tho?

Nobody asked for that. But there is no harm if it can be done easily. I just don't understand why the previous version crashed the python frontend.

**Comment by jjsjann123** [comment]
It's good to merge now. I'm pulling the button

**Pull request merged**
