### PR TITLE
Bump flatbuffers to match upstream version (v23.3.3)

### PR DESCRIPTION
**Pull request by rdspring1**
Fixes https://github.com/NVIDIA/Fuser/issues/281
Related: https://github.com/pytorch/pytorch/pull/100716

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by jjsjann123** [comment]
lol `!build` won't work since it uses last successful container, which has an out-dated flatbuffer on upstream.

**Comment by jjsjann123** [comment]
I hate the new github GUI. I can no longer see which submodule commit is at. But I'm gonna trust you that it's the same one as with what upstream has

**Comment by jjsjann123** [comment]
@rdspring1 Let's verify the fix locally since CI can't do anything for us here.

**Comment by rdspring1** [comment]
You can see the flatbuffers version here: https://github.com/NVIDIA/Fuser/tree/bump_flatbuffers/third_party

**Comment by jjsjann123** [comment]
:shipit:

**Pull request merged**
